-- Tennis (women's) players, batch 7 (30 players, bringing the roster to 126
-- total: batches 1-6's 96 + batch 7's 30). Same upsert pattern as prior
-- batches: Players upserts on the unique Name constraint,
-- PlayerAttributeValues upserts on the existing unique (PlayerId,
-- AttributeDefinitionId) constraint, both scoped to the "tennis-women"
-- Sport. No overrides in this batch -- every row is IsOverridden = false,
-- DifficultyOverride = NULL.

INSERT INTO "Players" ("SportId", "Name", "IsOverridden", "DifficultyOverride")
SELECT s."Id", v."Name", v."IsOverridden", v."DifficultyOverride"
FROM "Sports" s
CROSS JOIN (VALUES
    ('Iva Jovic',                false, NULL),
    ('Victoria Mboko',           false, NULL),
    ('Sorana Cirstea',           false, NULL),
    ('Anna Kalinskaya',          false, NULL),
    ('Elise Mertens',            false, NULL),
    ('Maja Chwalinska',          false, NULL),
    ('Anastasia Potapova',       false, NULL),
    ('Marie Bouzkova',           false, NULL),
    ('Ann Li',                   false, NULL),
    ('Liudmila Samsonova',       false, NULL),
    ('Katerina Siniakova',       false, NULL),
    ('Peyton Stearns',           false, NULL),
    ('Camila Osorio',            false, NULL),
    ('McCartney Kessler',        false, NULL),
    ('Magdalena Frech',          false, NULL),
    ('Daria Kasatkina',          false, NULL),
    ('Donna Vekic',              false, NULL),
    ('Clara Tauson',             false, NULL),
    ('Elisabetta Cocciaretto',   false, NULL),
    ('Alycia Parks',             false, NULL),
    ('Diane Parry',              false, NULL),
    ('Caty McNally',             false, NULL),
    ('Wang Xinyu',               false, NULL),
    ('Cristina Bucsa',           false, NULL),
    ('Hailey Baptiste',          false, NULL),
    ('Ashlyn Krueger',           false, NULL),
    ('Renata Zarazua',           false, NULL),
    ('Talia Gibson',             false, NULL),
    ('Maya Joint',               false, NULL),
    ('Alina Korneeva',           false, NULL)
) AS v("Name", "IsOverridden", "DifficultyOverride")
WHERE s."Slug" = 'tennis-women'
ON CONFLICT ("Name") DO UPDATE SET
    "SportId" = EXCLUDED."SportId",
    "IsOverridden" = EXCLUDED."IsOverridden",
    "DifficultyOverride" = EXCLUDED."DifficultyOverride";

-- One row per (player, attribute) pair. PlayerId/AttributeDefinitionId are
-- resolved by name/key lookup (scoped to each player's own SportId), so
-- this file has no dependency on insertion order or id values, and can
-- never cross-attach to tennis-men's AttributeDefinitions.
INSERT INTO "PlayerAttributeValues" ("PlayerId", "AttributeDefinitionId", "Value")
SELECT p."Id", ad."Id", v."Value"
FROM (VALUES
    -- Player,                          AttrKey,                Value
    ('Iva Jovic',                       'active_status',        'Active'),
    ('Iva Jovic',                       'plays',                'Right'),
    ('Iva Jovic',                       'backhand',             'Two-Handed'),
    ('Iva Jovic',                       'country',              'USA'),
    ('Iva Jovic',                       'grand_slam_titles',    '0'),
    ('Iva Jovic',                       'career_high_ranking',  '16'),
    ('Iva Jovic',                       'turned_pro_year',      '2022'),
    ('Iva Jovic',                       'career_titles',        '1'),

    ('Victoria Mboko',                  'active_status',        'Active'),
    ('Victoria Mboko',                  'plays',                'Right'),
    ('Victoria Mboko',                  'backhand',             'Two-Handed'),
    ('Victoria Mboko',                  'country',              'Canada'),
    ('Victoria Mboko',                  'grand_slam_titles',    '0'),
    ('Victoria Mboko',                  'career_high_ranking',  '9'),
    ('Victoria Mboko',                  'turned_pro_year',      '2022'),
    ('Victoria Mboko',                  'career_titles',        '2'),

    ('Sorana Cirstea',                  'active_status',        'Active'),
    ('Sorana Cirstea',                  'plays',                'Right'),
    ('Sorana Cirstea',                  'backhand',             'Two-Handed'),
    ('Sorana Cirstea',                  'country',              'Romania'),
    ('Sorana Cirstea',                  'grand_slam_titles',    '0'),
    ('Sorana Cirstea',                  'career_high_ranking',  '18'),
    ('Sorana Cirstea',                  'turned_pro_year',      '2006'),
    ('Sorana Cirstea',                  'career_titles',        '4'),

    ('Anna Kalinskaya',                 'active_status',        'Active'),
    ('Anna Kalinskaya',                 'plays',                'Right'),
    ('Anna Kalinskaya',                 'backhand',             'Two-Handed'),
    ('Anna Kalinskaya',                 'country',              'Russia'),
    ('Anna Kalinskaya',                 'grand_slam_titles',    '0'),
    ('Anna Kalinskaya',                 'career_high_ranking',  '11'),
    ('Anna Kalinskaya',                 'turned_pro_year',      '2016'),
    ('Anna Kalinskaya',                 'career_titles',        '0'),

    ('Elise Mertens',                   'active_status',        'Active'),
    ('Elise Mertens',                   'plays',                'Right'),
    ('Elise Mertens',                   'backhand',             'Two-Handed'),
    ('Elise Mertens',                   'country',              'Belgium'),
    ('Elise Mertens',                   'grand_slam_titles',    '0'),
    ('Elise Mertens',                   'career_high_ranking',  '12'),
    ('Elise Mertens',                   'turned_pro_year',      '2013'),
    ('Elise Mertens',                   'career_titles',        '10'),

    ('Maja Chwalinska',                 'active_status',        'Active'),
    ('Maja Chwalinska',                 'plays',                'Left'),
    ('Maja Chwalinska',                 'backhand',             'Two-Handed'),
    ('Maja Chwalinska',                 'country',              'Poland'),
    ('Maja Chwalinska',                 'grand_slam_titles',    '0'),
    ('Maja Chwalinska',                 'career_high_ranking',  '113'),
    ('Maja Chwalinska',                 'turned_pro_year',      '2018'),
    ('Maja Chwalinska',                 'career_titles',        '0'),

    ('Anastasia Potapova',              'active_status',        'Active'),
    ('Anastasia Potapova',              'plays',                'Right'),
    ('Anastasia Potapova',              'backhand',             'Two-Handed'),
    ('Anastasia Potapova',              'country',              'Austria'),
    ('Anastasia Potapova',              'grand_slam_titles',    '0'),
    ('Anastasia Potapova',              'career_high_ranking',  '21'),
    ('Anastasia Potapova',              'turned_pro_year',      '2017'),
    ('Anastasia Potapova',              'career_titles',        '3'),

    ('Marie Bouzkova',                  'active_status',        'Active'),
    ('Marie Bouzkova',                  'plays',                'Right'),
    ('Marie Bouzkova',                  'backhand',             'Two-Handed'),
    ('Marie Bouzkova',                  'country',              'Czech Republic'),
    ('Marie Bouzkova',                  'grand_slam_titles',    '0'),
    ('Marie Bouzkova',                  'career_high_ranking',  '24'),
    ('Marie Bouzkova',                  'turned_pro_year',      '2013'),
    ('Marie Bouzkova',                  'career_titles',        '3'),

    ('Ann Li',                          'active_status',        'Active'),
    ('Ann Li',                          'plays',                'Right'),
    ('Ann Li',                          'backhand',             'Two-Handed'),
    ('Ann Li',                          'country',              'USA'),
    ('Ann Li',                          'grand_slam_titles',    '0'),
    ('Ann Li',                          'career_high_ranking',  '29'),
    ('Ann Li',                          'turned_pro_year',      '2017'),
    ('Ann Li',                          'career_titles',        '2'),

    ('Liudmila Samsonova',              'active_status',        'Active'),
    ('Liudmila Samsonova',              'plays',                'Right'),
    ('Liudmila Samsonova',              'backhand',             'Two-Handed'),
    ('Liudmila Samsonova',              'country',              'Russia'),
    ('Liudmila Samsonova',              'grand_slam_titles',    '0'),
    ('Liudmila Samsonova',              'career_high_ranking',  '12'),
    ('Liudmila Samsonova',              'turned_pro_year',      '2013'),
    ('Liudmila Samsonova',              'career_titles',        '5'),

    ('Katerina Siniakova',              'active_status',        'Active'),
    ('Katerina Siniakova',              'plays',                'Right'),
    ('Katerina Siniakova',              'backhand',             'Two-Handed'),
    ('Katerina Siniakova',              'country',              'Czech Republic'),
    ('Katerina Siniakova',              'grand_slam_titles',    '0'),
    ('Katerina Siniakova',              'career_high_ranking',  '27'),
    ('Katerina Siniakova',              'turned_pro_year',      '2012'),
    ('Katerina Siniakova',              'career_titles',        '5'),

    ('Peyton Stearns',                  'active_status',        'Active'),
    ('Peyton Stearns',                  'plays',                'Right'),
    ('Peyton Stearns',                  'backhand',             'Two-Handed'),
    ('Peyton Stearns',                  'country',              'USA'),
    ('Peyton Stearns',                  'grand_slam_titles',    '0'),
    ('Peyton Stearns',                  'career_high_ranking',  '28'),
    ('Peyton Stearns',                  'turned_pro_year',      '2022'),
    ('Peyton Stearns',                  'career_titles',        '2'),

    ('Camila Osorio',                   'active_status',        'Active'),
    ('Camila Osorio',                   'plays',                'Right'),
    ('Camila Osorio',                   'backhand',             'Two-Handed'),
    ('Camila Osorio',                   'country',              'Colombia'),
    ('Camila Osorio',                   'grand_slam_titles',    '0'),
    ('Camila Osorio',                   'career_high_ranking',  '33'),
    ('Camila Osorio',                   'turned_pro_year',      '2019'),
    ('Camila Osorio',                   'career_titles',        '3'),

    ('McCartney Kessler',               'active_status',        'Active'),
    ('McCartney Kessler',               'plays',                'Right'),
    ('McCartney Kessler',               'backhand',             'Two-Handed'),
    ('McCartney Kessler',               'country',              'USA'),
    ('McCartney Kessler',               'grand_slam_titles',    '0'),
    ('McCartney Kessler',               'career_high_ranking',  '30'),
    ('McCartney Kessler',               'turned_pro_year',      '2022'),
    ('McCartney Kessler',               'career_titles',        '3'),

    ('Magdalena Frech',                 'active_status',        'Active'),
    ('Magdalena Frech',                 'plays',                'Right'),
    ('Magdalena Frech',                 'backhand',             'Two-Handed'),
    ('Magdalena Frech',                 'country',              'Poland'),
    ('Magdalena Frech',                 'grand_slam_titles',    '0'),
    ('Magdalena Frech',                 'career_high_ranking',  '22'),
    ('Magdalena Frech',                 'turned_pro_year',      '2013'),
    ('Magdalena Frech',                 'career_titles',        '1'),

    ('Daria Kasatkina',                 'active_status',        'Active'),
    ('Daria Kasatkina',                 'plays',                'Right'),
    ('Daria Kasatkina',                 'backhand',             'Two-Handed'),
    ('Daria Kasatkina',                 'country',              'Australia'),
    ('Daria Kasatkina',                 'grand_slam_titles',    '0'),
    ('Daria Kasatkina',                 'career_high_ranking',  '8'),
    ('Daria Kasatkina',                 'turned_pro_year',      '2014'),
    ('Daria Kasatkina',                 'career_titles',        '8'),

    ('Donna Vekic',                     'active_status',        'Active'),
    ('Donna Vekic',                     'plays',                'Right'),
    ('Donna Vekic',                     'backhand',             'Two-Handed'),
    ('Donna Vekic',                     'country',              'Croatia'),
    ('Donna Vekic',                     'grand_slam_titles',    '0'),
    ('Donna Vekic',                     'career_high_ranking',  '17'),
    ('Donna Vekic',                     'turned_pro_year',      '2012'),
    ('Donna Vekic',                     'career_titles',        '5'),

    ('Clara Tauson',                    'active_status',        'Active'),
    ('Clara Tauson',                    'plays',                'Right'),
    ('Clara Tauson',                    'backhand',             'Two-Handed'),
    ('Clara Tauson',                    'country',              'Denmark'),
    ('Clara Tauson',                    'grand_slam_titles',    '0'),
    ('Clara Tauson',                    'career_high_ranking',  '12'),
    ('Clara Tauson',                    'turned_pro_year',      '2019'),
    ('Clara Tauson',                    'career_titles',        '3'),

    ('Elisabetta Cocciaretto',          'active_status',        'Active'),
    ('Elisabetta Cocciaretto',          'plays',                'Right'),
    ('Elisabetta Cocciaretto',          'backhand',             'Two-Handed'),
    ('Elisabetta Cocciaretto',          'country',              'Italy'),
    ('Elisabetta Cocciaretto',          'grand_slam_titles',    '0'),
    ('Elisabetta Cocciaretto',          'career_high_ranking',  '29'),
    ('Elisabetta Cocciaretto',          'turned_pro_year',      '2017'),
    ('Elisabetta Cocciaretto',          'career_titles',        '2'),

    ('Alycia Parks',                    'active_status',        'Active'),
    ('Alycia Parks',                    'plays',                'Right'),
    ('Alycia Parks',                    'backhand',             'Two-Handed'),
    ('Alycia Parks',                    'country',              'USA'),
    ('Alycia Parks',                    'grand_slam_titles',    '0'),
    ('Alycia Parks',                    'career_high_ranking',  '40'),
    ('Alycia Parks',                    'turned_pro_year',      '2018'),
    ('Alycia Parks',                    'career_titles',        '1'),

    ('Diane Parry',                     'active_status',        'Active'),
    ('Diane Parry',                     'plays',                'Right'),
    ('Diane Parry',                     'backhand',             'One-Handed'),
    ('Diane Parry',                     'country',              'France'),
    ('Diane Parry',                     'grand_slam_titles',    '0'),
    ('Diane Parry',                     'career_high_ranking',  '48'),
    ('Diane Parry',                     'turned_pro_year',      '2017'),
    ('Diane Parry',                     'career_titles',        '0'),

    ('Caty McNally',                    'active_status',        'Active'),
    ('Caty McNally',                    'plays',                'Right'),
    ('Caty McNally',                    'backhand',             'Two-Handed'),
    ('Caty McNally',                    'country',              'USA'),
    ('Caty McNally',                    'grand_slam_titles',    '0'),
    ('Caty McNally',                    'career_high_ranking',  '54'),
    ('Caty McNally',                    'turned_pro_year',      '2019'),
    ('Caty McNally',                    'career_titles',        '0'),

    ('Wang Xinyu',                      'active_status',        'Active'),
    ('Wang Xinyu',                      'plays',                'Right'),
    ('Wang Xinyu',                      'backhand',             'Two-Handed'),
    ('Wang Xinyu',                      'country',              'China'),
    ('Wang Xinyu',                      'grand_slam_titles',    '0'),
    ('Wang Xinyu',                      'career_high_ranking',  '30'),
    ('Wang Xinyu',                      'turned_pro_year',      '2018'),
    ('Wang Xinyu',                      'career_titles',        '0'),

    ('Cristina Bucsa',                  'active_status',        'Active'),
    ('Cristina Bucsa',                  'plays',                'Right'),
    ('Cristina Bucsa',                  'backhand',             'Two-Handed'),
    ('Cristina Bucsa',                  'country',              'Spain'),
    ('Cristina Bucsa',                  'grand_slam_titles',    '0'),
    ('Cristina Bucsa',                  'career_high_ranking',  '30'),
    ('Cristina Bucsa',                  'turned_pro_year',      '2016'),
    ('Cristina Bucsa',                  'career_titles',        '1'),

    ('Hailey Baptiste',                 'active_status',        'Active'),
    ('Hailey Baptiste',                 'plays',                'Right'),
    ('Hailey Baptiste',                 'backhand',             'Two-Handed'),
    ('Hailey Baptiste',                 'country',              'USA'),
    ('Hailey Baptiste',                 'grand_slam_titles',    '0'),
    ('Hailey Baptiste',                 'career_high_ranking',  '32'),
    ('Hailey Baptiste',                 'turned_pro_year',      '2019'),
    ('Hailey Baptiste',                 'career_titles',        '0'),

    ('Ashlyn Krueger',                  'active_status',        'Active'),
    ('Ashlyn Krueger',                  'plays',                'Right'),
    ('Ashlyn Krueger',                  'backhand',             'Two-Handed'),
    ('Ashlyn Krueger',                  'country',              'USA'),
    ('Ashlyn Krueger',                  'grand_slam_titles',    '0'),
    ('Ashlyn Krueger',                  'career_high_ranking',  '29'),
    ('Ashlyn Krueger',                  'turned_pro_year',      '2021'),
    ('Ashlyn Krueger',                  'career_titles',        '1'),

    ('Renata Zarazua',                  'active_status',        'Active'),
    ('Renata Zarazua',                  'plays',                'Right'),
    ('Renata Zarazua',                  'backhand',             'Two-Handed'),
    ('Renata Zarazua',                  'country',              'Mexico'),
    ('Renata Zarazua',                  'grand_slam_titles',    '0'),
    ('Renata Zarazua',                  'career_high_ranking',  '51'),
    ('Renata Zarazua',                  'turned_pro_year',      '2012'),
    ('Renata Zarazua',                  'career_titles',        '0'),

    ('Talia Gibson',                    'active_status',        'Active'),
    ('Talia Gibson',                    'plays',                'Right'),
    ('Talia Gibson',                    'backhand',             'Two-Handed'),
    ('Talia Gibson',                    'country',              'Australia'),
    ('Talia Gibson',                    'grand_slam_titles',    '0'),
    ('Talia Gibson',                    'career_high_ranking',  '55'),
    ('Talia Gibson',                    'turned_pro_year',      '2019'),
    ('Talia Gibson',                    'career_titles',        '0'),

    ('Maya Joint',                      'active_status',        'Active'),
    ('Maya Joint',                      'plays',                'Right'),
    ('Maya Joint',                      'backhand',             'Two-Handed'),
    ('Maya Joint',                      'country',              'Australia'),
    ('Maya Joint',                      'grand_slam_titles',    '0'),
    ('Maya Joint',                      'career_high_ranking',  '28'),
    ('Maya Joint',                      'turned_pro_year',      '2024'),
    ('Maya Joint',                      'career_titles',        '2'),

    ('Alina Korneeva',                  'active_status',        'Active'),
    ('Alina Korneeva',                  'plays',                'Right'),
    ('Alina Korneeva',                  'backhand',             'Two-Handed'),
    ('Alina Korneeva',                  'country',              'Russia'),
    ('Alina Korneeva',                  'grand_slam_titles',    '0'),
    ('Alina Korneeva',                  'career_high_ranking',  '117'),
    ('Alina Korneeva',                  'turned_pro_year',      '2023'),
    ('Alina Korneeva',                  'career_titles',        '0')
) AS v("PlayerName", "AttrKey", "Value")
JOIN "Players" p ON p."Name" = v."PlayerName"
JOIN "AttributeDefinitions" ad ON ad."Key" = v."AttrKey" AND ad."SportId" = p."SportId"
ON CONFLICT ("PlayerId", "AttributeDefinitionId") DO UPDATE SET
    "Value" = EXCLUDED."Value";
