-- Women's International Cricket players, batch 3 (30 players). Same
-- upsert pattern as batches 1-2: Players upserts on the unique Name
-- constraint, PlayerAttributeValues upserts on the existing unique
-- (PlayerId, AttributeDefinitionId) constraint, both scoped to the
-- "cricket-women-international" Sport. No overrides in this batch --
-- every row is IsOverridden = false, DifficultyOverride = NULL.

INSERT INTO "Players" ("SportId", "Name", "IsOverridden", "DifficultyOverride")
SELECT s."Id", v."Name", v."IsOverridden", v."DifficultyOverride"
FROM "Sports" s
CROSS JOIN (VALUES
    ('Yastika Bhatia',            false, NULL),
    ('Pooja Vastrakar',           false, NULL),
    ('Sneh Rana',                 false, NULL),
    ('Shreyanka Patil',           false, NULL),
    ('Phoebe Litchfield',         false, NULL),
    ('Alana King',                false, NULL),
    ('Darcie Brown',              false, NULL),
    ('Kim Garth',                 false, NULL),
    ('Lauren Bell',               false, NULL),
    ('Charlie Dean',              false, NULL),
    ('Emma Lamb',                 false, NULL),
    ('Freya Kemp',                false, NULL),
    ('Shemaine Campbelle',        false, NULL),
    ('Afy Fletcher',              false, NULL),
    ('Amy Satterthwaite',         false, NULL),
    ('Jess Kerr',                 false, NULL),
    ('Brooke Halliday',           false, NULL),
    ('Chloe Tryon',               false, NULL),
    ('Suné Luus',                 false, NULL),
    ('Nonkululeko Mlaba',         false, NULL),
    ('Anneke Bosch',              false, NULL),
    ('Sidra Ameen',               false, NULL),
    ('Nida Dar',                  false, NULL),
    ('Muneeba Ali',               false, NULL),
    ('Achini Kulasuriya',         false, NULL),
    ('Nilakshi de Silva',         false, NULL),
    ('Fahima Khatun',             false, NULL),
    ('Sharmin Akhter',            false, NULL),
    ('Josephine Nkomo',           false, NULL),
    ('Rashada Williams',          false, NULL)
) AS v("Name", "IsOverridden", "DifficultyOverride")
WHERE s."Slug" = 'cricket-women-international'
ON CONFLICT ("Name") DO UPDATE SET
    "SportId" = EXCLUDED."SportId",
    "IsOverridden" = EXCLUDED."IsOverridden",
    "DifficultyOverride" = EXCLUDED."DifficultyOverride";

-- One row per (player, attribute) pair. PlayerId/AttributeDefinitionId are
-- resolved by name/key lookup (scoped to each player's own SportId), so
-- this file has no dependency on insertion order or id values, and can
-- never cross-attach to cricket-men-international's AttributeDefinitions.
INSERT INTO "PlayerAttributeValues" ("PlayerId", "AttributeDefinitionId", "Value")
SELECT p."Id", ad."Id", v."Value"
FROM (VALUES
    -- Player,                          AttrKey,               Value
    ('Yastika Bhatia',                  'active_status',       'Active'),
    ('Yastika Bhatia',                  'country',              'India'),
    ('Yastika Bhatia',                  'batting_hand',         'Left'),
    ('Yastika Bhatia',                  'bowling_style',        'Hasn''t Bowled'),
    ('Yastika Bhatia',                  'role',                 'Wicketkeeper-Batter'),
    ('Yastika Bhatia',                  'combined_matches',     '94'),
    ('Yastika Bhatia',                  'combined_runs',        '1900'),
    ('Yastika Bhatia',                  'combined_wickets',     '0'),
    ('Yastika Bhatia',                  'debut_year',           '2021'),

    ('Pooja Vastrakar',                 'active_status',       'Active'),
    ('Pooja Vastrakar',                 'country',              'India'),
    ('Pooja Vastrakar',                 'batting_hand',         'Right'),
    ('Pooja Vastrakar',                 'bowling_style',        'Right-arm Pace'),
    ('Pooja Vastrakar',                 'role',                 'All-rounder'),
    ('Pooja Vastrakar',                 'combined_matches',     '97'),
    ('Pooja Vastrakar',                 'combined_runs',        '700'),
    ('Pooja Vastrakar',                 'combined_wickets',     '85'),
    ('Pooja Vastrakar',                 'debut_year',           '2018'),

    ('Sneh Rana',                       'active_status',       'Active'),
    ('Sneh Rana',                       'country',              'India'),
    ('Sneh Rana',                       'batting_hand',         'Right'),
    ('Sneh Rana',                       'bowling_style',        'Right-arm Spin'),
    ('Sneh Rana',                       'role',                 'Bowling All-rounder'),
    ('Sneh Rana',                       'combined_matches',     '159'),
    ('Sneh Rana',                       'combined_runs',        '1800'),
    ('Sneh Rana',                       'combined_wickets',     '165'),
    ('Sneh Rana',                       'debut_year',           '2014'),

    ('Shreyanka Patil',                 'active_status',       'Active'),
    ('Shreyanka Patil',                 'country',              'India'),
    ('Shreyanka Patil',                 'batting_hand',         'Right'),
    ('Shreyanka Patil',                 'bowling_style',        'Right-arm Spin'),
    ('Shreyanka Patil',                 'role',                 'Bowler'),
    ('Shreyanka Patil',                 'combined_matches',     '23'),
    ('Shreyanka Patil',                 'combined_runs',        '150'),
    ('Shreyanka Patil',                 'combined_wickets',     '30'),
    ('Shreyanka Patil',                 'debut_year',           '2023'),

    ('Phoebe Litchfield',               'active_status',       'Active'),
    ('Phoebe Litchfield',               'country',              'Australia'),
    ('Phoebe Litchfield',               'batting_hand',         'Left'),
    ('Phoebe Litchfield',               'bowling_style',        'Hasn''t Bowled'),
    ('Phoebe Litchfield',               'role',                 'Batter'),
    ('Phoebe Litchfield',               'combined_matches',     '76'),
    ('Phoebe Litchfield',               'combined_runs',        '2354'),
    ('Phoebe Litchfield',               'combined_wickets',     '0'),
    ('Phoebe Litchfield',               'debut_year',           '2022'),

    ('Alana King',                      'active_status',       'Active'),
    ('Alana King',                      'country',              'Australia'),
    ('Alana King',                      'batting_hand',         'Right'),
    ('Alana King',                      'bowling_style',        'Right-arm Spin'),
    ('Alana King',                      'role',                 'Bowling All-rounder'),
    ('Alana King',                      'combined_matches',     '72'),
    ('Alana King',                      'combined_runs',        '349'),
    ('Alana King',                      'combined_wickets',     '112'),
    ('Alana King',                      'debut_year',           '2022'),

    ('Darcie Brown',                    'active_status',       'Active'),
    ('Darcie Brown',                    'country',              'Australia'),
    ('Darcie Brown',                    'batting_hand',         'Right'),
    ('Darcie Brown',                    'bowling_style',        'Right-arm Pace'),
    ('Darcie Brown',                    'role',                 'Bowler'),
    ('Darcie Brown',                    'combined_matches',     '108'),
    ('Darcie Brown',                    'combined_runs',        '450'),
    ('Darcie Brown',                    'combined_wickets',     '130'),
    ('Darcie Brown',                    'debut_year',           '2021'),

    ('Kim Garth',                       'active_status',       'Active'),
    ('Kim Garth',                       'country',              'Australia'),
    ('Kim Garth',                       'batting_hand',         'Right'),
    ('Kim Garth',                       'bowling_style',        'Right-arm Pace'),
    ('Kim Garth',                       'role',                 'All-rounder'),
    ('Kim Garth',                       'combined_matches',     '112'),
    ('Kim Garth',                       'combined_runs',        '1760'),
    ('Kim Garth',                       'combined_wickets',     '95'),
    ('Kim Garth',                       'debut_year',           '2010'),

    ('Lauren Bell',                     'active_status',       'Active'),
    ('Lauren Bell',                     'country',              'England'),
    ('Lauren Bell',                     'batting_hand',         'Right'),
    ('Lauren Bell',                     'bowling_style',        'Right-arm Pace'),
    ('Lauren Bell',                     'role',                 'Bowler'),
    ('Lauren Bell',                     'combined_matches',     '90'),
    ('Lauren Bell',                     'combined_runs',        '225'),
    ('Lauren Bell',                     'combined_wickets',     '105'),
    ('Lauren Bell',                     'debut_year',           '2022'),

    ('Charlie Dean',                    'active_status',       'Active'),
    ('Charlie Dean',                    'country',              'England'),
    ('Charlie Dean',                    'batting_hand',         'Right'),
    ('Charlie Dean',                    'bowling_style',        'Right-arm Spin'),
    ('Charlie Dean',                    'role',                 'Bowling All-rounder'),
    ('Charlie Dean',                    'combined_matches',     '106'),
    ('Charlie Dean',                    'combined_runs',        '450'),
    ('Charlie Dean',                    'combined_wickets',     '142'),
    ('Charlie Dean',                    'debut_year',           '2021'),

    ('Emma Lamb',                       'active_status',       'Active'),
    ('Emma Lamb',                       'country',              'England'),
    ('Emma Lamb',                       'batting_hand',         'Right'),
    ('Emma Lamb',                       'bowling_style',        'Right-arm Spin'),
    ('Emma Lamb',                       'role',                 'Batting All-rounder'),
    ('Emma Lamb',                       'combined_matches',     '33'),
    ('Emma Lamb',                       'combined_runs',        '1400'),
    ('Emma Lamb',                       'combined_wickets',     '12'),
    ('Emma Lamb',                       'debut_year',           '2021'),

    ('Freya Kemp',                      'active_status',       'Active'),
    ('Freya Kemp',                      'country',              'England'),
    ('Freya Kemp',                      'batting_hand',         'Left'),
    ('Freya Kemp',                      'bowling_style',        'Left-arm Pace'),
    ('Freya Kemp',                      'role',                 'All-rounder'),
    ('Freya Kemp',                      'combined_matches',     '30'),
    ('Freya Kemp',                      'combined_runs',        '217'),
    ('Freya Kemp',                      'combined_wickets',     '22'),
    ('Freya Kemp',                      'debut_year',           '2022'),

    ('Shemaine Campbelle',              'active_status',       'Active'),
    ('Shemaine Campbelle',              'country',              'West Indies'),
    ('Shemaine Campbelle',              'batting_hand',         'Right'),
    ('Shemaine Campbelle',              'bowling_style',        'Right-arm Pace'),
    ('Shemaine Campbelle',              'role',                 'All-rounder'),
    ('Shemaine Campbelle',              'combined_matches',     '227'),
    ('Shemaine Campbelle',              'combined_runs',        '2455'),
    ('Shemaine Campbelle',              'combined_wickets',     '50'),
    ('Shemaine Campbelle',              'debut_year',           '2009'),

    ('Afy Fletcher',                    'active_status',       'Active'),
    ('Afy Fletcher',                    'country',              'West Indies'),
    ('Afy Fletcher',                    'batting_hand',         'Right'),
    ('Afy Fletcher',                    'bowling_style',        'Right-arm Spin'),
    ('Afy Fletcher',                    'role',                 'Bowler'),
    ('Afy Fletcher',                    'combined_matches',     '182'),
    ('Afy Fletcher',                    'combined_runs',        '550'),
    ('Afy Fletcher',                    'combined_wickets',     '171'),
    ('Afy Fletcher',                    'debut_year',           '2008'),

    ('Amy Satterthwaite',               'active_status',       'Retired'),
    ('Amy Satterthwaite',               'country',              'New Zealand'),
    ('Amy Satterthwaite',               'batting_hand',         'Left'),
    ('Amy Satterthwaite',               'bowling_style',        'Right-arm Pace'),
    ('Amy Satterthwaite',               'role',                 'All-rounder'),
    ('Amy Satterthwaite',               'combined_matches',     '256'),
    ('Amy Satterthwaite',               'combined_runs',        '6500'),
    ('Amy Satterthwaite',               'combined_wickets',     '120'),
    ('Amy Satterthwaite',               'debut_year',           '2007'),

    ('Jess Kerr',                       'active_status',       'Active'),
    ('Jess Kerr',                       'country',              'New Zealand'),
    ('Jess Kerr',                       'batting_hand',         'Right'),
    ('Jess Kerr',                       'bowling_style',        'Right-arm Pace'),
    ('Jess Kerr',                       'role',                 'Bowler'),
    ('Jess Kerr',                       'combined_matches',     '105'),
    ('Jess Kerr',                       'combined_runs',        '450'),
    ('Jess Kerr',                       'combined_wickets',     '102'),
    ('Jess Kerr',                       'debut_year',           '2020'),

    ('Brooke Halliday',                 'active_status',       'Active'),
    ('Brooke Halliday',                 'country',              'New Zealand'),
    ('Brooke Halliday',                 'batting_hand',         'Left'),
    ('Brooke Halliday',                 'bowling_style',        'Right-arm Pace'),
    ('Brooke Halliday',                 'role',                 'All-rounder'),
    ('Brooke Halliday',                 'combined_matches',     '120'),
    ('Brooke Halliday',                 'combined_runs',        '3800'),
    ('Brooke Halliday',                 'combined_wickets',     '18'),
    ('Brooke Halliday',                 'debut_year',           '2021'),

    ('Chloe Tryon',                     'active_status',       'Active'),
    ('Chloe Tryon',                     'country',              'South Africa'),
    ('Chloe Tryon',                     'batting_hand',         'Right'),
    ('Chloe Tryon',                     'bowling_style',        'Left-arm Spin'),
    ('Chloe Tryon',                     'role',                 'All-rounder'),
    ('Chloe Tryon',                     'combined_matches',     '204'),
    ('Chloe Tryon',                     'combined_runs',        '3742'),
    ('Chloe Tryon',                     'combined_wickets',     '132'),
    ('Chloe Tryon',                     'debut_year',           '2010'),

    ('Suné Luus',                       'active_status',       'Active'),
    ('Suné Luus',                       'country',              'South Africa'),
    ('Suné Luus',                       'batting_hand',         'Right'),
    ('Suné Luus',                       'bowling_style',        'Right-arm Spin'),
    ('Suné Luus',                       'role',                 'Bowling All-rounder'),
    ('Suné Luus',                       'combined_matches',     '187'),
    ('Suné Luus',                       'combined_runs',        '1800'),
    ('Suné Luus',                       'combined_wickets',     '173'),
    ('Suné Luus',                       'debut_year',           '2012'),

    ('Nonkululeko Mlaba',                'active_status',       'Active'),
    ('Nonkululeko Mlaba',                'country',              'South Africa'),
    ('Nonkululeko Mlaba',                'batting_hand',         'Right'),
    ('Nonkululeko Mlaba',                'bowling_style',        'Left-arm Spin'),
    ('Nonkululeko Mlaba',                'role',                 'Bowler'),
    ('Nonkululeko Mlaba',                'combined_matches',     '103'),
    ('Nonkululeko Mlaba',                'combined_runs',        '280'),
    ('Nonkululeko Mlaba',                'combined_wickets',     '129'),
    ('Nonkululeko Mlaba',                'debut_year',           '2019'),

    ('Anneke Bosch',                    'active_status',       'Active'),
    ('Anneke Bosch',                    'country',              'South Africa'),
    ('Anneke Bosch',                    'batting_hand',         'Right'),
    ('Anneke Bosch',                    'bowling_style',        'Right-arm Pace'),
    ('Anneke Bosch',                    'role',                 'All-rounder'),
    ('Anneke Bosch',                    'combined_matches',     '108'),
    ('Anneke Bosch',                    'combined_runs',        '2200'),
    ('Anneke Bosch',                    'combined_wickets',     '65'),
    ('Anneke Bosch',                    'debut_year',           '2016'),

    ('Sidra Ameen',                     'active_status',       'Active'),
    ('Sidra Ameen',                     'country',              'Pakistan'),
    ('Sidra Ameen',                     'batting_hand',         'Right'),
    ('Sidra Ameen',                     'bowling_style',        'Right-arm Pace'),
    ('Sidra Ameen',                     'role',                 'Batter'),
    ('Sidra Ameen',                     'combined_matches',     '95'),
    ('Sidra Ameen',                     'combined_runs',        '1978'),
    ('Sidra Ameen',                     'combined_wickets',     '0'),
    ('Sidra Ameen',                     'debut_year',           '2011'),

    ('Nida Dar',                        'active_status',       'Active'),
    ('Nida Dar',                        'country',              'Pakistan'),
    ('Nida Dar',                        'batting_hand',         'Right'),
    ('Nida Dar',                        'bowling_style',        'Right-arm Spin'),
    ('Nida Dar',                        'role',                 'All-rounder'),
    ('Nida Dar',                        'combined_matches',     '285'),
    ('Nida Dar',                        'combined_runs',        '4200'),
    ('Nida Dar',                        'combined_wickets',     '245'),
    ('Nida Dar',                        'debut_year',           '2010'),

    ('Muneeba Ali',                     'active_status',       'Active'),
    ('Muneeba Ali',                     'country',              'Pakistan'),
    ('Muneeba Ali',                     'batting_hand',         'Left'),
    ('Muneeba Ali',                     'bowling_style',        'Hasn''t Bowled'),
    ('Muneeba Ali',                     'role',                 'Wicketkeeper-Batter'),
    ('Muneeba Ali',                     'combined_matches',     '140'),
    ('Muneeba Ali',                     'combined_runs',        '2800'),
    ('Muneeba Ali',                     'combined_wickets',     '0'),
    ('Muneeba Ali',                     'debut_year',           '2016'),

    ('Achini Kulasuriya',               'active_status',       'Active'),
    ('Achini Kulasuriya',               'country',              'Sri Lanka'),
    ('Achini Kulasuriya',               'batting_hand',         'Left'),
    ('Achini Kulasuriya',               'bowling_style',        'Right-arm Pace'),
    ('Achini Kulasuriya',               'role',                 'Bowler'),
    ('Achini Kulasuriya',               'combined_matches',     '42'),
    ('Achini Kulasuriya',               'combined_runs',        '52'),
    ('Achini Kulasuriya',               'combined_wickets',     '16'),
    ('Achini Kulasuriya',               'debut_year',           '2015'),

    ('Nilakshi de Silva',                'active_status',       'Retired'),
    ('Nilakshi de Silva',                'country',              'Sri Lanka'),
    ('Nilakshi de Silva',                'batting_hand',         'Right'),
    ('Nilakshi de Silva',                'bowling_style',        'Right-arm Pace'),
    ('Nilakshi de Silva',                'role',                 'All-rounder'),
    ('Nilakshi de Silva',                'combined_matches',     '107'),
    ('Nilakshi de Silva',                'combined_runs',        '1374'),
    ('Nilakshi de Silva',                'combined_wickets',     '42'),
    ('Nilakshi de Silva',                'debut_year',           '2013'),

    ('Fahima Khatun',                   'active_status',       'Active'),
    ('Fahima Khatun',                   'country',              'Bangladesh'),
    ('Fahima Khatun',                   'batting_hand',         'Right'),
    ('Fahima Khatun',                   'bowling_style',        'Right-arm Spin'),
    ('Fahima Khatun',                   'role',                 'Bowler'),
    ('Fahima Khatun',                   'combined_matches',     '148'),
    ('Fahima Khatun',                   'combined_runs',        '765'),
    ('Fahima Khatun',                   'combined_wickets',     '89'),
    ('Fahima Khatun',                   'debut_year',           '2013'),

    ('Sharmin Akhter',                  'active_status',       'Active'),
    ('Sharmin Akhter',                  'country',              'Bangladesh'),
    ('Sharmin Akhter',                  'batting_hand',         'Right'),
    ('Sharmin Akhter',                  'bowling_style',        'Hasn''t Bowled'),
    ('Sharmin Akhter',                  'role',                 'Batter'),
    ('Sharmin Akhter',                  'combined_matches',     '110'),
    ('Sharmin Akhter',                  'combined_runs',        '1800'),
    ('Sharmin Akhter',                  'combined_wickets',     '0'),
    ('Sharmin Akhter',                  'debut_year',           '2011'),

    ('Josephine Nkomo',                 'active_status',       'Active'),
    ('Josephine Nkomo',                 'country',              'Zimbabwe'),
    ('Josephine Nkomo',                 'batting_hand',         'Right'),
    ('Josephine Nkomo',                 'bowling_style',        'Right-arm Pace'),
    ('Josephine Nkomo',                 'role',                 'Bowler'),
    ('Josephine Nkomo',                 'combined_matches',     '95'),
    ('Josephine Nkomo',                 'combined_runs',        '550'),
    ('Josephine Nkomo',                 'combined_wickets',     '120'),
    ('Josephine Nkomo',                 'debut_year',           '2019'),

    ('Rashada Williams',                'active_status',       'Active'),
    ('Rashada Williams',                'country',              'West Indies'),
    ('Rashada Williams',                'batting_hand',         'Right'),
    ('Rashada Williams',                'bowling_style',        'Hasn''t Bowled'),
    ('Rashada Williams',                'role',                 'Wicketkeeper-Batter'),
    ('Rashada Williams',                'combined_matches',     '63'),
    ('Rashada Williams',                'combined_runs',        '864'),
    ('Rashada Williams',                'combined_wickets',     '0'),
    ('Rashada Williams',                'debut_year',           '2021')
) AS v("PlayerName", "AttrKey", "Value")
JOIN "Players" p ON p."Name" = v."PlayerName"
JOIN "AttributeDefinitions" ad ON ad."Key" = v."AttrKey" AND ad."SportId" = p."SportId"
ON CONFLICT ("PlayerId", "AttributeDefinitionId") DO UPDATE SET
    "Value" = EXCLUDED."Value"
WHERE "PlayerAttributeValues"."IsManuallyEdited" = false;
