-- Women's International Cricket players, batch 4 (30 players, bringing the
-- roster to 120 total: batches 1-3's 90 + batch 4's 30). Same upsert
-- pattern as prior batches: Players upserts on the unique Name constraint,
-- PlayerAttributeValues upserts on the existing unique (PlayerId,
-- AttributeDefinitionId) constraint, both scoped to the
-- "cricket-women-international" Sport. No overrides in this batch -- every
-- row is IsOverridden = false, DifficultyOverride = NULL.

INSERT INTO "Players" ("SportId", "Name", "IsOverridden", "DifficultyOverride")
SELECT s."Id", v."Name", v."IsOverridden", v."DifficultyOverride"
FROM "Sports" s
CROSS JOIN (VALUES
    ('Priya Punia',               false, NULL),
    ('Diana Edulji',              false, NULL),
    ('Anjum Chopra',              false, NULL),
    ('Grace Harris',              false, NULL),
    ('Ellyse Villani',            false, NULL),
    ('Georgia Wareham',           false, NULL),
    ('Sophie Molineux',           false, NULL),
    ('Bess Heath',                false, NULL),
    ('Issy Wong',                 false, NULL),
    ('Maia Bouchier',             false, NULL),
    ('Danielle Gibson',           false, NULL),
    ('Anya Shrubsole',            false, NULL),
    ('Qiana Joseph',              false, NULL),
    ('Anisa Mohammed',            false, NULL),
    ('Zaida James',               false, NULL),
    ('Eden Carson',               false, NULL),
    ('Fran Jonas',                false, NULL),
    ('Isabella Gaze',             false, NULL),
    ('Tazmin Brits',              false, NULL),
    ('Lizelle Lee',               false, NULL),
    ('Sadia Iqbal',               false, NULL),
    ('Natalia Pervaiz',           false, NULL),
    ('Diana Baig',                false, NULL),
    ('Udeshika Prabodhani',       false, NULL),
    ('Inoka Ranaweera',           false, NULL),
    ('Sobhana Mostary',           false, NULL),
    ('Murshida Khatun',           false, NULL),
    ('Marufa Akter',              false, NULL),
    ('Orla Prendergast',          false, NULL),
    ('Amy Hunter',                false, NULL)
) AS v("Name", "IsOverridden", "DifficultyOverride")
WHERE s."Slug" = 'cricket-women-international'
ON CONFLICT ("Name") DO UPDATE SET
    "SportId" = EXCLUDED."SportId",
    "IsOverridden" = EXCLUDED."IsOverridden",
    "DifficultyOverride" = EXCLUDED."DifficultyOverride";

-- One row per (player, attribute) pair. PlayerId/AttributeDefinitionId are
-- resolved by name/key lookup (scoped to each player's own SportId), so
-- this file has no dependency on insertion order or id values, and can
-- never cross-attach to cricket-men-international's AttributeDefinitions.
INSERT INTO "PlayerAttributeValues" ("PlayerId", "AttributeDefinitionId", "Value")
SELECT p."Id", ad."Id", v."Value"
FROM (VALUES
    -- Player,                          AttrKey,               Value
    ('Priya Punia',                     'active_status',       'Active'),
    ('Priya Punia',                     'country',              'India'),
    ('Priya Punia',                     'batting_hand',         'Right'),
    ('Priya Punia',                     'bowling_style',        'Right-arm Pace'),
    ('Priya Punia',                     'role',                 'Batter'),
    ('Priya Punia',                     'combined_matches',     '37'),
    ('Priya Punia',                     'combined_runs',        '900'),
    ('Priya Punia',                     'combined_wickets',     '0'),
    ('Priya Punia',                     'debut_year',           '2019'),

    ('Diana Edulji',                    'active_status',       'Retired'),
    ('Diana Edulji',                    'country',              'India'),
    ('Diana Edulji',                    'batting_hand',         'Right'),
    ('Diana Edulji',                    'bowling_style',        'Left-arm Spin'),
    ('Diana Edulji',                    'role',                 'All-rounder'),
    ('Diana Edulji',                    'combined_matches',     '54'),
    ('Diana Edulji',                    'combined_runs',        '700'),
    ('Diana Edulji',                    'combined_wickets',     '120'),
    ('Diana Edulji',                    'debut_year',           '1976'),

    ('Anjum Chopra',                    'active_status',       'Retired'),
    ('Anjum Chopra',                    'country',              'India'),
    ('Anjum Chopra',                    'batting_hand',         'Left'),
    ('Anjum Chopra',                    'bowling_style',        'Right-arm Pace'),
    ('Anjum Chopra',                    'role',                 'Batter'),
    ('Anjum Chopra',                    'combined_matches',     '156'),
    ('Anjum Chopra',                    'combined_runs',        '4200'),
    ('Anjum Chopra',                    'combined_wickets',     '18'),
    ('Anjum Chopra',                    'debut_year',           '1995'),

    ('Grace Harris',                    'active_status',       'Active'),
    ('Grace Harris',                    'country',              'Australia'),
    ('Grace Harris',                    'batting_hand',         'Right'),
    ('Grace Harris',                    'bowling_style',        'Right-arm Spin'),
    ('Grace Harris',                    'role',                 'All-rounder'),
    ('Grace Harris',                    'combined_matches',     '110'),
    ('Grace Harris',                    'combined_runs',        '1978'),
    ('Grace Harris',                    'combined_wickets',     '34'),
    ('Grace Harris',                    'debut_year',           '2015'),

    ('Ellyse Villani',                  'active_status',       'Retired'),
    ('Ellyse Villani',                  'country',              'Australia'),
    ('Ellyse Villani',                  'batting_hand',         'Right'),
    ('Ellyse Villani',                  'bowling_style',        'Right-arm Pace'),
    ('Ellyse Villani',                  'role',                 'Batter'),
    ('Ellyse Villani',                  'combined_matches',     '124'),
    ('Ellyse Villani',                  'combined_runs',        '2675'),
    ('Ellyse Villani',                  'combined_wickets',     '17'),
    ('Ellyse Villani',                  'debut_year',           '2009'),

    ('Georgia Wareham',                 'active_status',       'Active'),
    ('Georgia Wareham',                 'country',              'Australia'),
    ('Georgia Wareham',                 'batting_hand',         'Right'),
    ('Georgia Wareham',                 'bowling_style',        'Right-arm Spin'),
    ('Georgia Wareham',                 'role',                 'Bowler'),
    ('Georgia Wareham',                 'combined_matches',     '131'),
    ('Georgia Wareham',                 'combined_runs',        '950'),
    ('Georgia Wareham',                 'combined_wickets',     '125'),
    ('Georgia Wareham',                 'debut_year',           '2018'),

    ('Sophie Molineux',                 'active_status',       'Active'),
    ('Sophie Molineux',                 'country',              'Australia'),
    ('Sophie Molineux',                 'batting_hand',         'Left'),
    ('Sophie Molineux',                 'bowling_style',        'Left-arm Spin'),
    ('Sophie Molineux',                 'role',                 'Bowler'),
    ('Sophie Molineux',                 'combined_matches',     '128'),
    ('Sophie Molineux',                 'combined_runs',        '1200'),
    ('Sophie Molineux',                 'combined_wickets',     '155'),
    ('Sophie Molineux',                 'debut_year',           '2018'),

    ('Bess Heath',                      'active_status',       'Active'),
    ('Bess Heath',                      'country',              'England'),
    ('Bess Heath',                      'batting_hand',         'Right'),
    ('Bess Heath',                      'bowling_style',        'Hasn''t Bowled'),
    ('Bess Heath',                      'role',                 'Wicketkeeper-Batter'),
    ('Bess Heath',                      'combined_matches',     '25'),
    ('Bess Heath',                      'combined_runs',        '450'),
    ('Bess Heath',                      'combined_wickets',     '0'),
    ('Bess Heath',                      'debut_year',           '2023'),

    ('Issy Wong',                       'active_status',       'Active'),
    ('Issy Wong',                       'country',              'England'),
    ('Issy Wong',                       'batting_hand',         'Right'),
    ('Issy Wong',                       'bowling_style',        'Right-arm Pace'),
    ('Issy Wong',                       'role',                 'Bowler'),
    ('Issy Wong',                       'combined_matches',     '23'),
    ('Issy Wong',                       'combined_runs',        '65'),
    ('Issy Wong',                       'combined_wickets',     '20'),
    ('Issy Wong',                       'debut_year',           '2022'),

    ('Maia Bouchier',                   'active_status',       'Active'),
    ('Maia Bouchier',                   'country',              'England'),
    ('Maia Bouchier',                   'batting_hand',         'Right'),
    ('Maia Bouchier',                   'bowling_style',        'Right-arm Pace'),
    ('Maia Bouchier',                   'role',                 'Batter'),
    ('Maia Bouchier',                   'combined_matches',     '50'),
    ('Maia Bouchier',                   'combined_runs',        '1500'),
    ('Maia Bouchier',                   'combined_wickets',     '2'),
    ('Maia Bouchier',                   'debut_year',           '2021'),

    ('Danielle Gibson',                 'active_status',       'Active'),
    ('Danielle Gibson',                 'country',              'England'),
    ('Danielle Gibson',                 'batting_hand',         'Right'),
    ('Danielle Gibson',                 'bowling_style',        'Right-arm Pace'),
    ('Danielle Gibson',                 'role',                 'All-rounder'),
    ('Danielle Gibson',                 'combined_matches',     '32'),
    ('Danielle Gibson',                 'combined_runs',        '550'),
    ('Danielle Gibson',                 'combined_wickets',     '52'),
    ('Danielle Gibson',                 'debut_year',           '2023'),

    ('Anya Shrubsole',                  'active_status',       'Retired'),
    ('Anya Shrubsole',                  'country',              'England'),
    ('Anya Shrubsole',                  'batting_hand',         'Right'),
    ('Anya Shrubsole',                  'bowling_style',        'Right-arm Pace'),
    ('Anya Shrubsole',                  'role',                 'Bowler'),
    ('Anya Shrubsole',                  'combined_matches',     '173'),
    ('Anya Shrubsole',                  'combined_runs',        '1100'),
    ('Anya Shrubsole',                  'combined_wickets',     '227'),
    ('Anya Shrubsole',                  'debut_year',           '2008'),

    ('Qiana Joseph',                    'active_status',       'Active'),
    ('Qiana Joseph',                    'country',              'West Indies'),
    ('Qiana Joseph',                    'batting_hand',         'Left'),
    ('Qiana Joseph',                    'bowling_style',        'Left-arm Spin'),
    ('Qiana Joseph',                    'role',                 'Bowler'),
    ('Qiana Joseph',                    'combined_matches',     '40'),
    ('Qiana Joseph',                    'combined_runs',        '450'),
    ('Qiana Joseph',                    'combined_wickets',     '15'),
    ('Qiana Joseph',                    'debut_year',           '2017'),

    ('Anisa Mohammed',                  'active_status',       'Retired'),
    ('Anisa Mohammed',                  'country',              'West Indies'),
    ('Anisa Mohammed',                  'batting_hand',         'Right'),
    ('Anisa Mohammed',                  'bowling_style',        'Right-arm Spin'),
    ('Anisa Mohammed',                  'role',                 'Bowler'),
    ('Anisa Mohammed',                  'combined_matches',     '233'),
    ('Anisa Mohammed',                  'combined_runs',        '900'),
    ('Anisa Mohammed',                  'combined_wickets',     '266'),
    ('Anisa Mohammed',                  'debut_year',           '2003'),

    ('Zaida James',                     'active_status',       'Active'),
    ('Zaida James',                     'country',              'West Indies'),
    ('Zaida James',                     'batting_hand',         'Left'),
    ('Zaida James',                     'bowling_style',        'Left-arm Spin'),
    ('Zaida James',                     'role',                 'All-rounder'),
    ('Zaida James',                     'combined_matches',     '60'),
    ('Zaida James',                     'combined_runs',        '350'),
    ('Zaida James',                     'combined_wickets',     '22'),
    ('Zaida James',                     'debut_year',           '2023'),

    ('Eden Carson',                     'active_status',       'Active'),
    ('Eden Carson',                     'country',              'New Zealand'),
    ('Eden Carson',                     'batting_hand',         'Right'),
    ('Eden Carson',                     'bowling_style',        'Right-arm Spin'),
    ('Eden Carson',                     'role',                 'Bowler'),
    ('Eden Carson',                     'combined_matches',     '85'),
    ('Eden Carson',                     'combined_runs',        '550'),
    ('Eden Carson',                     'combined_wickets',     '105'),
    ('Eden Carson',                     'debut_year',           '2022'),

    ('Fran Jonas',                      'active_status',       'Active'),
    ('Fran Jonas',                      'country',              'New Zealand'),
    ('Fran Jonas',                      'batting_hand',         'Right'),
    ('Fran Jonas',                      'bowling_style',        'Left-arm Spin'),
    ('Fran Jonas',                      'role',                 'Bowler'),
    ('Fran Jonas',                      'combined_matches',     '55'),
    ('Fran Jonas',                      'combined_runs',        '175'),
    ('Fran Jonas',                      'combined_wickets',     '60'),
    ('Fran Jonas',                      'debut_year',           '2021'),

    ('Isabella Gaze',                   'active_status',       'Active'),
    ('Isabella Gaze',                   'country',              'New Zealand'),
    ('Isabella Gaze',                   'batting_hand',         'Right'),
    ('Isabella Gaze',                   'bowling_style',        'Hasn''t Bowled'),
    ('Isabella Gaze',                   'role',                 'Wicketkeeper-Batter'),
    ('Isabella Gaze',                   'combined_matches',     '50'),
    ('Isabella Gaze',                   'combined_runs',        '650'),
    ('Isabella Gaze',                   'combined_wickets',     '0'),
    ('Isabella Gaze',                   'debut_year',           '2022'),

    ('Tazmin Brits',                    'active_status',       'Active'),
    ('Tazmin Brits',                    'country',              'South Africa'),
    ('Tazmin Brits',                    'batting_hand',         'Right'),
    ('Tazmin Brits',                    'bowling_style',        'Hasn''t Bowled'),
    ('Tazmin Brits',                    'role',                 'Batter'),
    ('Tazmin Brits',                    'combined_matches',     '101'),
    ('Tazmin Brits',                    'combined_runs',        '3400'),
    ('Tazmin Brits',                    'combined_wickets',     '0'),
    ('Tazmin Brits',                    'debut_year',           '2018'),

    ('Lizelle Lee',                     'active_status',       'Retired'),
    ('Lizelle Lee',                     'country',              'South Africa'),
    ('Lizelle Lee',                     'batting_hand',         'Right'),
    ('Lizelle Lee',                     'bowling_style',        'Right-arm Pace'),
    ('Lizelle Lee',                     'role',                 'Wicketkeeper-Batter'),
    ('Lizelle Lee',                     'combined_matches',     '178'),
    ('Lizelle Lee',                     'combined_runs',        '5500'),
    ('Lizelle Lee',                     'combined_wickets',     '4'),
    ('Lizelle Lee',                     'debut_year',           '2013'),

    ('Sadia Iqbal',                     'active_status',       'Active'),
    ('Sadia Iqbal',                     'country',              'Pakistan'),
    ('Sadia Iqbal',                     'batting_hand',         'Left'),
    ('Sadia Iqbal',                     'bowling_style',        'Left-arm Spin'),
    ('Sadia Iqbal',                     'role',                 'Bowler'),
    ('Sadia Iqbal',                     'combined_matches',     '145'),
    ('Sadia Iqbal',                     'combined_runs',        '350'),
    ('Sadia Iqbal',                     'combined_wickets',     '175'),
    ('Sadia Iqbal',                     'debut_year',           '2019'),

    ('Natalia Pervaiz',                 'active_status',       'Active'),
    ('Natalia Pervaiz',                 'country',              'Pakistan'),
    ('Natalia Pervaiz',                 'batting_hand',         'Right'),
    ('Natalia Pervaiz',                 'bowling_style',        'Right-arm Pace'),
    ('Natalia Pervaiz',                 'role',                 'All-rounder'),
    ('Natalia Pervaiz',                 'combined_matches',     '155'),
    ('Natalia Pervaiz',                 'combined_runs',        '2200'),
    ('Natalia Pervaiz',                 'combined_wickets',     '140'),
    ('Natalia Pervaiz',                 'debut_year',           '2017'),

    ('Diana Baig',                      'active_status',       'Active'),
    ('Diana Baig',                      'country',              'Pakistan'),
    ('Diana Baig',                      'batting_hand',         'Right'),
    ('Diana Baig',                      'bowling_style',        'Right-arm Pace'),
    ('Diana Baig',                      'role',                 'Bowler'),
    ('Diana Baig',                      'combined_matches',     '145'),
    ('Diana Baig',                      'combined_runs',        '450'),
    ('Diana Baig',                      'combined_wickets',     '140'),
    ('Diana Baig',                      'debut_year',           '2015'),

    ('Udeshika Prabodhani',             'active_status',       'Active'),
    ('Udeshika Prabodhani',             'country',              'Sri Lanka'),
    ('Udeshika Prabodhani',             'batting_hand',         'Right'),
    ('Udeshika Prabodhani',             'bowling_style',        'Left-arm Pace'),
    ('Udeshika Prabodhani',             'role',                 'Bowler'),
    ('Udeshika Prabodhani',             'combined_matches',     '120'),
    ('Udeshika Prabodhani',             'combined_runs',        '250'),
    ('Udeshika Prabodhani',             'combined_wickets',     '66'),
    ('Udeshika Prabodhani',             'debut_year',           '2009'),

    ('Inoka Ranaweera',                 'active_status',       'Active'),
    ('Inoka Ranaweera',                 'country',              'Sri Lanka'),
    ('Inoka Ranaweera',                 'batting_hand',         'Right'),
    ('Inoka Ranaweera',                 'bowling_style',        'Left-arm Spin'),
    ('Inoka Ranaweera',                 'role',                 'Bowler'),
    ('Inoka Ranaweera',                 'combined_matches',     '195'),
    ('Inoka Ranaweera',                 'combined_runs',        '800'),
    ('Inoka Ranaweera',                 'combined_wickets',     '165'),
    ('Inoka Ranaweera',                 'debut_year',           '2003'),

    ('Sobhana Mostary',                 'active_status',       'Active'),
    ('Sobhana Mostary',                 'country',              'Bangladesh'),
    ('Sobhana Mostary',                 'batting_hand',         'Right'),
    ('Sobhana Mostary',                 'bowling_style',        'Right-arm Pace'),
    ('Sobhana Mostary',                 'role',                 'All-rounder'),
    ('Sobhana Mostary',                 'combined_matches',     '100'),
    ('Sobhana Mostary',                 'combined_runs',        '900'),
    ('Sobhana Mostary',                 'combined_wickets',     '40'),
    ('Sobhana Mostary',                 'debut_year',           '2013'),

    ('Murshida Khatun',                 'active_status',       'Active'),
    ('Murshida Khatun',                 'country',              'Bangladesh'),
    ('Murshida Khatun',                 'batting_hand',         'Left'),
    ('Murshida Khatun',                 'bowling_style',        'Hasn''t Bowled'),
    ('Murshida Khatun',                 'role',                 'Batter'),
    ('Murshida Khatun',                 'combined_matches',     '85'),
    ('Murshida Khatun',                 'combined_runs',        '1600'),
    ('Murshida Khatun',                 'combined_wickets',     '0'),
    ('Murshida Khatun',                 'debut_year',           '2018'),

    ('Marufa Akter',                    'active_status',       'Active'),
    ('Marufa Akter',                    'country',              'Bangladesh'),
    ('Marufa Akter',                    'batting_hand',         'Right'),
    ('Marufa Akter',                    'bowling_style',        'Right-arm Pace'),
    ('Marufa Akter',                    'role',                 'Bowler'),
    ('Marufa Akter',                    'combined_matches',     '80'),
    ('Marufa Akter',                    'combined_runs',        '150'),
    ('Marufa Akter',                    'combined_wickets',     '75'),
    ('Marufa Akter',                    'debut_year',           '2021'),

    ('Orla Prendergast',                'active_status',       'Active'),
    ('Orla Prendergast',                'country',              'Ireland'),
    ('Orla Prendergast',                'batting_hand',         'Right'),
    ('Orla Prendergast',                'bowling_style',        'Right-arm Pace'),
    ('Orla Prendergast',                'role',                 'All-rounder'),
    ('Orla Prendergast',                'combined_matches',     '110'),
    ('Orla Prendergast',                'combined_runs',        '2400'),
    ('Orla Prendergast',                'combined_wickets',     '75'),
    ('Orla Prendergast',                'debut_year',           '2018'),

    ('Amy Hunter',                      'active_status',       'Active'),
    ('Amy Hunter',                      'country',              'Ireland'),
    ('Amy Hunter',                      'batting_hand',         'Right'),
    ('Amy Hunter',                      'bowling_style',        'Hasn''t Bowled'),
    ('Amy Hunter',                      'role',                 'Wicketkeeper-Batter'),
    ('Amy Hunter',                      'combined_matches',     '100'),
    ('Amy Hunter',                      'combined_runs',        '2000'),
    ('Amy Hunter',                      'combined_wickets',     '0'),
    ('Amy Hunter',                      'debut_year',           '2020')
) AS v("PlayerName", "AttrKey", "Value")
JOIN "Players" p ON p."Name" = v."PlayerName"
JOIN "AttributeDefinitions" ad ON ad."Key" = v."AttrKey" AND ad."SportId" = p."SportId"
ON CONFLICT ("PlayerId", "AttributeDefinitionId") DO UPDATE SET
    "Value" = EXCLUDED."Value"
WHERE "PlayerAttributeValues"."IsManuallyEdited" = false;
