-- Women's International Cricket players, batch 1 (30 players). Same
-- upsert pattern as the Men's Cricket batch file: Players upserts on the
-- unique Name constraint, PlayerAttributeValues upserts on the existing
-- unique (PlayerId, AttributeDefinitionId) constraint, both scoped to the
-- "cricket-women-international" Sport. No overrides in this batch -- every
-- row is IsOverridden = false, DifficultyOverride = NULL.

INSERT INTO "Players" ("SportId", "Name", "IsOverridden", "DifficultyOverride")
SELECT s."Id", v."Name", v."IsOverridden", v."DifficultyOverride"
FROM "Sports" s
CROSS JOIN (VALUES
    ('Mithali Raj',              false, NULL),
    ('Jhulan Goswami',           false, NULL),
    ('Harmanpreet Kaur',         false, NULL),
    ('Smriti Mandhana',          false, NULL),
    ('Ellyse Perry',             false, NULL),
    ('Meg Lanning',              false, NULL),
    ('Alyssa Healy',             false, NULL),
    ('Cathryn Fitzpatrick',      false, NULL),
    ('Charlotte Edwards',        false, NULL),
    ('Claire Taylor',            false, NULL),
    ('Katherine Sciver-Brunt',   false, NULL),
    ('Heather Knight',           false, NULL),
    ('Stafanie Taylor',          false, NULL),
    ('Deandra Dottin',           false, NULL),
    ('Suzie Bates',              false, NULL),
    ('Sophie Devine',            false, NULL),
    ('Dane van Niekerk',         false, NULL),
    ('Marizanne Kapp',           false, NULL),
    ('Sana Mir',                 false, NULL),
    ('Chamari Athapaththu',      false, NULL),
    ('Nigar Sultana',            false, NULL),
    ('Laura Delany',             false, NULL),
    ('Kathryn Bryce',            false, NULL),
    ('Belinda Clark',            false, NULL),
    ('Rachael Heyhoe Flint',     false, NULL),
    ('Shabnim Ismail',           false, NULL),
    ('Shafali Verma',            false, NULL),
    ('Amelia Kerr',              false, NULL),
    ('Lisa Sthalekar',           false, NULL),
    ('Nat Sciver-Brunt',         false, NULL)
) AS v("Name", "IsOverridden", "DifficultyOverride")
WHERE s."Slug" = 'cricket-women-international'
ON CONFLICT ("Name") DO UPDATE SET
    "SportId" = EXCLUDED."SportId",
    "IsOverridden" = CASE WHEN "Players"."IsOverridden" THEN "Players"."IsOverridden" ELSE EXCLUDED."IsOverridden" END,
    "DifficultyOverride" = CASE WHEN "Players"."IsOverridden" THEN "Players"."DifficultyOverride" ELSE EXCLUDED."DifficultyOverride" END;

-- One row per (player, attribute) pair. PlayerId/AttributeDefinitionId are
-- resolved by name/key lookup (scoped to each player's own SportId), so
-- this file has no dependency on insertion order or id values, and can
-- never cross-attach to cricket-men-international's AttributeDefinitions.
INSERT INTO "PlayerAttributeValues" ("PlayerId", "AttributeDefinitionId", "Value")
SELECT p."Id", ad."Id", v."Value"
FROM (VALUES
    -- Player,                       AttrKey,               Value
    ('Mithali Raj',                  'active_status',       'Retired'),
    ('Mithali Raj',                  'country',              'India'),
    ('Mithali Raj',                  'batting_hand',         'Right'),
    ('Mithali Raj',                  'bowling_style',        'Right-arm Spin'),
    ('Mithali Raj',                  'role',                 'Batter'),
    ('Mithali Raj',                  'combined_matches',     '333'),
    ('Mithali Raj',                  'combined_runs',        '10868'),
    ('Mithali Raj',                  'combined_wickets',     '8'),
    ('Mithali Raj',                  'debut_year',           '1999'),

    ('Jhulan Goswami',               'active_status',       'Retired'),
    ('Jhulan Goswami',               'country',              'India'),
    ('Jhulan Goswami',               'batting_hand',         'Right'),
    ('Jhulan Goswami',               'bowling_style',        'Right-arm Pace'),
    ('Jhulan Goswami',               'role',                 'Bowler'),
    ('Jhulan Goswami',               'combined_matches',     '284'),
    ('Jhulan Goswami',               'combined_runs',        '1924'),
    ('Jhulan Goswami',               'combined_wickets',     '355'),
    ('Jhulan Goswami',               'debut_year',           '2002'),

    ('Harmanpreet Kaur',              'active_status',       'Active'),
    ('Harmanpreet Kaur',              'country',              'India'),
    ('Harmanpreet Kaur',              'batting_hand',         'Right'),
    ('Harmanpreet Kaur',              'bowling_style',        'Right-arm Spin'),
    ('Harmanpreet Kaur',              'role',                 'All-rounder'),
    ('Harmanpreet Kaur',              'combined_matches',     '374'),
    ('Harmanpreet Kaur',              'combined_runs',        '9061'),
    ('Harmanpreet Kaur',              'combined_wickets',     '75'),
    ('Harmanpreet Kaur',              'debut_year',           '2009'),

    ('Smriti Mandhana',               'active_status',       'Active'),
    ('Smriti Mandhana',               'country',              'India'),
    ('Smriti Mandhana',               'batting_hand',         'Left'),
    ('Smriti Mandhana',               'bowling_style',        'Right-arm Pace'),
    ('Smriti Mandhana',               'role',                 'Batter'),
    ('Smriti Mandhana',               'combined_matches',     '300'),
    ('Smriti Mandhana',               'combined_runs',        '10737'),
    ('Smriti Mandhana',               'combined_wickets',     '1'),
    ('Smriti Mandhana',               'debut_year',           '2013'),

    ('Ellyse Perry',                  'active_status',       'Active'),
    ('Ellyse Perry',                  'country',              'Australia'),
    ('Ellyse Perry',                  'batting_hand',         'Right'),
    ('Ellyse Perry',                  'bowling_style',        'Right-arm Pace'),
    ('Ellyse Perry',                  'role',                 'All-rounder'),
    ('Ellyse Perry',                  'combined_matches',     '351'),
    ('Ellyse Perry',                  'combined_runs',        '7711'),
    ('Ellyse Perry',                  'combined_wickets',     '331'),
    ('Ellyse Perry',                  'debut_year',           '2007'),

    ('Meg Lanning',                   'active_status',       'Retired'),
    ('Meg Lanning',                   'country',              'Australia'),
    ('Meg Lanning',                   'batting_hand',         'Right'),
    ('Meg Lanning',                   'bowling_style',        'Right-arm Pace'),
    ('Meg Lanning',                   'role',                 'Batter'),
    ('Meg Lanning',                   'combined_matches',     '241'),
    ('Meg Lanning',                   'combined_runs',        '8352'),
    ('Meg Lanning',                   'combined_wickets',     '5'),
    ('Meg Lanning',                   'debut_year',           '2010'),

    ('Alyssa Healy',                  'active_status',       'Active'),
    ('Alyssa Healy',                  'country',              'Australia'),
    ('Alyssa Healy',                  'batting_hand',         'Right'),
    ('Alyssa Healy',                  'bowling_style',        'Hasn''t Bowled'),
    ('Alyssa Healy',                  'role',                 'Wicketkeeper-Batter'),
    ('Alyssa Healy',                  'combined_matches',     '251'),
    ('Alyssa Healy',                  'combined_runs',        '5693'),
    ('Alyssa Healy',                  'combined_wickets',     '0'),
    ('Alyssa Healy',                  'debut_year',           '2010'),

    ('Cathryn Fitzpatrick',           'active_status',       'Retired'),
    ('Cathryn Fitzpatrick',           'country',              'Australia'),
    ('Cathryn Fitzpatrick',           'batting_hand',         'Right'),
    ('Cathryn Fitzpatrick',           'bowling_style',        'Right-arm Pace'),
    ('Cathryn Fitzpatrick',           'role',                 'Bowler'),
    ('Cathryn Fitzpatrick',           'combined_matches',     '122'),
    ('Cathryn Fitzpatrick',           'combined_runs',        '803'),
    ('Cathryn Fitzpatrick',           'combined_wickets',     '240'),
    ('Cathryn Fitzpatrick',           'debut_year',           '1991'),

    ('Charlotte Edwards',             'active_status',       'Retired'),
    ('Charlotte Edwards',             'country',              'England'),
    ('Charlotte Edwards',             'batting_hand',         'Right'),
    ('Charlotte Edwards',             'bowling_style',        'Right-arm Spin'),
    ('Charlotte Edwards',             'role',                 'Batter'),
    ('Charlotte Edwards',             'combined_matches',     '309'),
    ('Charlotte Edwards',             'combined_runs',        '10273'),
    ('Charlotte Edwards',             'combined_wickets',     '75'),
    ('Charlotte Edwards',             'debut_year',           '1996'),

    ('Claire Taylor',                 'active_status',       'Retired'),
    ('Claire Taylor',                 'country',              'England'),
    ('Claire Taylor',                 'batting_hand',         'Right'),
    ('Claire Taylor',                 'bowling_style',        'Hasn''t Bowled'),
    ('Claire Taylor',                 'role',                 'Batter'),
    ('Claire Taylor',                 'combined_matches',     '168'),
    ('Claire Taylor',                 'combined_runs',        '5746'),
    ('Claire Taylor',                 'combined_wickets',     '0'),
    ('Claire Taylor',                 'debut_year',           '1998'),

    ('Katherine Sciver-Brunt',        'active_status',       'Retired'),
    ('Katherine Sciver-Brunt',        'country',              'England'),
    ('Katherine Sciver-Brunt',        'batting_hand',         'Right'),
    ('Katherine Sciver-Brunt',        'bowling_style',        'Right-arm Pace'),
    ('Katherine Sciver-Brunt',        'role',                 'Bowling All-rounder'),
    ('Katherine Sciver-Brunt',        'combined_matches',     '267'),
    ('Katherine Sciver-Brunt',        'combined_runs',        '1864'),
    ('Katherine Sciver-Brunt',        'combined_wickets',     '335'),
    ('Katherine Sciver-Brunt',        'debut_year',           '2004'),

    ('Heather Knight',                'active_status',       'Active'),
    ('Heather Knight',                'country',              'England'),
    ('Heather Knight',                'batting_hand',         'Right'),
    ('Heather Knight',                'bowling_style',        'Right-arm Spin'),
    ('Heather Knight',                'role',                 'Batter'),
    ('Heather Knight',                'combined_matches',     '251'),
    ('Heather Knight',                'combined_runs',        '6351'),
    ('Heather Knight',                'combined_wickets',     '84'),
    ('Heather Knight',                'debut_year',           '2010'),

    ('Stafanie Taylor',               'active_status',       'Active'),
    ('Stafanie Taylor',               'country',              'West Indies'),
    ('Stafanie Taylor',               'batting_hand',         'Right'),
    ('Stafanie Taylor',               'bowling_style',        'Right-arm Spin'),
    ('Stafanie Taylor',               'role',                 'All-rounder'),
    ('Stafanie Taylor',               'combined_matches',     '285'),
    ('Stafanie Taylor',               'combined_runs',        '9117'),
    ('Stafanie Taylor',               'combined_wickets',     '253'),
    ('Stafanie Taylor',               'debut_year',           '2008'),

    ('Deandra Dottin',                'active_status',       'Active'),
    ('Deandra Dottin',                'country',              'West Indies'),
    ('Deandra Dottin',                'batting_hand',         'Right'),
    ('Deandra Dottin',                'bowling_style',        'Right-arm Pace'),
    ('Deandra Dottin',                'role',                 'All-rounder'),
    ('Deandra Dottin',                'combined_matches',     '312'),
    ('Deandra Dottin',                'combined_runs',        '7122'),
    ('Deandra Dottin',                'combined_wickets',     '161'),
    ('Deandra Dottin',                'debut_year',           '2008'),

    ('Suzie Bates',                   'active_status',       'Retired'),
    ('Suzie Bates',                   'country',              'New Zealand'),
    ('Suzie Bates',                   'batting_hand',         'Right'),
    ('Suzie Bates',                   'bowling_style',        'Right-arm Pace'),
    ('Suzie Bates',                   'role',                 'All-rounder'),
    ('Suzie Bates',                   'combined_matches',     '362'),
    ('Suzie Bates',                   'combined_runs',        '10681'),
    ('Suzie Bates',                   'combined_wickets',     '145'),
    ('Suzie Bates',                   'debut_year',           '2006'),

    ('Sophie Devine',                 'active_status',       'Active'),
    ('Sophie Devine',                 'country',              'New Zealand'),
    ('Sophie Devine',                 'batting_hand',         'Right'),
    ('Sophie Devine',                 'bowling_style',        'Right-arm Pace'),
    ('Sophie Devine',                 'role',                 'Batting All-rounder'),
    ('Sophie Devine',                 'combined_matches',     '259'),
    ('Sophie Devine',                 'combined_runs',        '6544'),
    ('Sophie Devine',                 'combined_wickets',     '202'),
    ('Sophie Devine',                 'debut_year',           '2006'),

    ('Dane van Niekerk',               'active_status',       'Active'),
    ('Dane van Niekerk',               'country',              'South Africa'),
    ('Dane van Niekerk',               'batting_hand',         'Right'),
    ('Dane van Niekerk',               'bowling_style',        'Right-arm Spin'),
    ('Dane van Niekerk',               'role',                 'All-rounder'),
    ('Dane van Niekerk',               'combined_matches',     '194'),
    ('Dane van Niekerk',               'combined_runs',        '4074'),
    ('Dane van Niekerk',               'combined_wickets',     '203'),
    ('Dane van Niekerk',               'debut_year',           '2009'),

    ('Marizanne Kapp',                'active_status',       'Active'),
    ('Marizanne Kapp',                'country',              'South Africa'),
    ('Marizanne Kapp',                'batting_hand',         'Right'),
    ('Marizanne Kapp',                'bowling_style',        'Right-arm Pace'),
    ('Marizanne Kapp',                'role',                 'All-rounder'),
    ('Marizanne Kapp',                'combined_matches',     '263'),
    ('Marizanne Kapp',                'combined_runs',        '5997'),
    ('Marizanne Kapp',                'combined_wickets',     '274'),
    ('Marizanne Kapp',                'debut_year',           '2009'),

    ('Sana Mir',                      'active_status',       'Retired'),
    ('Sana Mir',                      'country',              'Pakistan'),
    ('Sana Mir',                      'batting_hand',         'Right'),
    ('Sana Mir',                      'bowling_style',        'Right-arm Spin'),
    ('Sana Mir',                      'role',                 'All-rounder'),
    ('Sana Mir',                      'combined_matches',     '227'),
    ('Sana Mir',                      'combined_runs',        '2450'),
    ('Sana Mir',                      'combined_wickets',     '239'),
    ('Sana Mir',                      'debut_year',           '2005'),

    ('Chamari Athapaththu',           'active_status',       'Active'),
    ('Chamari Athapaththu',           'country',              'Sri Lanka'),
    ('Chamari Athapaththu',           'batting_hand',         'Left'),
    ('Chamari Athapaththu',           'bowling_style',        'Right-arm Spin'),
    ('Chamari Athapaththu',           'role',                 'Batting All-rounder'),
    ('Chamari Athapaththu',           'combined_matches',     '287'),
    ('Chamari Athapaththu',           'combined_runs',        '8045'),
    ('Chamari Athapaththu',           'combined_wickets',     '130'),
    ('Chamari Athapaththu',           'debut_year',           '2009'),

    ('Nigar Sultana',                 'active_status',       'Active'),
    ('Nigar Sultana',                 'country',              'Bangladesh'),
    ('Nigar Sultana',                 'batting_hand',         'Right'),
    ('Nigar Sultana',                 'bowling_style',        'Hasn''t Bowled'),
    ('Nigar Sultana',                 'role',                 'Wicketkeeper-Batter'),
    ('Nigar Sultana',                 'combined_matches',     '138'),
    ('Nigar Sultana',                 'combined_runs',        '2570'),
    ('Nigar Sultana',                 'combined_wickets',     '0'),
    ('Nigar Sultana',                 'debut_year',           '2015'),

    ('Laura Delany',                  'active_status',       'Active'),
    ('Laura Delany',                  'country',              'Ireland'),
    ('Laura Delany',                  'batting_hand',         'Right'),
    ('Laura Delany',                  'bowling_style',        'Right-arm Pace'),
    ('Laura Delany',                  'role',                 'All-rounder'),
    ('Laura Delany',                  'combined_matches',     '149'),
    ('Laura Delany',                  'combined_runs',        '2060'),
    ('Laura Delany',                  'combined_wickets',     '87'),
    ('Laura Delany',                  'debut_year',           '2010'),

    ('Kathryn Bryce',                 'active_status',       'Active'),
    ('Kathryn Bryce',                 'country',              'Scotland'),
    ('Kathryn Bryce',                 'batting_hand',         'Right'),
    ('Kathryn Bryce',                 'bowling_style',        'Right-arm Pace'),
    ('Kathryn Bryce',                 'role',                 'All-rounder'),
    ('Kathryn Bryce',                 'combined_matches',     '59'),
    ('Kathryn Bryce',                 'combined_runs',        '1867'),
    ('Kathryn Bryce',                 'combined_wickets',     '59'),
    ('Kathryn Bryce',                 'debut_year',           '2018'),

    ('Belinda Clark',                 'active_status',       'Retired'),
    ('Belinda Clark',                 'country',              'Australia'),
    ('Belinda Clark',                 'batting_hand',         'Right'),
    ('Belinda Clark',                 'bowling_style',        'Right-arm Spin'),
    ('Belinda Clark',                 'role',                 'Batter'),
    ('Belinda Clark',                 'combined_matches',     '134'),
    ('Belinda Clark',                 'combined_runs',        '5775'),
    ('Belinda Clark',                 'combined_wickets',     '4'),
    ('Belinda Clark',                 'debut_year',           '1991'),

    ('Rachael Heyhoe Flint',          'active_status',       'Retired'),
    ('Rachael Heyhoe Flint',          'country',              'England'),
    ('Rachael Heyhoe Flint',          'batting_hand',         'Right'),
    ('Rachael Heyhoe Flint',          'bowling_style',        'Right-arm Spin'),
    ('Rachael Heyhoe Flint',          'role',                 'Batter'),
    ('Rachael Heyhoe Flint',          'combined_matches',     '45'),
    ('Rachael Heyhoe Flint',          'combined_runs',        '2237'),
    ('Rachael Heyhoe Flint',          'combined_wickets',     '4'),
    ('Rachael Heyhoe Flint',          'debut_year',           '1960'),

    ('Shabnim Ismail',                'active_status',       'Active'),
    ('Shabnim Ismail',                'country',              'South Africa'),
    ('Shabnim Ismail',                'batting_hand',         'Left'),
    ('Shabnim Ismail',                'bowling_style',        'Right-arm Pace'),
    ('Shabnim Ismail',                'role',                 'Bowler'),
    ('Shabnim Ismail',                'combined_matches',     '241'),
    ('Shabnim Ismail',                'combined_runs',        '664'),
    ('Shabnim Ismail',                'combined_wickets',     '317'),
    ('Shabnim Ismail',                'debut_year',           '2007'),

    ('Shafali Verma',                 'active_status',       'Active'),
    ('Shafali Verma',                 'country',              'India'),
    ('Shafali Verma',                 'batting_hand',         'Right'),
    ('Shafali Verma',                 'bowling_style',        'Right-arm Spin'),
    ('Shafali Verma',                 'role',                 'Batter'),
    ('Shafali Verma',                 'combined_matches',     '121'),
    ('Shafali Verma',                 'combined_runs',        '3353'),
    ('Shafali Verma',                 'combined_wickets',     '14'),
    ('Shafali Verma',                 'debut_year',           '2019'),

    ('Amelia Kerr',                   'active_status',       'Active'),
    ('Amelia Kerr',                   'country',              'New Zealand'),
    ('Amelia Kerr',                   'batting_hand',         'Right'),
    ('Amelia Kerr',                   'bowling_style',        'Right-arm Spin'),
    ('Amelia Kerr',                   'role',                 'All-rounder'),
    ('Amelia Kerr',                   'combined_matches',     '186'),
    ('Amelia Kerr',                   'combined_runs',        '4571'),
    ('Amelia Kerr',                   'combined_wickets',     '230'),
    ('Amelia Kerr',                   'debut_year',           '2016'),

    ('Lisa Sthalekar',                'active_status',       'Retired'),
    ('Lisa Sthalekar',                'country',              'Australia'),
    ('Lisa Sthalekar',                'batting_hand',         'Right'),
    ('Lisa Sthalekar',                'bowling_style',        'Right-arm Spin'),
    ('Lisa Sthalekar',                'role',                 'All-rounder'),
    ('Lisa Sthalekar',                'combined_matches',     '187'),
    ('Lisa Sthalekar',                'combined_runs',        '3913'),
    ('Lisa Sthalekar',                'combined_wickets',     '229'),
    ('Lisa Sthalekar',                'debut_year',           '2001'),

    ('Nat Sciver-Brunt',               'active_status',       'Active'),
    ('Nat Sciver-Brunt',               'country',              'England'),
    ('Nat Sciver-Brunt',               'batting_hand',         'Right'),
    ('Nat Sciver-Brunt',               'bowling_style',        'Right-arm Pace'),
    ('Nat Sciver-Brunt',               'role',                 'All-rounder'),
    ('Nat Sciver-Brunt',               'combined_matches',     '278'),
    ('Nat Sciver-Brunt',               'combined_runs',        '8197'),
    ('Nat Sciver-Brunt',               'combined_wickets',     '190'),
    ('Nat Sciver-Brunt',               'debut_year',           '2013')
) AS v("PlayerName", "AttrKey", "Value")
JOIN "Players" p ON p."Name" = v."PlayerName"
JOIN "AttributeDefinitions" ad ON ad."Key" = v."AttrKey" AND ad."SportId" = p."SportId"
ON CONFLICT ("PlayerId", "AttributeDefinitionId") DO UPDATE SET
    "Value" = EXCLUDED."Value"
WHERE "PlayerAttributeValues"."IsManuallyEdited" = false;
