-- Women's International Cricket players, batch 2 (30 players). Same
-- upsert pattern as batch 1: Players upserts on the unique Name
-- constraint, PlayerAttributeValues upserts on the existing unique
-- (PlayerId, AttributeDefinitionId) constraint, both scoped to the
-- "cricket-women-international" Sport. No overrides in this batch --
-- every row is IsOverridden = false, DifficultyOverride = NULL.

INSERT INTO "Players" ("SportId", "Name", "IsOverridden", "DifficultyOverride")
SELECT s."Id", v."Name", v."IsOverridden", v."DifficultyOverride"
FROM "Sports" s
CROSS JOIN (VALUES
    ('Deepti Sharma',             false, NULL),
    ('Jemimah Rodrigues',         false, NULL),
    ('Richa Ghosh',               false, NULL),
    ('Renuka Singh Thakur',       false, NULL),
    ('Radha Yadav',               false, NULL),
    ('Tahlia McGrath',            false, NULL),
    ('Ashleigh Gardner',          false, NULL),
    ('Beth Mooney',               false, NULL),
    ('Megan Schutt',              false, NULL),
    ('Annabel Sutherland',        false, NULL),
    ('Sophie Ecclestone',         false, NULL),
    ('Tammy Beaumont',            false, NULL),
    ('Alice Capsey',              false, NULL),
    ('Danni Wyatt',               false, NULL),
    ('Sophia Dunkley',            false, NULL),
    ('Hayley Matthews',           false, NULL),
    ('Chinelle Henry',            false, NULL),
    ('Lea Tahuhu',                false, NULL),
    ('Maddy Green',               false, NULL),
    ('Georgia Plimmer',           false, NULL),
    ('Laura Wolvaardt',           false, NULL),
    ('Nadine de Klerk',           false, NULL),
    ('Ayabonga Khaka',            false, NULL),
    ('Aliya Riaz',                false, NULL),
    ('Fatima Sana',               false, NULL),
    ('Harshitha Samarawickrama',  false, NULL),
    ('Kavisha Dilhari',           false, NULL),
    ('Rumana Ahmed',              false, NULL),
    ('Gaby Lewis',                false, NULL),
    ('Sarah Bryce',               false, NULL)
) AS v("Name", "IsOverridden", "DifficultyOverride")
WHERE s."Slug" = 'cricket-women-international'
ON CONFLICT ("Name") DO UPDATE SET
    "SportId" = EXCLUDED."SportId",
    "IsOverridden" = EXCLUDED."IsOverridden",
    "DifficultyOverride" = EXCLUDED."DifficultyOverride";

-- One row per (player, attribute) pair. PlayerId/AttributeDefinitionId are
-- resolved by name/key lookup (scoped to each player's own SportId), so
-- this file has no dependency on insertion order or id values, and can
-- never cross-attach to cricket-men-international's AttributeDefinitions.
INSERT INTO "PlayerAttributeValues" ("PlayerId", "AttributeDefinitionId", "Value")
SELECT p."Id", ad."Id", v."Value"
FROM (VALUES
    -- Player,                          AttrKey,               Value
    ('Deepti Sharma',                   'active_status',       'Active'),
    ('Deepti Sharma',                   'country',              'India'),
    ('Deepti Sharma',                   'batting_hand',         'Left'),
    ('Deepti Sharma',                   'bowling_style',        'Right-arm Spin'),
    ('Deepti Sharma',                   'role',                 'All-rounder'),
    ('Deepti Sharma',                   'combined_matches',     '218'),
    ('Deepti Sharma',                   'combined_runs',        '3500'),
    ('Deepti Sharma',                   'combined_wickets',     '230'),
    ('Deepti Sharma',                   'debut_year',           '2014'),

    ('Jemimah Rodrigues',               'active_status',       'Active'),
    ('Jemimah Rodrigues',               'country',              'India'),
    ('Jemimah Rodrigues',               'batting_hand',         'Right'),
    ('Jemimah Rodrigues',               'bowling_style',        'Right-arm Spin'),
    ('Jemimah Rodrigues',               'role',                 'Batter'),
    ('Jemimah Rodrigues',               'combined_matches',     '182'),
    ('Jemimah Rodrigues',               'combined_runs',        '3800'),
    ('Jemimah Rodrigues',               'combined_wickets',     '5'),
    ('Jemimah Rodrigues',               'debut_year',           '2018'),

    ('Richa Ghosh',                     'active_status',       'Active'),
    ('Richa Ghosh',                     'country',              'India'),
    ('Richa Ghosh',                     'batting_hand',         'Right'),
    ('Richa Ghosh',                     'bowling_style',        'Right-arm Pace'),
    ('Richa Ghosh',                     'role',                 'Wicketkeeper-Batter'),
    ('Richa Ghosh',                     'combined_matches',     '117'),
    ('Richa Ghosh',                     'combined_runs',        '2330'),
    ('Richa Ghosh',                     'combined_wickets',     '1'),
    ('Richa Ghosh',                     'debut_year',           '2020'),

    ('Renuka Singh Thakur',             'active_status',       'Active'),
    ('Renuka Singh Thakur',             'country',              'India'),
    ('Renuka Singh Thakur',             'batting_hand',         'Right'),
    ('Renuka Singh Thakur',             'bowling_style',        'Right-arm Pace'),
    ('Renuka Singh Thakur',             'role',                 'Bowler'),
    ('Renuka Singh Thakur',             'combined_matches',     '102'),
    ('Renuka Singh Thakur',             'combined_runs',        '350'),
    ('Renuka Singh Thakur',             'combined_wickets',     '113'),
    ('Renuka Singh Thakur',             'debut_year',           '2021'),

    ('Radha Yadav',                     'active_status',       'Active'),
    ('Radha Yadav',                     'country',              'India'),
    ('Radha Yadav',                     'batting_hand',         'Right'),
    ('Radha Yadav',                     'bowling_style',        'Left-arm Spin'),
    ('Radha Yadav',                     'role',                 'Bowling All-rounder'),
    ('Radha Yadav',                     'combined_matches',     '151'),
    ('Radha Yadav',                     'combined_runs',        '900'),
    ('Radha Yadav',                     'combined_wickets',     '156'),
    ('Radha Yadav',                     'debut_year',           '2018'),

    ('Tahlia McGrath',                  'active_status',       'Active'),
    ('Tahlia McGrath',                  'country',              'Australia'),
    ('Tahlia McGrath',                  'batting_hand',         'Right'),
    ('Tahlia McGrath',                  'bowling_style',        'Right-arm Pace'),
    ('Tahlia McGrath',                  'role',                 'All-rounder'),
    ('Tahlia McGrath',                  'combined_matches',     '65'),
    ('Tahlia McGrath',                  'combined_runs',        '1397'),
    ('Tahlia McGrath',                  'combined_wickets',     '66'),
    ('Tahlia McGrath',                  'debut_year',           '2016'),

    ('Ashleigh Gardner',                'active_status',       'Active'),
    ('Ashleigh Gardner',                'country',              'Australia'),
    ('Ashleigh Gardner',                'batting_hand',         'Right'),
    ('Ashleigh Gardner',                'bowling_style',        'Right-arm Spin'),
    ('Ashleigh Gardner',                'role',                 'All-rounder'),
    ('Ashleigh Gardner',                'combined_matches',     '195'),
    ('Ashleigh Gardner',                'combined_runs',        '3850'),
    ('Ashleigh Gardner',                'combined_wickets',     '220'),
    ('Ashleigh Gardner',                'debut_year',           '2017'),

    ('Beth Mooney',                     'active_status',       'Active'),
    ('Beth Mooney',                     'country',              'Australia'),
    ('Beth Mooney',                     'batting_hand',         'Left'),
    ('Beth Mooney',                     'bowling_style',        'Hasn''t Bowled'),
    ('Beth Mooney',                     'role',                 'Wicketkeeper-Batter'),
    ('Beth Mooney',                     'combined_matches',     '221'),
    ('Beth Mooney',                     'combined_runs',        '7695'),
    ('Beth Mooney',                     'combined_wickets',     '0'),
    ('Beth Mooney',                     'debut_year',           '2016'),

    ('Megan Schutt',                    'active_status',       'Active'),
    ('Megan Schutt',                    'country',              'Australia'),
    ('Megan Schutt',                    'batting_hand',         'Right'),
    ('Megan Schutt',                    'bowling_style',        'Right-arm Pace'),
    ('Megan Schutt',                    'role',                 'Bowler'),
    ('Megan Schutt',                    'combined_matches',     '239'),
    ('Megan Schutt',                    'combined_runs',        '450'),
    ('Megan Schutt',                    'combined_wickets',     '265'),
    ('Megan Schutt',                    'debut_year',           '2012'),

    ('Annabel Sutherland',              'active_status',       'Active'),
    ('Annabel Sutherland',              'country',              'Australia'),
    ('Annabel Sutherland',              'batting_hand',         'Right'),
    ('Annabel Sutherland',              'bowling_style',        'Right-arm Pace'),
    ('Annabel Sutherland',              'role',                 'All-rounder'),
    ('Annabel Sutherland',              'combined_matches',     '96'),
    ('Annabel Sutherland',              'combined_runs',        '1358'),
    ('Annabel Sutherland',              'combined_wickets',     '94'),
    ('Annabel Sutherland',              'debut_year',           '2020'),

    ('Sophie Ecclestone',               'active_status',       'Active'),
    ('Sophie Ecclestone',               'country',              'England'),
    ('Sophie Ecclestone',               'batting_hand',         'Right'),
    ('Sophie Ecclestone',               'bowling_style',        'Left-arm Spin'),
    ('Sophie Ecclestone',               'role',                 'Bowler'),
    ('Sophie Ecclestone',               'combined_matches',     '202'),
    ('Sophie Ecclestone',               'combined_runs',        '750'),
    ('Sophie Ecclestone',               'combined_wickets',     '322'),
    ('Sophie Ecclestone',               'debut_year',           '2016'),

    ('Tammy Beaumont',                  'active_status',       'Retired'),
    ('Tammy Beaumont',                  'country',              'England'),
    ('Tammy Beaumont',                  'batting_hand',         'Right'),
    ('Tammy Beaumont',                  'bowling_style',        'Hasn''t Bowled'),
    ('Tammy Beaumont',                  'role',                 'Batter'),
    ('Tammy Beaumont',                  'combined_matches',     '270'),
    ('Tammy Beaumont',                  'combined_runs',        '7500'),
    ('Tammy Beaumont',                  'combined_wickets',     '0'),
    ('Tammy Beaumont',                  'debut_year',           '2009'),

    ('Alice Capsey',                    'active_status',       'Active'),
    ('Alice Capsey',                    'country',              'England'),
    ('Alice Capsey',                    'batting_hand',         'Right'),
    ('Alice Capsey',                    'bowling_style',        'Right-arm Spin'),
    ('Alice Capsey',                    'role',                 'Batting All-rounder'),
    ('Alice Capsey',                    'combined_matches',     '68'),
    ('Alice Capsey',                    'combined_runs',        '1340'),
    ('Alice Capsey',                    'combined_wickets',     '8'),
    ('Alice Capsey',                    'debut_year',           '2022'),

    ('Danni Wyatt',                     'active_status',       'Active'),
    ('Danni Wyatt',                     'country',              'England'),
    ('Danni Wyatt',                     'batting_hand',         'Right'),
    ('Danni Wyatt',                     'bowling_style',        'Right-arm Spin'),
    ('Danni Wyatt',                     'role',                 'Batter'),
    ('Danni Wyatt',                     'combined_matches',     '263'),
    ('Danni Wyatt',                     'combined_runs',        '5135'),
    ('Danni Wyatt',                     'combined_wickets',     '51'),
    ('Danni Wyatt',                     'debut_year',           '2010'),

    ('Sophia Dunkley',                  'active_status',       'Active'),
    ('Sophia Dunkley',                  'country',              'England'),
    ('Sophia Dunkley',                  'batting_hand',         'Right'),
    ('Sophia Dunkley',                  'bowling_style',        'Right-arm Spin'),
    ('Sophia Dunkley',                  'role',                 'Batter'),
    ('Sophia Dunkley',                  'combined_matches',     '104'),
    ('Sophia Dunkley',                  'combined_runs',        '2200'),
    ('Sophia Dunkley',                  'combined_wickets',     '12'),
    ('Sophia Dunkley',                  'debut_year',           '2018'),

    ('Hayley Matthews',                 'active_status',       'Active'),
    ('Hayley Matthews',                 'country',              'West Indies'),
    ('Hayley Matthews',                 'batting_hand',         'Right'),
    ('Hayley Matthews',                 'bowling_style',        'Right-arm Spin'),
    ('Hayley Matthews',                 'role',                 'All-rounder'),
    ('Hayley Matthews',                 'combined_matches',     '205'),
    ('Hayley Matthews',                 'combined_runs',        '5936'),
    ('Hayley Matthews',                 'combined_wickets',     '184'),
    ('Hayley Matthews',                 'debut_year',           '2016'),

    ('Chinelle Henry',                  'active_status',       'Active'),
    ('Chinelle Henry',                  'country',              'West Indies'),
    ('Chinelle Henry',                  'batting_hand',         'Right'),
    ('Chinelle Henry',                  'bowling_style',        'Right-arm Pace'),
    ('Chinelle Henry',                  'role',                 'All-rounder'),
    ('Chinelle Henry',                  'combined_matches',     '135'),
    ('Chinelle Henry',                  'combined_runs',        '1524'),
    ('Chinelle Henry',                  'combined_wickets',     '59'),
    ('Chinelle Henry',                  'debut_year',           '2013'),

    ('Lea Tahuhu',                      'active_status',       'Active'),
    ('Lea Tahuhu',                      'country',              'New Zealand'),
    ('Lea Tahuhu',                      'batting_hand',         'Right'),
    ('Lea Tahuhu',                      'bowling_style',        'Right-arm Pace'),
    ('Lea Tahuhu',                      'role',                 'Bowler'),
    ('Lea Tahuhu',                      'combined_matches',     '195'),
    ('Lea Tahuhu',                      'combined_runs',        '450'),
    ('Lea Tahuhu',                      'combined_wickets',     '205'),
    ('Lea Tahuhu',                      'debut_year',           '2011'),

    ('Maddy Green',                     'active_status',       'Active'),
    ('Maddy Green',                     'country',              'New Zealand'),
    ('Maddy Green',                     'batting_hand',         'Right'),
    ('Maddy Green',                     'bowling_style',        'Right-arm Spin'),
    ('Maddy Green',                     'role',                 'Batter'),
    ('Maddy Green',                     'combined_matches',     '170'),
    ('Maddy Green',                     'combined_runs',        '3500'),
    ('Maddy Green',                     'combined_wickets',     '18'),
    ('Maddy Green',                     'debut_year',           '2012'),

    ('Georgia Plimmer',                 'active_status',       'Active'),
    ('Georgia Plimmer',                 'country',              'New Zealand'),
    ('Georgia Plimmer',                 'batting_hand',         'Right'),
    ('Georgia Plimmer',                 'bowling_style',        'Right-arm Pace'),
    ('Georgia Plimmer',                 'role',                 'Batter'),
    ('Georgia Plimmer',                 'combined_matches',     '78'),
    ('Georgia Plimmer',                 'combined_runs',        '1149'),
    ('Georgia Plimmer',                 'combined_wickets',     '0'),
    ('Georgia Plimmer',                 'debut_year',           '2022'),

    ('Laura Wolvaardt',                 'active_status',       'Active'),
    ('Laura Wolvaardt',                 'country',              'South Africa'),
    ('Laura Wolvaardt',                 'batting_hand',         'Right'),
    ('Laura Wolvaardt',                 'bowling_style',        'Hasn''t Bowled'),
    ('Laura Wolvaardt',                 'role',                 'Batter'),
    ('Laura Wolvaardt',                 'combined_matches',     '197'),
    ('Laura Wolvaardt',                 'combined_runs',        '7214'),
    ('Laura Wolvaardt',                 'combined_wickets',     '0'),
    ('Laura Wolvaardt',                 'debut_year',           '2016'),

    ('Nadine de Klerk',                 'active_status',       'Active'),
    ('Nadine de Klerk',                 'country',              'South Africa'),
    ('Nadine de Klerk',                 'batting_hand',         'Right'),
    ('Nadine de Klerk',                 'bowling_style',        'Right-arm Pace'),
    ('Nadine de Klerk',                 'role',                 'All-rounder'),
    ('Nadine de Klerk',                 'combined_matches',     '154'),
    ('Nadine de Klerk',                 'combined_runs',        '2186'),
    ('Nadine de Klerk',                 'combined_wickets',     '107'),
    ('Nadine de Klerk',                 'debut_year',           '2017'),

    ('Ayabonga Khaka',                  'active_status',       'Active'),
    ('Ayabonga Khaka',                  'country',              'South Africa'),
    ('Ayabonga Khaka',                  'batting_hand',         'Right'),
    ('Ayabonga Khaka',                  'bowling_style',        'Right-arm Pace'),
    ('Ayabonga Khaka',                  'role',                 'Bowler'),
    ('Ayabonga Khaka',                  'combined_matches',     '193'),
    ('Ayabonga Khaka',                  'combined_runs',        '800'),
    ('Ayabonga Khaka',                  'combined_wickets',     '180'),
    ('Ayabonga Khaka',                  'debut_year',           '2012'),

    ('Aliya Riaz',                      'active_status',       'Active'),
    ('Aliya Riaz',                      'country',              'Pakistan'),
    ('Aliya Riaz',                      'batting_hand',         'Right'),
    ('Aliya Riaz',                      'bowling_style',        'Right-arm Pace'),
    ('Aliya Riaz',                      'role',                 'All-rounder'),
    ('Aliya Riaz',                      'combined_matches',     '205'),
    ('Aliya Riaz',                      'combined_runs',        '3096'),
    ('Aliya Riaz',                      'combined_wickets',     '55'),
    ('Aliya Riaz',                      'debut_year',           '2014'),

    ('Fatima Sana',                     'active_status',       'Active'),
    ('Fatima Sana',                     'country',              'Pakistan'),
    ('Fatima Sana',                     'batting_hand',         'Right'),
    ('Fatima Sana',                     'bowling_style',        'Right-arm Pace'),
    ('Fatima Sana',                     'role',                 'Bowling All-rounder'),
    ('Fatima Sana',                     'combined_matches',     '150'),
    ('Fatima Sana',                     'combined_runs',        '1500'),
    ('Fatima Sana',                     'combined_wickets',     '160'),
    ('Fatima Sana',                     'debut_year',           '2019'),

    ('Harshitha Samarawickrama',        'active_status',       'Active'),
    ('Harshitha Samarawickrama',        'country',              'Sri Lanka'),
    ('Harshitha Samarawickrama',        'batting_hand',         'Left'),
    ('Harshitha Samarawickrama',        'bowling_style',        'Right-arm Pace'),
    ('Harshitha Samarawickrama',        'role',                 'Batter'),
    ('Harshitha Samarawickrama',        'combined_matches',     '130'),
    ('Harshitha Samarawickrama',        'combined_runs',        '2900'),
    ('Harshitha Samarawickrama',        'combined_wickets',     '6'),
    ('Harshitha Samarawickrama',        'debut_year',           '2016'),

    ('Kavisha Dilhari',                 'active_status',       'Active'),
    ('Kavisha Dilhari',                 'country',              'Sri Lanka'),
    ('Kavisha Dilhari',                 'batting_hand',         'Right'),
    ('Kavisha Dilhari',                 'bowling_style',        'Right-arm Spin'),
    ('Kavisha Dilhari',                 'role',                 'Batting All-rounder'),
    ('Kavisha Dilhari',                 'combined_matches',     '62'),
    ('Kavisha Dilhari',                 'combined_runs',        '653'),
    ('Kavisha Dilhari',                 'combined_wickets',     '44'),
    ('Kavisha Dilhari',                 'debut_year',           '2018'),

    ('Rumana Ahmed',                    'active_status',       'Retired'),
    ('Rumana Ahmed',                    'country',              'Bangladesh'),
    ('Rumana Ahmed',                    'batting_hand',         'Right'),
    ('Rumana Ahmed',                    'bowling_style',        'Right-arm Spin'),
    ('Rumana Ahmed',                    'role',                 'All-rounder'),
    ('Rumana Ahmed',                    'combined_matches',     '185'),
    ('Rumana Ahmed',                    'combined_runs',        '2100'),
    ('Rumana Ahmed',                    'combined_wickets',     '160'),
    ('Rumana Ahmed',                    'debut_year',           '2011'),

    ('Gaby Lewis',                      'active_status',       'Active'),
    ('Gaby Lewis',                      'country',              'Ireland'),
    ('Gaby Lewis',                      'batting_hand',         'Right'),
    ('Gaby Lewis',                      'bowling_style',        'Right-arm Spin'),
    ('Gaby Lewis',                      'role',                 'Batter'),
    ('Gaby Lewis',                      'combined_matches',     '164'),
    ('Gaby Lewis',                      'combined_runs',        '4466'),
    ('Gaby Lewis',                      'combined_wickets',     '13'),
    ('Gaby Lewis',                      'debut_year',           '2014'),

    ('Sarah Bryce',                     'active_status',       'Active'),
    ('Sarah Bryce',                     'country',              'Scotland'),
    ('Sarah Bryce',                     'batting_hand',         'Right'),
    ('Sarah Bryce',                     'bowling_style',        'Hasn''t Bowled'),
    ('Sarah Bryce',                     'role',                 'Wicketkeeper-Batter'),
    ('Sarah Bryce',                     'combined_matches',     '91'),
    ('Sarah Bryce',                     'combined_runs',        '2029'),
    ('Sarah Bryce',                     'combined_wickets',     '0'),
    ('Sarah Bryce',                     'debut_year',           '2018')
) AS v("PlayerName", "AttrKey", "Value")
JOIN "Players" p ON p."Name" = v."PlayerName"
JOIN "AttributeDefinitions" ad ON ad."Key" = v."AttrKey" AND ad."SportId" = p."SportId"
ON CONFLICT ("PlayerId", "AttributeDefinitionId") DO UPDATE SET
    "Value" = EXCLUDED."Value";
