-- Men's International Cricket players, batch 1 (30 players). Same upsert
-- pattern as the Tennis batch files: Players upserts on the unique Name
-- constraint, PlayerAttributeValues upserts on the existing unique
-- (PlayerId, AttributeDefinitionId) constraint, both scoped to the
-- "cricket-men-international" Sport. No overrides in this batch -- every
-- row is IsOverridden = false, DifficultyOverride = NULL.

INSERT INTO "Players" ("SportId", "Name", "IsOverridden", "DifficultyOverride")
SELECT s."Id", v."Name", v."IsOverridden", v."DifficultyOverride"
FROM "Sports" s
CROSS JOIN (VALUES
    ('Sourav Ganguly',          false, NULL),
    ('Sachin Tendulkar',        false, NULL),
    ('Virat Kohli',             false, NULL),
    ('Rahul Dravid',            false, NULL),
    ('Kapil Dev',               false, NULL),
    ('MS Dhoni',                false, NULL),
    ('Don Bradman',             false, NULL),
    ('Ricky Ponting',           false, NULL),
    ('Shane Warne',             false, NULL),
    ('Glenn McGrath',           false, NULL),
    ('Steve Smith',             false, NULL),
    ('Brian Lara',              false, NULL),
    ('Viv Richards',            false, NULL),
    ('Imran Khan',              false, NULL),
    ('Wasim Akram',             false, NULL),
    ('Babar Azam',              false, NULL),
    ('Inzamam-ul-Haq',          false, NULL),
    ('Ben Stokes',              false, NULL),
    ('Joe Root',                false, NULL),
    ('Ian Botham',              false, NULL),
    ('Eoin Morgan',             false, NULL),
    ('Muttiah Muralitharan',    false, NULL),
    ('Kumar Sangakkara',        false, NULL),
    ('AB de Villiers',          false, NULL),
    ('Jacques Kallis',          false, NULL),
    ('Ross Taylor',             false, NULL),
    ('Kane Williamson',         false, NULL),
    ('Rashid Khan',             false, NULL),
    ('Shakib Al Hasan',         false, NULL),
    ('Paul Stirling',           false, NULL)
) AS v("Name", "IsOverridden", "DifficultyOverride")
WHERE s."Slug" = 'cricket-men-international'
ON CONFLICT ("Name") DO UPDATE SET
    "SportId" = EXCLUDED."SportId",
    "IsOverridden" = CASE WHEN "Players"."IsOverridden" THEN "Players"."IsOverridden" ELSE EXCLUDED."IsOverridden" END,
    "DifficultyOverride" = CASE WHEN "Players"."IsOverridden" THEN "Players"."DifficultyOverride" ELSE EXCLUDED."DifficultyOverride" END;

-- One row per (player, attribute) pair. PlayerId/AttributeDefinitionId are
-- resolved by name/key lookup (scoped to each player's own SportId), so
-- this file has no dependency on insertion order or id values, and can
-- never cross-attach to cricket-women-international's AttributeDefinitions.
INSERT INTO "PlayerAttributeValues" ("PlayerId", "AttributeDefinitionId", "Value")
SELECT p."Id", ad."Id", v."Value"
FROM (VALUES
    -- Player,                       AttrKey,               Value
    ('Sourav Ganguly',               'active_status',       'Retired'),
    ('Sourav Ganguly',               'country',              'India'),
    ('Sourav Ganguly',               'batting_hand',         'Left'),
    ('Sourav Ganguly',               'bowling_style',        'Right-arm Pace'),
    ('Sourav Ganguly',               'role',                 'Batter'),
    ('Sourav Ganguly',               'combined_matches',     '424'),
    ('Sourav Ganguly',               'combined_runs',        '18575'),
    ('Sourav Ganguly',               'combined_wickets',     '132'),
    ('Sourav Ganguly',               'debut_year',           '1992'),

    ('Sachin Tendulkar',             'active_status',       'Retired'),
    ('Sachin Tendulkar',             'country',              'India'),
    ('Sachin Tendulkar',             'batting_hand',         'Right'),
    ('Sachin Tendulkar',             'bowling_style',        'Right-arm Spin'),
    ('Sachin Tendulkar',             'role',                 'Batter'),
    ('Sachin Tendulkar',             'combined_matches',     '664'),
    ('Sachin Tendulkar',             'combined_runs',        '34357'),
    ('Sachin Tendulkar',             'combined_wickets',     '200'),
    ('Sachin Tendulkar',             'debut_year',           '1989'),

    ('Virat Kohli',                  'active_status',       'Active'),
    ('Virat Kohli',                  'country',              'India'),
    ('Virat Kohli',                  'batting_hand',         'Right'),
    ('Virat Kohli',                  'bowling_style',        'Right-arm Pace'),
    ('Virat Kohli',                  'role',                 'Batter'),
    ('Virat Kohli',                  'combined_matches',     '550'),
    ('Virat Kohli',                  'combined_runs',        '27599'),
    ('Virat Kohli',                  'combined_wickets',     '8'),
    ('Virat Kohli',                  'debut_year',           '2008'),

    ('Rahul Dravid',                 'active_status',       'Retired'),
    ('Rahul Dravid',                 'country',              'India'),
    ('Rahul Dravid',                 'batting_hand',         'Right'),
    ('Rahul Dravid',                 'bowling_style',        'Right-arm Spin'),
    ('Rahul Dravid',                 'role',                 'Batter'),
    ('Rahul Dravid',                 'combined_matches',     '509'),
    ('Rahul Dravid',                 'combined_runs',        '24208'),
    ('Rahul Dravid',                 'combined_wickets',     '5'),
    ('Rahul Dravid',                 'debut_year',           '1996'),

    ('Kapil Dev',                    'active_status',       'Retired'),
    ('Kapil Dev',                    'country',              'India'),
    ('Kapil Dev',                    'batting_hand',         'Right'),
    ('Kapil Dev',                    'bowling_style',        'Right-arm Pace'),
    ('Kapil Dev',                    'role',                 'All-rounder'),
    ('Kapil Dev',                    'combined_matches',     '356'),
    ('Kapil Dev',                    'combined_runs',        '9031'),
    ('Kapil Dev',                    'combined_wickets',     '687'),
    ('Kapil Dev',                    'debut_year',           '1978'),

    ('MS Dhoni',                     'active_status',       'Retired'),
    ('MS Dhoni',                     'country',              'India'),
    ('MS Dhoni',                     'batting_hand',         'Right'),
    ('MS Dhoni',                     'bowling_style',        'Right-arm Pace'),
    ('MS Dhoni',                     'role',                 'Wicketkeeper-Batter'),
    ('MS Dhoni',                     'combined_matches',     '538'),
    ('MS Dhoni',                     'combined_runs',        '17266'),
    ('MS Dhoni',                     'combined_wickets',     '1'),
    ('MS Dhoni',                     'debut_year',           '2004'),

    ('Don Bradman',                  'active_status',       'Retired'),
    ('Don Bradman',                  'country',              'Australia'),
    ('Don Bradman',                  'batting_hand',         'Right'),
    ('Don Bradman',                  'bowling_style',        'Hasn''t Bowled'),
    ('Don Bradman',                  'role',                 'Batter'),
    ('Don Bradman',                  'combined_matches',     '52'),
    ('Don Bradman',                  'combined_runs',        '6996'),
    ('Don Bradman',                  'combined_wickets',     '2'),
    ('Don Bradman',                  'debut_year',           '1928'),

    ('Ricky Ponting',                'active_status',       'Retired'),
    ('Ricky Ponting',                'country',              'Australia'),
    ('Ricky Ponting',                'batting_hand',         'Right'),
    ('Ricky Ponting',                'bowling_style',        'Right-arm Pace'),
    ('Ricky Ponting',                'role',                 'Batter'),
    ('Ricky Ponting',                'combined_matches',     '560'),
    ('Ricky Ponting',                'combined_runs',        '27483'),
    ('Ricky Ponting',                'combined_wickets',     '5'),
    ('Ricky Ponting',                'debut_year',           '1995'),

    ('Shane Warne',                  'active_status',       'Retired'),
    ('Shane Warne',                  'country',              'Australia'),
    ('Shane Warne',                  'batting_hand',         'Right'),
    ('Shane Warne',                  'bowling_style',        'Right-arm Spin'),
    ('Shane Warne',                  'role',                 'Bowler'),
    ('Shane Warne',                  'combined_matches',     '339'),
    ('Shane Warne',                  'combined_runs',        '3700'),
    ('Shane Warne',                  'combined_wickets',     '1001'),
    ('Shane Warne',                  'debut_year',           '1992'),

    ('Glenn McGrath',                'active_status',       'Retired'),
    ('Glenn McGrath',                'country',              'Australia'),
    ('Glenn McGrath',                'batting_hand',         'Right'),
    ('Glenn McGrath',                'bowling_style',        'Right-arm Pace'),
    ('Glenn McGrath',                'role',                 'Bowler'),
    ('Glenn McGrath',                'combined_matches',     '376'),
    ('Glenn McGrath',                'combined_runs',        '1200'),
    ('Glenn McGrath',                'combined_wickets',     '946'),
    ('Glenn McGrath',                'debut_year',           '1993'),

    ('Steve Smith',                  'active_status',       'Active'),
    ('Steve Smith',                  'country',              'Australia'),
    ('Steve Smith',                  'batting_hand',         'Right'),
    ('Steve Smith',                  'bowling_style',        'Right-arm Spin'),
    ('Steve Smith',                  'role',                 'Batter'),
    ('Steve Smith',                  'combined_matches',     '350'),
    ('Steve Smith',                  'combined_runs',        '17000'),
    ('Steve Smith',                  'combined_wickets',     '25'),
    ('Steve Smith',                  'debut_year',           '2010'),

    ('Brian Lara',                   'active_status',       'Retired'),
    ('Brian Lara',                   'country',              'West Indies'),
    ('Brian Lara',                   'batting_hand',         'Left'),
    ('Brian Lara',                   'bowling_style',        'Right-arm Spin'),
    ('Brian Lara',                   'role',                 'Batter'),
    ('Brian Lara',                   'combined_matches',     '430'),
    ('Brian Lara',                   'combined_runs',        '22358'),
    ('Brian Lara',                   'combined_wickets',     '5'),
    ('Brian Lara',                   'debut_year',           '1990'),

    ('Viv Richards',                 'active_status',       'Retired'),
    ('Viv Richards',                 'country',              'West Indies'),
    ('Viv Richards',                 'batting_hand',         'Right'),
    ('Viv Richards',                 'bowling_style',        'Right-arm Spin'),
    ('Viv Richards',                 'role',                 'Batter'),
    ('Viv Richards',                 'combined_matches',     '308'),
    ('Viv Richards',                 'combined_runs',        '15261'),
    ('Viv Richards',                 'combined_wickets',     '150'),
    ('Viv Richards',                 'debut_year',           '1974'),

    ('Imran Khan',                   'active_status',       'Retired'),
    ('Imran Khan',                   'country',              'Pakistan'),
    ('Imran Khan',                   'batting_hand',         'Right'),
    ('Imran Khan',                   'bowling_style',        'Right-arm Pace'),
    ('Imran Khan',                   'role',                 'Bowling All-rounder'),
    ('Imran Khan',                   'combined_matches',     '263'),
    ('Imran Khan',                   'combined_runs',        '7516'),
    ('Imran Khan',                   'combined_wickets',     '544'),
    ('Imran Khan',                   'debut_year',           '1971'),

    ('Wasim Akram',                  'active_status',       'Retired'),
    ('Wasim Akram',                  'country',              'Pakistan'),
    ('Wasim Akram',                  'batting_hand',         'Left'),
    ('Wasim Akram',                  'bowling_style',        'Left-arm Pace'),
    ('Wasim Akram',                  'role',                 'Bowler'),
    ('Wasim Akram',                  'combined_matches',     '460'),
    ('Wasim Akram',                  'combined_runs',        '6615'),
    ('Wasim Akram',                  'combined_wickets',     '916'),
    ('Wasim Akram',                  'debut_year',           '1984'),

    ('Babar Azam',                   'active_status',       'Active'),
    ('Babar Azam',                   'country',              'Pakistan'),
    ('Babar Azam',                   'batting_hand',         'Right'),
    ('Babar Azam',                   'bowling_style',        'Right-arm Spin'),
    ('Babar Azam',                   'role',                 'Batter'),
    ('Babar Azam',                   'combined_matches',     '320'),
    ('Babar Azam',                   'combined_runs',        '15500'),
    ('Babar Azam',                   'combined_wickets',     '5'),
    ('Babar Azam',                   'debut_year',           '2015'),

    ('Inzamam-ul-Haq',                'active_status',       'Retired'),
    ('Inzamam-ul-Haq',                'country',              'Pakistan'),
    ('Inzamam-ul-Haq',                'batting_hand',         'Right'),
    ('Inzamam-ul-Haq',                'bowling_style',        'Left-arm Spin'),
    ('Inzamam-ul-Haq',                'role',                 'Batter'),
    ('Inzamam-ul-Haq',                'combined_matches',     '499'),
    ('Inzamam-ul-Haq',                'combined_runs',        '18569'),
    ('Inzamam-ul-Haq',                'combined_wickets',     '22'),
    ('Inzamam-ul-Haq',                'debut_year',           '1991'),

    ('Ben Stokes',                   'active_status',       'Retired'),
    ('Ben Stokes',                   'country',              'England'),
    ('Ben Stokes',                   'batting_hand',         'Left'),
    ('Ben Stokes',                   'bowling_style',        'Right-arm Pace'),
    ('Ben Stokes',                   'role',                 'All-rounder'),
    ('Ben Stokes',                   'combined_matches',     '262'),
    ('Ben Stokes',                   'combined_runs',        '11000'),
    ('Ben Stokes',                   'combined_wickets',     '301'),
    ('Ben Stokes',                   'debut_year',           '2011'),

    ('Joe Root',                     'active_status',       'Active'),
    ('Joe Root',                     'country',              'England'),
    ('Joe Root',                     'batting_hand',         'Right'),
    ('Joe Root',                     'bowling_style',        'Right-arm Spin'),
    ('Joe Root',                     'role',                 'Batter'),
    ('Joe Root',                     'combined_matches',     '378'),
    ('Joe Root',                     'combined_runs',        '21607'),
    ('Joe Root',                     'combined_wickets',     '66'),
    ('Joe Root',                     'debut_year',           '2012'),

    ('Ian Botham',                   'active_status',       'Retired'),
    ('Ian Botham',                   'country',              'England'),
    ('Ian Botham',                   'batting_hand',         'Right'),
    ('Ian Botham',                   'bowling_style',        'Right-arm Pace'),
    ('Ian Botham',                   'role',                 'All-rounder'),
    ('Ian Botham',                   'combined_matches',     '218'),
    ('Ian Botham',                   'combined_runs',        '7313'),
    ('Ian Botham',                   'combined_wickets',     '528'),
    ('Ian Botham',                   'debut_year',           '1976'),

    ('Eoin Morgan',                  'active_status',       'Retired'),
    ('Eoin Morgan',                  'country',              'England'),
    ('Eoin Morgan',                  'batting_hand',         'Left'),
    ('Eoin Morgan',                  'bowling_style',        'Hasn''t Bowled'),
    ('Eoin Morgan',                  'role',                 'Batter'),
    ('Eoin Morgan',                  'combined_matches',     '379'),
    ('Eoin Morgan',                  'combined_runs',        '10859'),
    ('Eoin Morgan',                  'combined_wickets',     '2'),
    ('Eoin Morgan',                  'debut_year',           '2009'),

    ('Muttiah Muralitharan',         'active_status',       'Retired'),
    ('Muttiah Muralitharan',         'country',              'Sri Lanka'),
    ('Muttiah Muralitharan',         'batting_hand',         'Right'),
    ('Muttiah Muralitharan',         'bowling_style',        'Right-arm Spin'),
    ('Muttiah Muralitharan',         'role',                 'Bowler'),
    ('Muttiah Muralitharan',         'combined_matches',     '483'),
    ('Muttiah Muralitharan',         'combined_runs',        '1900'),
    ('Muttiah Muralitharan',         'combined_wickets',     '1334'),
    ('Muttiah Muralitharan',         'debut_year',           '1992'),

    ('Kumar Sangakkara',             'active_status',       'Retired'),
    ('Kumar Sangakkara',             'country',              'Sri Lanka'),
    ('Kumar Sangakkara',             'batting_hand',         'Left'),
    ('Kumar Sangakkara',             'bowling_style',        'Right-arm Spin'),
    ('Kumar Sangakkara',             'role',                 'Wicketkeeper-Batter'),
    ('Kumar Sangakkara',             'combined_matches',     '594'),
    ('Kumar Sangakkara',             'combined_runs',        '28016'),
    ('Kumar Sangakkara',             'combined_wickets',     '1'),
    ('Kumar Sangakkara',             'debut_year',           '2000'),

    ('AB de Villiers',               'active_status',       'Retired'),
    ('AB de Villiers',               'country',              'South Africa'),
    ('AB de Villiers',               'batting_hand',         'Right'),
    ('AB de Villiers',               'bowling_style',        'Right-arm Pace'),
    ('AB de Villiers',               'role',                 'Wicketkeeper-Batter'),
    ('AB de Villiers',               'combined_matches',     '420'),
    ('AB de Villiers',               'combined_runs',        '20014'),
    ('AB de Villiers',               'combined_wickets',     '13'),
    ('AB de Villiers',               'debut_year',           '2004'),

    ('Jacques Kallis',               'active_status',       'Retired'),
    ('Jacques Kallis',               'country',              'South Africa'),
    ('Jacques Kallis',               'batting_hand',         'Right'),
    ('Jacques Kallis',               'bowling_style',        'Right-arm Pace'),
    ('Jacques Kallis',               'role',                 'All-rounder'),
    ('Jacques Kallis',               'combined_matches',     '519'),
    ('Jacques Kallis',               'combined_runs',        '25534'),
    ('Jacques Kallis',               'combined_wickets',     '577'),
    ('Jacques Kallis',               'debut_year',           '1995'),

    ('Ross Taylor',                  'active_status',       'Retired'),
    ('Ross Taylor',                  'country',              'New Zealand'),
    ('Ross Taylor',                  'batting_hand',         'Right'),
    ('Ross Taylor',                  'bowling_style',        'Right-arm Spin'),
    ('Ross Taylor',                  'role',                 'Batter'),
    ('Ross Taylor',                  'combined_matches',     '450'),
    ('Ross Taylor',                  'combined_runs',        '18199'),
    ('Ross Taylor',                  'combined_wickets',     '0'),
    ('Ross Taylor',                  'debut_year',           '2006'),

    ('Kane Williamson',              'active_status',       'Retired'),
    ('Kane Williamson',              'country',              'New Zealand'),
    ('Kane Williamson',              'batting_hand',         'Right'),
    ('Kane Williamson',              'bowling_style',        'Right-arm Spin'),
    ('Kane Williamson',              'role',                 'Batter'),
    ('Kane Williamson',              'combined_matches',     '378'),
    ('Kane Williamson',              'combined_runs',        '19346'),
    ('Kane Williamson',              'combined_wickets',     '5'),
    ('Kane Williamson',              'debut_year',           '2010'),

    ('Rashid Khan',                  'active_status',       'Active'),
    ('Rashid Khan',                  'country',              'Afghanistan'),
    ('Rashid Khan',                  'batting_hand',         'Right'),
    ('Rashid Khan',                  'bowling_style',        'Right-arm Spin'),
    ('Rashid Khan',                  'role',                 'Bowling All-rounder'),
    ('Rashid Khan',                  'combined_matches',     '250'),
    ('Rashid Khan',                  'combined_runs',        '2500'),
    ('Rashid Khan',                  'combined_wickets',     '400'),
    ('Rashid Khan',                  'debut_year',           '2015'),

    ('Shakib Al Hasan',              'active_status',       'Active'),
    ('Shakib Al Hasan',              'country',              'Bangladesh'),
    ('Shakib Al Hasan',              'batting_hand',         'Left'),
    ('Shakib Al Hasan',              'bowling_style',        'Left-arm Spin'),
    ('Shakib Al Hasan',              'role',                 'All-rounder'),
    ('Shakib Al Hasan',              'combined_matches',     '447'),
    ('Shakib Al Hasan',              'combined_runs',        '14730'),
    ('Shakib Al Hasan',              'combined_wickets',     '706'),
    ('Shakib Al Hasan',              'debut_year',           '2006'),

    ('Paul Stirling',                'active_status',       'Active'),
    ('Paul Stirling',                'country',              'Ireland'),
    ('Paul Stirling',                'batting_hand',         'Right'),
    ('Paul Stirling',                'bowling_style',        'Right-arm Spin'),
    ('Paul Stirling',                'role',                 'Batter'),
    ('Paul Stirling',                'combined_matches',     '331'),
    ('Paul Stirling',                'combined_runs',        '10195'),
    ('Paul Stirling',                'combined_wickets',     '65'),
    ('Paul Stirling',                'debut_year',           '2008')
) AS v("PlayerName", "AttrKey", "Value")
JOIN "Players" p ON p."Name" = v."PlayerName"
JOIN "AttributeDefinitions" ad ON ad."Key" = v."AttrKey" AND ad."SportId" = p."SportId"
ON CONFLICT ("PlayerId", "AttributeDefinitionId") DO UPDATE SET
    "Value" = EXCLUDED."Value"
WHERE "PlayerAttributeValues"."IsManuallyEdited" = false;
