-- Men's International Cricket players, batch 6 (30 players, bringing the
-- roster to 180 total: batches 1-5's 150 + batch 6's 30). Same upsert
-- pattern as prior batches: Players upserts on the unique Name constraint,
-- PlayerAttributeValues upserts on the existing unique (PlayerId,
-- AttributeDefinitionId) constraint, both scoped to the
-- "cricket-men-international" Sport. No overrides in this batch -- every
-- row is IsOverridden = false, DifficultyOverride = NULL.

INSERT INTO "Players" ("SportId", "Name", "IsOverridden", "DifficultyOverride")
SELECT s."Id", v."Name", v."IsOverridden", v."DifficultyOverride"
FROM "Sports" s
CROSS JOIN (VALUES
    ('Yuzvendra Chahal',         false, NULL),
    ('Shreyas Iyer',             false, NULL),
    ('Ishan Kishan',             false, NULL),
    ('Arshdeep Singh',           false, NULL),
    ('Varun Chakravarthy',       false, NULL),
    ('Nathan Lyon',              false, NULL),
    ('Matthew Wade',             false, NULL),
    ('Josh Inglis',              false, NULL),
    ('Ashton Agar',              false, NULL),
    ('Zak Crawley',              false, NULL),
    ('Liam Livingstone',         false, NULL),
    ('Phil Salt',                false, NULL),
    ('Imam-ul-Haq',              false, NULL),
    ('Salman Agha',              false, NULL),
    ('Alzarri Joseph',           false, NULL),
    ('Roston Chase',             false, NULL),
    ('Akeal Hosein',             false, NULL),
    ('Daryl Mitchell',           false, NULL),
    ('Rachin Ravindra',          false, NULL),
    ('Matt Henry',               false, NULL),
    ('Heinrich Klaasen',         false, NULL),
    ('Marco Jansen',             false, NULL),
    ('Keshav Maharaj',           false, NULL),
    ('Kusal Mendis',             false, NULL),
    ('Charith Asalanka',         false, NULL),
    ('Maheesh Theekshana',       false, NULL),
    ('Najmul Hossain Shanto',    false, NULL),
    ('Taskin Ahmed',             false, NULL),
    ('Rahmanullah Gurbaz',       false, NULL),
    ('Sean Williams',            false, NULL)
) AS v("Name", "IsOverridden", "DifficultyOverride")
WHERE s."Slug" = 'cricket-men-international'
ON CONFLICT ("Name") DO UPDATE SET
    "SportId" = EXCLUDED."SportId",
    "IsOverridden" = EXCLUDED."IsOverridden",
    "DifficultyOverride" = EXCLUDED."DifficultyOverride";

-- One row per (player, attribute) pair. PlayerId/AttributeDefinitionId are
-- resolved by name/key lookup (scoped to each player's own SportId), so
-- this file has no dependency on insertion order or id values, and can
-- never cross-attach to cricket-women-international's AttributeDefinitions.
INSERT INTO "PlayerAttributeValues" ("PlayerId", "AttributeDefinitionId", "Value")
SELECT p."Id", ad."Id", v."Value"
FROM (VALUES
    -- Player,                          AttrKey,               Value
    ('Yuzvendra Chahal',                'active_status',       'Active'),
    ('Yuzvendra Chahal',                'country',              'India'),
    ('Yuzvendra Chahal',                'batting_hand',         'Right'),
    ('Yuzvendra Chahal',                'bowling_style',        'Right-arm Spin'),
    ('Yuzvendra Chahal',                'role',                 'Bowler'),
    ('Yuzvendra Chahal',                'combined_matches',     '152'),
    ('Yuzvendra Chahal',                'combined_runs',        '83'),
    ('Yuzvendra Chahal',                'combined_wickets',     '217'),
    ('Yuzvendra Chahal',                'debut_year',           '2016'),

    ('Shreyas Iyer',                    'active_status',       'Active'),
    ('Shreyas Iyer',                    'country',              'India'),
    ('Shreyas Iyer',                    'batting_hand',         'Right'),
    ('Shreyas Iyer',                    'bowling_style',        'Right-arm Spin'),
    ('Shreyas Iyer',                    'role',                 'Batter'),
    ('Shreyas Iyer',                    'combined_matches',     '135'),
    ('Shreyas Iyer',                    'combined_runs',        '4760'),
    ('Shreyas Iyer',                    'combined_wickets',     '6'),
    ('Shreyas Iyer',                    'debut_year',           '2017'),

    ('Ishan Kishan',                    'active_status',       'Active'),
    ('Ishan Kishan',                    'country',              'India'),
    ('Ishan Kishan',                    'batting_hand',         'Left'),
    ('Ishan Kishan',                    'bowling_style',        'Right-arm Pace'),
    ('Ishan Kishan',                    'role',                 'Wicketkeeper-Batter'),
    ('Ishan Kishan',                    'combined_matches',     '72'),
    ('Ishan Kishan',                    'combined_runs',        '2370'),
    ('Ishan Kishan',                    'combined_wickets',     '0'),
    ('Ishan Kishan',                    'debut_year',           '2021'),

    ('Arshdeep Singh',                  'active_status',       'Active'),
    ('Arshdeep Singh',                  'country',              'India'),
    ('Arshdeep Singh',                  'batting_hand',         'Left'),
    ('Arshdeep Singh',                  'bowling_style',        'Left-arm Pace'),
    ('Arshdeep Singh',                  'role',                 'Bowler'),
    ('Arshdeep Singh',                  'combined_matches',     '110'),
    ('Arshdeep Singh',                  'combined_runs',        '180'),
    ('Arshdeep Singh',                  'combined_wickets',     '160'),
    ('Arshdeep Singh',                  'debut_year',           '2022'),

    ('Varun Chakravarthy',              'active_status',       'Active'),
    ('Varun Chakravarthy',              'country',              'India'),
    ('Varun Chakravarthy',              'batting_hand',         'Right'),
    ('Varun Chakravarthy',              'bowling_style',        'Right-arm Spin'),
    ('Varun Chakravarthy',              'role',                 'Bowler'),
    ('Varun Chakravarthy',              'combined_matches',     '70'),
    ('Varun Chakravarthy',              'combined_runs',        '120'),
    ('Varun Chakravarthy',              'combined_wickets',     '93'),
    ('Varun Chakravarthy',              'debut_year',           '2021'),

    ('Nathan Lyon',                     'active_status',       'Active'),
    ('Nathan Lyon',                     'country',              'Australia'),
    ('Nathan Lyon',                     'batting_hand',         'Right'),
    ('Nathan Lyon',                     'bowling_style',        'Right-arm Spin'),
    ('Nathan Lyon',                     'role',                 'Bowler'),
    ('Nathan Lyon',                     'combined_matches',     '172'),
    ('Nathan Lyon',                     'combined_runs',        '1400'),
    ('Nathan Lyon',                     'combined_wickets',     '597'),
    ('Nathan Lyon',                     'debut_year',           '2011'),

    ('Matthew Wade',                    'active_status',       'Retired'),
    ('Matthew Wade',                    'country',              'Australia'),
    ('Matthew Wade',                    'batting_hand',         'Left'),
    ('Matthew Wade',                    'bowling_style',        'Right-arm Pace'),
    ('Matthew Wade',                    'role',                 'Wicketkeeper-Batter'),
    ('Matthew Wade',                    'combined_matches',     '225'),
    ('Matthew Wade',                    'combined_runs',        '5500'),
    ('Matthew Wade',                    'combined_wickets',     '5'),
    ('Matthew Wade',                    'debut_year',           '2011'),

    ('Josh Inglis',                     'active_status',       'Active'),
    ('Josh Inglis',                     'country',              'Australia'),
    ('Josh Inglis',                     'batting_hand',         'Right'),
    ('Josh Inglis',                     'bowling_style',        'Hasn''t Bowled'),
    ('Josh Inglis',                     'role',                 'Wicketkeeper-Batter'),
    ('Josh Inglis',                     'combined_matches',     '103'),
    ('Josh Inglis',                     'combined_runs',        '2050'),
    ('Josh Inglis',                     'combined_wickets',     '0'),
    ('Josh Inglis',                     'debut_year',           '2022'),

    ('Ashton Agar',                     'active_status',       'Retired'),
    ('Ashton Agar',                     'country',              'Australia'),
    ('Ashton Agar',                     'batting_hand',         'Left'),
    ('Ashton Agar',                     'bowling_style',        'Left-arm Spin'),
    ('Ashton Agar',                     'role',                 'Bowler'),
    ('Ashton Agar',                     'combined_matches',     '140'),
    ('Ashton Agar',                     'combined_runs',        '1800'),
    ('Ashton Agar',                     'combined_wickets',     '130'),
    ('Ashton Agar',                     'debut_year',           '2013'),

    ('Zak Crawley',                     'active_status',       'Active'),
    ('Zak Crawley',                     'country',              'England'),
    ('Zak Crawley',                     'batting_hand',         'Right'),
    ('Zak Crawley',                     'bowling_style',        'Right-arm Spin'),
    ('Zak Crawley',                     'role',                 'Batter'),
    ('Zak Crawley',                     'combined_matches',     '72'),
    ('Zak Crawley',                     'combined_runs',        '3785'),
    ('Zak Crawley',                     'combined_wickets',     '3'),
    ('Zak Crawley',                     'debut_year',           '2019'),

    ('Liam Livingstone',                'active_status',       'Active'),
    ('Liam Livingstone',                'country',              'England'),
    ('Liam Livingstone',                'batting_hand',         'Right'),
    ('Liam Livingstone',                'bowling_style',        'Right-arm Spin'),
    ('Liam Livingstone',                'role',                 'All-rounder'),
    ('Liam Livingstone',                'combined_matches',     '128'),
    ('Liam Livingstone',                'combined_runs',        '3200'),
    ('Liam Livingstone',                'combined_wickets',     '92'),
    ('Liam Livingstone',                'debut_year',           '2017'),

    ('Phil Salt',                       'active_status',       'Active'),
    ('Phil Salt',                       'country',              'England'),
    ('Phil Salt',                       'batting_hand',         'Right'),
    ('Phil Salt',                       'bowling_style',        'Right-arm Spin'),
    ('Phil Salt',                       'role',                 'Wicketkeeper-Batter'),
    ('Phil Salt',                       'combined_matches',     '93'),
    ('Phil Salt',                       'combined_runs',        '2705'),
    ('Phil Salt',                       'combined_wickets',     '3'),
    ('Phil Salt',                       'debut_year',           '2021'),

    ('Imam-ul-Haq',                     'active_status',       'Active'),
    ('Imam-ul-Haq',                     'country',              'Pakistan'),
    ('Imam-ul-Haq',                     'batting_hand',         'Left'),
    ('Imam-ul-Haq',                     'bowling_style',        'Right-arm Spin'),
    ('Imam-ul-Haq',                     'role',                 'Batter'),
    ('Imam-ul-Haq',                     'combined_matches',     '117'),
    ('Imam-ul-Haq',                     'combined_runs',        '5239'),
    ('Imam-ul-Haq',                     'combined_wickets',     '2'),
    ('Imam-ul-Haq',                     'debut_year',           '2017'),

    ('Salman Agha',                     'active_status',       'Active'),
    ('Salman Agha',                     'country',              'Pakistan'),
    ('Salman Agha',                     'batting_hand',         'Right'),
    ('Salman Agha',                     'bowling_style',        'Right-arm Spin'),
    ('Salman Agha',                     'role',                 'All-rounder'),
    ('Salman Agha',                     'combined_matches',     '105'),
    ('Salman Agha',                     'combined_runs',        '3200'),
    ('Salman Agha',                     'combined_wickets',     '65'),
    ('Salman Agha',                     'debut_year',           '2022'),

    ('Alzarri Joseph',                  'active_status',       'Active'),
    ('Alzarri Joseph',                  'country',              'West Indies'),
    ('Alzarri Joseph',                  'batting_hand',         'Right'),
    ('Alzarri Joseph',                  'bowling_style',        'Right-arm Pace'),
    ('Alzarri Joseph',                  'role',                 'Bowler'),
    ('Alzarri Joseph',                  'combined_matches',     '175'),
    ('Alzarri Joseph',                  'combined_runs',        '1500'),
    ('Alzarri Joseph',                  'combined_wickets',     '250'),
    ('Alzarri Joseph',                  'debut_year',           '2016'),

    ('Roston Chase',                    'active_status',       'Active'),
    ('Roston Chase',                    'country',              'West Indies'),
    ('Roston Chase',                    'batting_hand',         'Right'),
    ('Roston Chase',                    'bowling_style',        'Right-arm Spin'),
    ('Roston Chase',                    'role',                 'All-rounder'),
    ('Roston Chase',                    'combined_matches',     '189'),
    ('Roston Chase',                    'combined_runs',        '4717'),
    ('Roston Chase',                    'combined_wickets',     '129'),
    ('Roston Chase',                    'debut_year',           '2016'),

    ('Akeal Hosein',                    'active_status',       'Active'),
    ('Akeal Hosein',                    'country',              'West Indies'),
    ('Akeal Hosein',                    'batting_hand',         'Left'),
    ('Akeal Hosein',                    'bowling_style',        'Left-arm Spin'),
    ('Akeal Hosein',                    'role',                 'Bowler'),
    ('Akeal Hosein',                    'combined_matches',     '136'),
    ('Akeal Hosein',                    'combined_runs',        '900'),
    ('Akeal Hosein',                    'combined_wickets',     '156'),
    ('Akeal Hosein',                    'debut_year',           '2021'),

    ('Daryl Mitchell',                  'active_status',       'Active'),
    ('Daryl Mitchell',                  'country',              'New Zealand'),
    ('Daryl Mitchell',                  'batting_hand',         'Right'),
    ('Daryl Mitchell',                  'bowling_style',        'Right-arm Pace'),
    ('Daryl Mitchell',                  'role',                 'All-rounder'),
    ('Daryl Mitchell',                  'combined_matches',     '145'),
    ('Daryl Mitchell',                  'combined_runs',        '6500'),
    ('Daryl Mitchell',                  'combined_wickets',     '40'),
    ('Daryl Mitchell',                  'debut_year',           '2019'),

    ('Rachin Ravindra',                 'active_status',       'Active'),
    ('Rachin Ravindra',                 'country',              'New Zealand'),
    ('Rachin Ravindra',                 'batting_hand',         'Left'),
    ('Rachin Ravindra',                 'bowling_style',        'Left-arm Spin'),
    ('Rachin Ravindra',                 'role',                 'All-rounder'),
    ('Rachin Ravindra',                 'combined_matches',     '85'),
    ('Rachin Ravindra',                 'combined_runs',        '3800'),
    ('Rachin Ravindra',                 'combined_wickets',     '50'),
    ('Rachin Ravindra',                 'debut_year',           '2021'),

    ('Matt Henry',                      'active_status',       'Active'),
    ('Matt Henry',                      'country',              'New Zealand'),
    ('Matt Henry',                      'batting_hand',         'Right'),
    ('Matt Henry',                      'bowling_style',        'Right-arm Pace'),
    ('Matt Henry',                      'role',                 'Bowler'),
    ('Matt Henry',                      'combined_matches',     '193'),
    ('Matt Henry',                      'combined_runs',        '1200'),
    ('Matt Henry',                      'combined_wickets',     '350'),
    ('Matt Henry',                      'debut_year',           '2014'),

    ('Heinrich Klaasen',                'active_status',       'Retired'),
    ('Heinrich Klaasen',                'country',              'South Africa'),
    ('Heinrich Klaasen',                'batting_hand',         'Right'),
    ('Heinrich Klaasen',                'bowling_style',        'Right-arm Spin'),
    ('Heinrich Klaasen',                'role',                 'Wicketkeeper-Batter'),
    ('Heinrich Klaasen',                'combined_matches',     '172'),
    ('Heinrich Klaasen',                'combined_runs',        '5500'),
    ('Heinrich Klaasen',                'combined_wickets',     '4'),
    ('Heinrich Klaasen',                'debut_year',           '2018'),

    ('Marco Jansen',                    'active_status',       'Active'),
    ('Marco Jansen',                    'country',              'South Africa'),
    ('Marco Jansen',                    'batting_hand',         'Right'),
    ('Marco Jansen',                    'bowling_style',        'Left-arm Pace'),
    ('Marco Jansen',                    'role',                 'All-rounder'),
    ('Marco Jansen',                    'combined_matches',     '125'),
    ('Marco Jansen',                    'combined_runs',        '1800'),
    ('Marco Jansen',                    'combined_wickets',     '215'),
    ('Marco Jansen',                    'debut_year',           '2021'),

    ('Keshav Maharaj',                  'active_status',       'Active'),
    ('Keshav Maharaj',                  'country',              'South Africa'),
    ('Keshav Maharaj',                  'batting_hand',         'Right'),
    ('Keshav Maharaj',                  'bowling_style',        'Left-arm Spin'),
    ('Keshav Maharaj',                  'role',                 'Bowler'),
    ('Keshav Maharaj',                  'combined_matches',     '170'),
    ('Keshav Maharaj',                  'combined_runs',        '1500'),
    ('Keshav Maharaj',                  'combined_wickets',     '365'),
    ('Keshav Maharaj',                  'debut_year',           '2016'),

    ('Kusal Mendis',                    'active_status',       'Active'),
    ('Kusal Mendis',                    'country',              'Sri Lanka'),
    ('Kusal Mendis',                    'batting_hand',         'Right'),
    ('Kusal Mendis',                    'bowling_style',        'Hasn''t Bowled'),
    ('Kusal Mendis',                    'role',                 'Wicketkeeper-Batter'),
    ('Kusal Mendis',                    'combined_matches',     '333'),
    ('Kusal Mendis',                    'combined_runs',        '12269'),
    ('Kusal Mendis',                    'combined_wickets',     '0'),
    ('Kusal Mendis',                    'debut_year',           '2015'),

    ('Charith Asalanka',                'active_status',       'Active'),
    ('Charith Asalanka',                'country',              'Sri Lanka'),
    ('Charith Asalanka',                'batting_hand',         'Left'),
    ('Charith Asalanka',                'bowling_style',        'Right-arm Spin'),
    ('Charith Asalanka',                'role',                 'Batting All-rounder'),
    ('Charith Asalanka',                'combined_matches',     '164'),
    ('Charith Asalanka',                'combined_runs',        '4323'),
    ('Charith Asalanka',                'combined_wickets',     '38'),
    ('Charith Asalanka',                'debut_year',           '2021'),

    ('Maheesh Theekshana',              'active_status',       'Active'),
    ('Maheesh Theekshana',              'country',              'Sri Lanka'),
    ('Maheesh Theekshana',              'batting_hand',         'Right'),
    ('Maheesh Theekshana',              'bowling_style',        'Right-arm Spin'),
    ('Maheesh Theekshana',              'role',                 'Bowler'),
    ('Maheesh Theekshana',              'combined_matches',     '129'),
    ('Maheesh Theekshana',              'combined_runs',        '275'),
    ('Maheesh Theekshana',              'combined_wickets',     '154'),
    ('Maheesh Theekshana',              'debut_year',           '2021'),

    ('Najmul Hossain Shanto',           'active_status',       'Active'),
    ('Najmul Hossain Shanto',           'country',              'Bangladesh'),
    ('Najmul Hossain Shanto',           'batting_hand',         'Left'),
    ('Najmul Hossain Shanto',           'bowling_style',        'Right-arm Spin'),
    ('Najmul Hossain Shanto',           'role',                 'Batter'),
    ('Najmul Hossain Shanto',           'combined_matches',     '185'),
    ('Najmul Hossain Shanto',           'combined_runs',        '5800'),
    ('Najmul Hossain Shanto',           'combined_wickets',     '6'),
    ('Najmul Hossain Shanto',           'debut_year',           '2017'),

    ('Taskin Ahmed',                    'active_status',       'Active'),
    ('Taskin Ahmed',                    'country',              'Bangladesh'),
    ('Taskin Ahmed',                    'batting_hand',         'Left'),
    ('Taskin Ahmed',                    'bowling_style',        'Right-arm Pace'),
    ('Taskin Ahmed',                    'role',                 'Bowler'),
    ('Taskin Ahmed',                    'combined_matches',     '235'),
    ('Taskin Ahmed',                    'combined_runs',        '1800'),
    ('Taskin Ahmed',                    'combined_wickets',     '375'),
    ('Taskin Ahmed',                    'debut_year',           '2014'),

    ('Rahmanullah Gurbaz',              'active_status',       'Active'),
    ('Rahmanullah Gurbaz',              'country',              'Afghanistan'),
    ('Rahmanullah Gurbaz',              'batting_hand',         'Right'),
    ('Rahmanullah Gurbaz',              'bowling_style',        'Hasn''t Bowled'),
    ('Rahmanullah Gurbaz',              'role',                 'Wicketkeeper-Batter'),
    ('Rahmanullah Gurbaz',              'combined_matches',     '141'),
    ('Rahmanullah Gurbaz',              'combined_runs',        '4267'),
    ('Rahmanullah Gurbaz',              'combined_wickets',     '0'),
    ('Rahmanullah Gurbaz',              'debut_year',           '2019'),

    ('Sean Williams',                   'active_status',       'Retired'),
    ('Sean Williams',                   'country',              'Zimbabwe'),
    ('Sean Williams',                   'batting_hand',         'Left'),
    ('Sean Williams',                   'bowling_style',        'Left-arm Spin'),
    ('Sean Williams',                   'role',                 'All-rounder'),
    ('Sean Williams',                   'combined_matches',     '273'),
    ('Sean Williams',                   'combined_runs',        '8968'),
    ('Sean Williams',                   'combined_wickets',     '155'),
    ('Sean Williams',                   'debut_year',           '2005')
) AS v("PlayerName", "AttrKey", "Value")
JOIN "Players" p ON p."Name" = v."PlayerName"
JOIN "AttributeDefinitions" ad ON ad."Key" = v."AttrKey" AND ad."SportId" = p."SportId"
ON CONFLICT ("PlayerId", "AttributeDefinitionId") DO UPDATE SET
    "Value" = EXCLUDED."Value"
WHERE "PlayerAttributeValues"."IsManuallyEdited" = false;
