-- Men's International Cricket players, batch 2 (30 players, bringing the
-- roster to 60 total: batch 1's 30 + batch 2's 30). Same upsert pattern as
-- batch 1: Players upserts on the unique Name constraint,
-- PlayerAttributeValues upserts on the existing unique (PlayerId,
-- AttributeDefinitionId) constraint, both scoped to the
-- "cricket-men-international" Sport. No overrides in this batch -- every
-- row is IsOverridden = false, DifficultyOverride = NULL.

INSERT INTO "Players" ("SportId", "Name", "IsOverridden", "DifficultyOverride")
SELECT s."Id", v."Name", v."IsOverridden", v."DifficultyOverride"
FROM "Sports" s
CROSS JOIN (VALUES
    ('Andy Flower',              false, NULL),
    ('Sanath Jayasuriya',        false, NULL),
    ('Garfield Sobers',          false, NULL),
    ('Curtly Ambrose',           false, NULL),
    ('Courtney Walsh',           false, NULL),
    ('Chris Gayle',              false, NULL),
    ('Adam Gilchrist',           false, NULL),
    ('Steve Waugh',              false, NULL),
    ('Allan Border',             false, NULL),
    ('Virender Sehwag',          false, NULL),
    ('Anil Kumble',              false, NULL),
    ('Alastair Cook',            false, NULL),
    ('James Anderson',           false, NULL),
    ('Shahid Afridi',            false, NULL),
    ('Younis Khan',              false, NULL),
    ('Mahela Jayawardene',       false, NULL),
    ('Richard Hadlee',           false, NULL),
    ('Brendon McCullum',         false, NULL),
    ('Hashim Amla',              false, NULL),
    ('Dale Steyn',               false, NULL),
    ('Herschelle Gibbs',         false, NULL),
    ('Graeme Smith',             false, NULL),
    ('Chris Cairns',             false, NULL),
    ('Daniel Vettori',           false, NULL),
    ('Misbah-ul-Haq',            false, NULL),
    ('Mohammad Yousuf',          false, NULL),
    ('Rohit Sharma',             false, NULL),
    ('Jasprit Bumrah',           false, NULL),
    ('Mitchell Johnson',         false, NULL),
    ('Michael Clarke',           false, NULL)
) AS v("Name", "IsOverridden", "DifficultyOverride")
WHERE s."Slug" = 'cricket-men-international'
ON CONFLICT ("Name") DO UPDATE SET
    "SportId" = EXCLUDED."SportId",
    "IsOverridden" = CASE WHEN "Players"."IsOverridden" THEN "Players"."IsOverridden" ELSE EXCLUDED."IsOverridden" END,
    "DifficultyOverride" = CASE WHEN "Players"."IsOverridden" THEN "Players"."DifficultyOverride" ELSE EXCLUDED."DifficultyOverride" END;

-- One row per (player, attribute) pair. PlayerId/AttributeDefinitionId are
-- resolved by name/key lookup (scoped to each player's own SportId), so
-- this file has no dependency on insertion order or id values, and can
-- never cross-attach to cricket-women-international's AttributeDefinitions.
INSERT INTO "PlayerAttributeValues" ("PlayerId", "AttributeDefinitionId", "Value")
SELECT p."Id", ad."Id", v."Value"
FROM (VALUES
    -- Player,                       AttrKey,               Value
    ('Andy Flower',                  'active_status',       'Retired'),
    ('Andy Flower',                  'country',              'Zimbabwe'),
    ('Andy Flower',                  'batting_hand',         'Left'),
    ('Andy Flower',                  'bowling_style',        'Right-arm Spin'),
    ('Andy Flower',                  'role',                 'Wicketkeeper-Batter'),
    ('Andy Flower',                  'combined_matches',     '276'),
    ('Andy Flower',                  'combined_runs',        '11580'),
    ('Andy Flower',                  'combined_wickets',     '0'),
    ('Andy Flower',                  'debut_year',           '1992'),

    ('Sanath Jayasuriya',            'active_status',       'Retired'),
    ('Sanath Jayasuriya',            'country',              'Sri Lanka'),
    ('Sanath Jayasuriya',            'batting_hand',         'Left'),
    ('Sanath Jayasuriya',            'bowling_style',        'Left-arm Spin'),
    ('Sanath Jayasuriya',            'role',                 'Batting All-rounder'),
    ('Sanath Jayasuriya',            'combined_matches',     '586'),
    ('Sanath Jayasuriya',            'combined_runs',        '21032'),
    ('Sanath Jayasuriya',            'combined_wickets',     '440'),
    ('Sanath Jayasuriya',            'debut_year',           '1989'),

    ('Garfield Sobers',              'active_status',       'Retired'),
    ('Garfield Sobers',              'country',              'West Indies'),
    ('Garfield Sobers',              'batting_hand',         'Left'),
    ('Garfield Sobers',              'bowling_style',        'Left-arm Pace'),
    ('Garfield Sobers',              'role',                 'All-rounder'),
    ('Garfield Sobers',              'combined_matches',     '94'),
    ('Garfield Sobers',              'combined_runs',        '8032'),
    ('Garfield Sobers',              'combined_wickets',     '235'),
    ('Garfield Sobers',              'debut_year',           '1954'),

    ('Curtly Ambrose',               'active_status',       'Retired'),
    ('Curtly Ambrose',               'country',              'West Indies'),
    ('Curtly Ambrose',               'batting_hand',         'Left'),
    ('Curtly Ambrose',               'bowling_style',        'Right-arm Pace'),
    ('Curtly Ambrose',               'role',                 'Bowler'),
    ('Curtly Ambrose',               'combined_matches',     '274'),
    ('Curtly Ambrose',               'combined_runs',        '1500'),
    ('Curtly Ambrose',               'combined_wickets',     '630'),
    ('Curtly Ambrose',               'debut_year',           '1988'),

    ('Courtney Walsh',               'active_status',       'Retired'),
    ('Courtney Walsh',               'country',              'West Indies'),
    ('Courtney Walsh',               'batting_hand',         'Right'),
    ('Courtney Walsh',               'bowling_style',        'Right-arm Pace'),
    ('Courtney Walsh',               'role',                 'Bowler'),
    ('Courtney Walsh',               'combined_matches',     '337'),
    ('Courtney Walsh',               'combined_runs',        '1900'),
    ('Courtney Walsh',               'combined_wickets',     '746'),
    ('Courtney Walsh',               'debut_year',           '1984'),

    ('Chris Gayle',                  'active_status',       'Retired'),
    ('Chris Gayle',                  'country',              'West Indies'),
    ('Chris Gayle',                  'batting_hand',         'Left'),
    ('Chris Gayle',                  'bowling_style',        'Right-arm Spin'),
    ('Chris Gayle',                  'role',                 'Batter'),
    ('Chris Gayle',                  'combined_matches',     '483'),
    ('Chris Gayle',                  'combined_runs',        '19593'),
    ('Chris Gayle',                  'combined_wickets',     '200'),
    ('Chris Gayle',                  'debut_year',           '1999'),

    ('Adam Gilchrist',               'active_status',       'Retired'),
    ('Adam Gilchrist',               'country',              'Australia'),
    ('Adam Gilchrist',               'batting_hand',         'Left'),
    ('Adam Gilchrist',               'bowling_style',        'Hasn''t Bowled'),
    ('Adam Gilchrist',               'role',                 'Wicketkeeper-Batter'),
    ('Adam Gilchrist',               'combined_matches',     '396'),
    ('Adam Gilchrist',               'combined_runs',        '15389'),
    ('Adam Gilchrist',               'combined_wickets',     '0'),
    ('Adam Gilchrist',               'debut_year',           '1996'),

    ('Steve Waugh',                  'active_status',       'Retired'),
    ('Steve Waugh',                  'country',              'Australia'),
    ('Steve Waugh',                  'batting_hand',         'Right'),
    ('Steve Waugh',                  'bowling_style',        'Right-arm Pace'),
    ('Steve Waugh',                  'role',                 'Batting All-rounder'),
    ('Steve Waugh',                  'combined_matches',     '493'),
    ('Steve Waugh',                  'combined_runs',        '18496'),
    ('Steve Waugh',                  'combined_wickets',     '287'),
    ('Steve Waugh',                  'debut_year',           '1985'),

    ('Allan Border',                 'active_status',       'Retired'),
    ('Allan Border',                 'country',              'Australia'),
    ('Allan Border',                 'batting_hand',         'Left'),
    ('Allan Border',                 'bowling_style',        'Left-arm Spin'),
    ('Allan Border',                 'role',                 'Batter'),
    ('Allan Border',                 'combined_matches',     '429'),
    ('Allan Border',                 'combined_runs',        '17698'),
    ('Allan Border',                 'combined_wickets',     '112'),
    ('Allan Border',                 'debut_year',           '1978'),

    ('Virender Sehwag',              'active_status',       'Retired'),
    ('Virender Sehwag',              'country',              'India'),
    ('Virender Sehwag',              'batting_hand',         'Right'),
    ('Virender Sehwag',              'bowling_style',        'Right-arm Spin'),
    ('Virender Sehwag',              'role',                 'Batter'),
    ('Virender Sehwag',              'combined_matches',     '374'),
    ('Virender Sehwag',              'combined_runs',        '17253'),
    ('Virender Sehwag',              'combined_wickets',     '139'),
    ('Virender Sehwag',              'debut_year',           '1999'),

    ('Anil Kumble',                  'active_status',       'Retired'),
    ('Anil Kumble',                  'country',              'India'),
    ('Anil Kumble',                  'batting_hand',         'Right'),
    ('Anil Kumble',                  'bowling_style',        'Right-arm Spin'),
    ('Anil Kumble',                  'role',                 'Bowler'),
    ('Anil Kumble',                  'combined_matches',     '403'),
    ('Anil Kumble',                  'combined_runs',        '3700'),
    ('Anil Kumble',                  'combined_wickets',     '956'),
    ('Anil Kumble',                  'debut_year',           '1990'),

    ('Alastair Cook',                'active_status',       'Retired'),
    ('Alastair Cook',                'country',              'England'),
    ('Alastair Cook',                'batting_hand',         'Left'),
    ('Alastair Cook',                'bowling_style',        'Right-arm Pace'),
    ('Alastair Cook',                'role',                 'Batter'),
    ('Alastair Cook',                'combined_matches',     '253'),
    ('Alastair Cook',                'combined_runs',        '15676'),
    ('Alastair Cook',                'combined_wickets',     '1'),
    ('Alastair Cook',                'debut_year',           '2006'),

    ('James Anderson',               'active_status',       'Retired'),
    ('James Anderson',               'country',              'England'),
    ('James Anderson',               'batting_hand',         'Right'),
    ('James Anderson',               'bowling_style',        'Right-arm Pace'),
    ('James Anderson',               'role',                 'Bowler'),
    ('James Anderson',               'combined_matches',     '382'),
    ('James Anderson',               'combined_runs',        '1800'),
    ('James Anderson',               'combined_wickets',     '973'),
    ('James Anderson',               'debut_year',           '2002'),

    ('Shahid Afridi',                'active_status',       'Retired'),
    ('Shahid Afridi',                'country',              'Pakistan'),
    ('Shahid Afridi',                'batting_hand',         'Right'),
    ('Shahid Afridi',                'bowling_style',        'Right-arm Spin'),
    ('Shahid Afridi',                'role',                 'All-rounder'),
    ('Shahid Afridi',                'combined_matches',     '524'),
    ('Shahid Afridi',                'combined_runs',        '11196'),
    ('Shahid Afridi',                'combined_wickets',     '541'),
    ('Shahid Afridi',                'debut_year',           '1996'),

    ('Younis Khan',                  'active_status',       'Retired'),
    ('Younis Khan',                  'country',              'Pakistan'),
    ('Younis Khan',                  'batting_hand',         'Right'),
    ('Younis Khan',                  'bowling_style',        'Right-arm Pace'),
    ('Younis Khan',                  'role',                 'Batter'),
    ('Younis Khan',                  'combined_matches',     '408'),
    ('Younis Khan',                  'combined_runs',        '17662'),
    ('Younis Khan',                  'combined_wickets',     '5'),
    ('Younis Khan',                  'debut_year',           '2000'),

    ('Mahela Jayawardene',           'active_status',       'Retired'),
    ('Mahela Jayawardene',           'country',              'Sri Lanka'),
    ('Mahela Jayawardene',           'batting_hand',         'Right'),
    ('Mahela Jayawardene',           'bowling_style',        'Right-arm Pace'),
    ('Mahela Jayawardene',           'role',                 'Batter'),
    ('Mahela Jayawardene',           'combined_matches',     '652'),
    ('Mahela Jayawardene',           'combined_runs',        '25957'),
    ('Mahela Jayawardene',           'combined_wickets',     '18'),
    ('Mahela Jayawardene',           'debut_year',           '1997'),

    ('Richard Hadlee',               'active_status',       'Retired'),
    ('Richard Hadlee',               'country',              'New Zealand'),
    ('Richard Hadlee',               'batting_hand',         'Right'),
    ('Richard Hadlee',               'bowling_style',        'Right-arm Pace'),
    ('Richard Hadlee',               'role',                 'Bowler'),
    ('Richard Hadlee',               'combined_matches',     '201'),
    ('Richard Hadlee',               'combined_runs',        '4875'),
    ('Richard Hadlee',               'combined_wickets',     '589'),
    ('Richard Hadlee',               'debut_year',           '1973'),

    ('Brendon McCullum',             'active_status',       'Retired'),
    ('Brendon McCullum',             'country',              'New Zealand'),
    ('Brendon McCullum',             'batting_hand',         'Right'),
    ('Brendon McCullum',             'bowling_style',        'Right-arm Pace'),
    ('Brendon McCullum',             'role',                 'Wicketkeeper-Batter'),
    ('Brendon McCullum',             'combined_matches',     '432'),
    ('Brendon McCullum',             'combined_runs',        '14676'),
    ('Brendon McCullum',             'combined_wickets',     '2'),
    ('Brendon McCullum',             'debut_year',           '2002'),

    ('Hashim Amla',                  'active_status',       'Retired'),
    ('Hashim Amla',                  'country',              'South Africa'),
    ('Hashim Amla',                  'batting_hand',         'Right'),
    ('Hashim Amla',                  'bowling_style',        'Right-arm Spin'),
    ('Hashim Amla',                  'role',                 'Batter'),
    ('Hashim Amla',                  'combined_matches',     '349'),
    ('Hashim Amla',                  'combined_runs',        '18672'),
    ('Hashim Amla',                  'combined_wickets',     '0'),
    ('Hashim Amla',                  'debut_year',           '2004'),

    ('Dale Steyn',                   'active_status',       'Retired'),
    ('Dale Steyn',                   'country',              'South Africa'),
    ('Dale Steyn',                   'batting_hand',         'Right'),
    ('Dale Steyn',                   'bowling_style',        'Right-arm Pace'),
    ('Dale Steyn',                   'role',                 'Bowler'),
    ('Dale Steyn',                   'combined_matches',     '265'),
    ('Dale Steyn',                   'combined_runs',        '1500'),
    ('Dale Steyn',                   'combined_wickets',     '699'),
    ('Dale Steyn',                   'debut_year',           '2004'),

    ('Herschelle Gibbs',              'active_status',       'Retired'),
    ('Herschelle Gibbs',              'country',              'South Africa'),
    ('Herschelle Gibbs',              'batting_hand',         'Right'),
    ('Herschelle Gibbs',              'bowling_style',        'Right-arm Pace'),
    ('Herschelle Gibbs',              'role',                 'Batter'),
    ('Herschelle Gibbs',              'combined_matches',     '361'),
    ('Herschelle Gibbs',              'combined_runs',        '14661'),
    ('Herschelle Gibbs',              'combined_wickets',     '0'),
    ('Herschelle Gibbs',              'debut_year',           '1996'),

    ('Graeme Smith',                 'active_status',       'Retired'),
    ('Graeme Smith',                 'country',              'South Africa'),
    ('Graeme Smith',                 'batting_hand',         'Left'),
    ('Graeme Smith',                 'bowling_style',        'Right-arm Spin'),
    ('Graeme Smith',                 'role',                 'Batter'),
    ('Graeme Smith',                 'combined_matches',     '335'),
    ('Graeme Smith',                 'combined_runs',        '17236'),
    ('Graeme Smith',                 'combined_wickets',     '10'),
    ('Graeme Smith',                 'debut_year',           '2002'),

    ('Chris Cairns',                 'active_status',       'Retired'),
    ('Chris Cairns',                 'country',              'New Zealand'),
    ('Chris Cairns',                 'batting_hand',         'Right'),
    ('Chris Cairns',                 'bowling_style',        'Right-arm Pace'),
    ('Chris Cairns',                 'role',                 'All-rounder'),
    ('Chris Cairns',                 'combined_matches',     '279'),
    ('Chris Cairns',                 'combined_runs',        '8270'),
    ('Chris Cairns',                 'combined_wickets',     '419'),
    ('Chris Cairns',                 'debut_year',           '1989'),

    ('Daniel Vettori',                'active_status',       'Retired'),
    ('Daniel Vettori',                'country',              'New Zealand'),
    ('Daniel Vettori',                'batting_hand',         'Left'),
    ('Daniel Vettori',                'bowling_style',        'Left-arm Spin'),
    ('Daniel Vettori',                'role',                 'All-rounder'),
    ('Daniel Vettori',                'combined_matches',     '442'),
    ('Daniel Vettori',                'combined_runs',        '6989'),
    ('Daniel Vettori',                'combined_wickets',     '705'),
    ('Daniel Vettori',                'debut_year',           '1997'),

    ('Misbah-ul-Haq',                 'active_status',       'Retired'),
    ('Misbah-ul-Haq',                 'country',              'Pakistan'),
    ('Misbah-ul-Haq',                 'batting_hand',         'Right'),
    ('Misbah-ul-Haq',                 'bowling_style',        'Right-arm Spin'),
    ('Misbah-ul-Haq',                 'role',                 'Batter'),
    ('Misbah-ul-Haq',                 'combined_matches',     '276'),
    ('Misbah-ul-Haq',                 'combined_runs',        '11026'),
    ('Misbah-ul-Haq',                 'combined_wickets',     '5'),
    ('Misbah-ul-Haq',                 'debut_year',           '2001'),

    ('Mohammad Yousuf',               'active_status',       'Retired'),
    ('Mohammad Yousuf',               'country',              'Pakistan'),
    ('Mohammad Yousuf',               'batting_hand',         'Right'),
    ('Mohammad Yousuf',               'bowling_style',        'Right-arm Pace'),
    ('Mohammad Yousuf',               'role',                 'Batter'),
    ('Mohammad Yousuf',               'combined_matches',     '381'),
    ('Mohammad Yousuf',               'combined_runs',        '17278'),
    ('Mohammad Yousuf',               'combined_wickets',     '18'),
    ('Mohammad Yousuf',               'debut_year',           '1998'),

    ('Rohit Sharma',                  'active_status',       'Active'),
    ('Rohit Sharma',                  'country',              'India'),
    ('Rohit Sharma',                  'batting_hand',         'Right'),
    ('Rohit Sharma',                  'bowling_style',        'Right-arm Spin'),
    ('Rohit Sharma',                  'role',                 'Batter'),
    ('Rohit Sharma',                  'combined_matches',     '514'),
    ('Rohit Sharma',                  'combined_runs',        '19398'),
    ('Rohit Sharma',                  'combined_wickets',     '15'),
    ('Rohit Sharma',                  'debut_year',           '2007'),

    ('Jasprit Bumrah',                'active_status',       'Active'),
    ('Jasprit Bumrah',                'country',              'India'),
    ('Jasprit Bumrah',                'batting_hand',         'Right'),
    ('Jasprit Bumrah',                'bowling_style',        'Right-arm Pace'),
    ('Jasprit Bumrah',                'role',                 'Bowler'),
    ('Jasprit Bumrah',                'combined_matches',     '212'),
    ('Jasprit Bumrah',                'combined_runs',        '440'),
    ('Jasprit Bumrah',                'combined_wickets',     '420'),
    ('Jasprit Bumrah',                'debut_year',           '2016'),

    ('Mitchell Johnson',              'active_status',       'Retired'),
    ('Mitchell Johnson',              'country',              'Australia'),
    ('Mitchell Johnson',              'batting_hand',         'Left'),
    ('Mitchell Johnson',              'bowling_style',        'Left-arm Pace'),
    ('Mitchell Johnson',              'role',                 'Bowler'),
    ('Mitchell Johnson',              'combined_matches',     '256'),
    ('Mitchell Johnson',              'combined_runs',        '1721'),
    ('Mitchell Johnson',              'combined_wickets',     '596'),
    ('Mitchell Johnson',              'debut_year',           '2007'),

    ('Michael Clarke',                'active_status',       'Retired'),
    ('Michael Clarke',                'country',              'Australia'),
    ('Michael Clarke',                'batting_hand',         'Right'),
    ('Michael Clarke',                'bowling_style',        'Right-arm Spin'),
    ('Michael Clarke',                'role',                 'Batter'),
    ('Michael Clarke',                'combined_matches',     '394'),
    ('Michael Clarke',                'combined_runs',        '17112'),
    ('Michael Clarke',                'combined_wickets',     '88'),
    ('Michael Clarke',                'debut_year',           '2003')
) AS v("PlayerName", "AttrKey", "Value")
JOIN "Players" p ON p."Name" = v."PlayerName"
JOIN "AttributeDefinitions" ad ON ad."Key" = v."AttrKey" AND ad."SportId" = p."SportId"
ON CONFLICT ("PlayerId", "AttributeDefinitionId") DO UPDATE SET
    "Value" = EXCLUDED."Value"
WHERE "PlayerAttributeValues"."IsManuallyEdited" = false;
