-- Men's International Cricket players, batch 7 (30 players, bringing the
-- roster to 210 total: batches 1-6's 180 + batch 7's 30). Same upsert
-- pattern as prior batches: Players upserts on the unique Name constraint,
-- PlayerAttributeValues upserts on the existing unique (PlayerId,
-- AttributeDefinitionId) constraint, both scoped to the
-- "cricket-men-international" Sport. No overrides in this batch -- every
-- row is IsOverridden = false, DifficultyOverride = NULL.

INSERT INTO "Players" ("SportId", "Name", "IsOverridden", "DifficultyOverride")
SELECT s."Id", v."Name", v."IsOverridden", v."DifficultyOverride"
FROM "Sports" s
CROSS JOIN (VALUES
    ('Ravi Bishnoi',              false, NULL),
    ('Tilak Varma',               false, NULL),
    ('Sanju Samson',              false, NULL),
    ('Ruturaj Gaikwad',           false, NULL),
    ('Washington Sundar',         false, NULL),
    ('Nathan Ellis',              false, NULL),
    ('Tim David',                 false, NULL),
    ('Aaron Hardie',              false, NULL),
    ('Scott Boland',              false, NULL),
    ('Jamie Overton',             false, NULL),
    ('Jofra Archer',              false, NULL),
    ('Reece Topley',              false, NULL),
    ('Will Jacks',                false, NULL),
    ('Mohammad Haris',            false, NULL),
    ('Saim Ayub',                 false, NULL),
    ('Johnson Charles',           false, NULL),
    ('Reeza Hendricks',           false, NULL),
    ('Tabraiz Shamsi',            false, NULL),
    ('Lungi Ngidi',               false, NULL),
    ('Dushmantha Chameera',       false, NULL),
    ('Mehidy Hasan Miraz',        false, NULL),
    ('Naveen-ul-Haq',             false, NULL),
    ('Azmatullah Omarzai',        false, NULL),
    ('Bas de Leede',              false, NULL),
    ('Michael Leask',             false, NULL),
    ('Muhammad Waseem',           false, NULL),
    ('Aaron Jones',               false, NULL),
    ('Sandeep Lamichhane',        false, NULL),
    ('Wessly Madhevere',          false, NULL),
    ('Curtis Campher',            false, NULL)
) AS v("Name", "IsOverridden", "DifficultyOverride")
WHERE s."Slug" = 'cricket-men-international'
ON CONFLICT ("Name") DO UPDATE SET
    "SportId" = EXCLUDED."SportId",
    "IsOverridden" = CASE WHEN "Players"."IsOverridden" THEN "Players"."IsOverridden" ELSE EXCLUDED."IsOverridden" END,
    "DifficultyOverride" = CASE WHEN "Players"."IsOverridden" THEN "Players"."DifficultyOverride" ELSE EXCLUDED."DifficultyOverride" END;

-- One row per (player, attribute) pair. PlayerId/AttributeDefinitionId are
-- resolved by name/key lookup (scoped to each player's own SportId), so
-- this file has no dependency on insertion order or id values, and can
-- never cross-attach to cricket-women-international's AttributeDefinitions.
INSERT INTO "PlayerAttributeValues" ("PlayerId", "AttributeDefinitionId", "Value")
SELECT p."Id", ad."Id", v."Value"
FROM (VALUES
    -- Player,                          AttrKey,               Value
    ('Ravi Bishnoi',                    'active_status',       'Active'),
    ('Ravi Bishnoi',                    'country',              'India'),
    ('Ravi Bishnoi',                    'batting_hand',         'Right'),
    ('Ravi Bishnoi',                    'bowling_style',        'Right-arm Spin'),
    ('Ravi Bishnoi',                    'role',                 'Bowler'),
    ('Ravi Bishnoi',                    'combined_matches',     '71'),
    ('Ravi Bishnoi',                    'combined_runs',        '180'),
    ('Ravi Bishnoi',                    'combined_wickets',     '86'),
    ('Ravi Bishnoi',                    'debut_year',           '2022'),

    ('Tilak Varma',                     'active_status',       'Active'),
    ('Tilak Varma',                     'country',              'India'),
    ('Tilak Varma',                     'batting_hand',         'Left'),
    ('Tilak Varma',                     'bowling_style',        'Right-arm Spin'),
    ('Tilak Varma',                     'role',                 'Batting All-rounder'),
    ('Tilak Varma',                     'combined_matches',     '80'),
    ('Tilak Varma',                     'combined_runs',        '2800'),
    ('Tilak Varma',                     'combined_wickets',     '5'),
    ('Tilak Varma',                     'debut_year',           '2023'),

    ('Sanju Samson',                    'active_status',       'Active'),
    ('Sanju Samson',                    'country',              'India'),
    ('Sanju Samson',                    'batting_hand',         'Right'),
    ('Sanju Samson',                    'bowling_style',        'Hasn''t Bowled'),
    ('Sanju Samson',                    'role',                 'Wicketkeeper-Batter'),
    ('Sanju Samson',                    'combined_matches',     '80'),
    ('Sanju Samson',                    'combined_runs',        '2200'),
    ('Sanju Samson',                    'combined_wickets',     '0'),
    ('Sanju Samson',                    'debut_year',           '2015'),

    ('Ruturaj Gaikwad',                 'active_status',       'Active'),
    ('Ruturaj Gaikwad',                 'country',              'India'),
    ('Ruturaj Gaikwad',                 'batting_hand',         'Right'),
    ('Ruturaj Gaikwad',                 'bowling_style',        'Right-arm Spin'),
    ('Ruturaj Gaikwad',                 'role',                 'Batter'),
    ('Ruturaj Gaikwad',                 'combined_matches',     '60'),
    ('Ruturaj Gaikwad',                 'combined_runs',        '2000'),
    ('Ruturaj Gaikwad',                 'combined_wickets',     '4'),
    ('Ruturaj Gaikwad',                 'debut_year',           '2021'),

    ('Washington Sundar',                'active_status',       'Active'),
    ('Washington Sundar',                'country',              'India'),
    ('Washington Sundar',                'batting_hand',         'Left'),
    ('Washington Sundar',                'bowling_style',        'Right-arm Spin'),
    ('Washington Sundar',                'role',                 'Bowling All-rounder'),
    ('Washington Sundar',                'combined_matches',     '110'),
    ('Washington Sundar',                'combined_runs',        '1800'),
    ('Washington Sundar',                'combined_wickets',     '155'),
    ('Washington Sundar',                'debut_year',           '2017'),

    ('Nathan Ellis',                    'active_status',       'Active'),
    ('Nathan Ellis',                    'country',              'Australia'),
    ('Nathan Ellis',                    'batting_hand',         'Right'),
    ('Nathan Ellis',                    'bowling_style',        'Right-arm Pace'),
    ('Nathan Ellis',                    'role',                 'Bowler'),
    ('Nathan Ellis',                    'combined_matches',     '80'),
    ('Nathan Ellis',                    'combined_runs',        '175'),
    ('Nathan Ellis',                    'combined_wickets',     '105'),
    ('Nathan Ellis',                    'debut_year',           '2021'),

    ('Tim David',                       'active_status',       'Active'),
    ('Tim David',                       'country',              'Australia'),
    ('Tim David',                       'batting_hand',         'Right'),
    ('Tim David',                       'bowling_style',        'Right-arm Spin'),
    ('Tim David',                       'role',                 'Batter'),
    ('Tim David',                       'combined_matches',     '82'),
    ('Tim David',                       'combined_runs',        '1800'),
    ('Tim David',                       'combined_wickets',     '6'),
    ('Tim David',                       'debut_year',           '2019'),

    ('Aaron Hardie',                    'active_status',       'Retired'),
    ('Aaron Hardie',                    'country',              'Australia'),
    ('Aaron Hardie',                    'batting_hand',         'Right'),
    ('Aaron Hardie',                    'bowling_style',        'Right-arm Pace'),
    ('Aaron Hardie',                    'role',                 'All-rounder'),
    ('Aaron Hardie',                    'combined_matches',     '55'),
    ('Aaron Hardie',                    'combined_runs',        '900'),
    ('Aaron Hardie',                    'combined_wickets',     '35'),
    ('Aaron Hardie',                    'debut_year',           '2023'),

    ('Scott Boland',                    'active_status',       'Active'),
    ('Scott Boland',                    'country',              'Australia'),
    ('Scott Boland',                    'batting_hand',         'Right'),
    ('Scott Boland',                    'bowling_style',        'Right-arm Pace'),
    ('Scott Boland',                    'role',                 'Bowler'),
    ('Scott Boland',                    'combined_matches',     '36'),
    ('Scott Boland',                    'combined_runs',        '280'),
    ('Scott Boland',                    'combined_wickets',     '101'),
    ('Scott Boland',                    'debut_year',           '2016'),

    ('Jamie Overton',                   'active_status',       'Active'),
    ('Jamie Overton',                   'country',              'England'),
    ('Jamie Overton',                   'batting_hand',         'Right'),
    ('Jamie Overton',                   'bowling_style',        'Right-arm Pace'),
    ('Jamie Overton',                   'role',                 'All-rounder'),
    ('Jamie Overton',                   'combined_matches',     '33'),
    ('Jamie Overton',                   'combined_runs',        '600'),
    ('Jamie Overton',                   'combined_wickets',     '47'),
    ('Jamie Overton',                   'debut_year',           '2022'),

    ('Jofra Archer',                    'active_status',       'Active'),
    ('Jofra Archer',                    'country',              'England'),
    ('Jofra Archer',                    'batting_hand',         'Right'),
    ('Jofra Archer',                    'bowling_style',        'Right-arm Pace'),
    ('Jofra Archer',                    'role',                 'Bowler'),
    ('Jofra Archer',                    'combined_matches',     '65'),
    ('Jofra Archer',                    'combined_runs',        '450'),
    ('Jofra Archer',                    'combined_wickets',     '125'),
    ('Jofra Archer',                    'debut_year',           '2019'),

    ('Reece Topley',                    'active_status',       'Active'),
    ('Reece Topley',                    'country',              'England'),
    ('Reece Topley',                    'batting_hand',         'Right'),
    ('Reece Topley',                    'bowling_style',        'Left-arm Pace'),
    ('Reece Topley',                    'role',                 'Bowler'),
    ('Reece Topley',                    'combined_matches',     '55'),
    ('Reece Topley',                    'combined_runs',        '125'),
    ('Reece Topley',                    'combined_wickets',     '80'),
    ('Reece Topley',                    'debut_year',           '2015'),

    ('Will Jacks',                      'active_status',       'Active'),
    ('Will Jacks',                      'country',              'England'),
    ('Will Jacks',                      'batting_hand',         'Right'),
    ('Will Jacks',                      'bowling_style',        'Right-arm Spin'),
    ('Will Jacks',                      'role',                 'Batting All-rounder'),
    ('Will Jacks',                      'combined_matches',     '73'),
    ('Will Jacks',                      'combined_runs',        '1800'),
    ('Will Jacks',                      'combined_wickets',     '60'),
    ('Will Jacks',                      'debut_year',           '2022'),

    ('Mohammad Haris',                  'active_status',       'Active'),
    ('Mohammad Haris',                  'country',              'Pakistan'),
    ('Mohammad Haris',                  'batting_hand',         'Right'),
    ('Mohammad Haris',                  'bowling_style',        'Right-arm Spin'),
    ('Mohammad Haris',                  'role',                 'Wicketkeeper-Batter'),
    ('Mohammad Haris',                  'combined_matches',     '50'),
    ('Mohammad Haris',                  'combined_runs',        '1200'),
    ('Mohammad Haris',                  'combined_wickets',     '0'),
    ('Mohammad Haris',                  'debut_year',           '2022'),

    ('Saim Ayub',                       'active_status',       'Active'),
    ('Saim Ayub',                       'country',              'Pakistan'),
    ('Saim Ayub',                       'batting_hand',         'Left'),
    ('Saim Ayub',                       'bowling_style',        'Right-arm Spin'),
    ('Saim Ayub',                       'role',                 'All-rounder'),
    ('Saim Ayub',                       'combined_matches',     '72'),
    ('Saim Ayub',                       'combined_runs',        '2200'),
    ('Saim Ayub',                       'combined_wickets',     '25'),
    ('Saim Ayub',                       'debut_year',           '2023'),

    ('Johnson Charles',                 'active_status',       'Active'),
    ('Johnson Charles',                 'country',              'West Indies'),
    ('Johnson Charles',                 'batting_hand',         'Right'),
    ('Johnson Charles',                 'bowling_style',        'Hasn''t Bowled'),
    ('Johnson Charles',                 'role',                 'Wicketkeeper-Batter'),
    ('Johnson Charles',                 'combined_matches',     '122'),
    ('Johnson Charles',                 'combined_runs',        '3005'),
    ('Johnson Charles',                 'combined_wickets',     '0'),
    ('Johnson Charles',                 'debut_year',           '2011'),

    ('Reeza Hendricks',                 'active_status',       'Active'),
    ('Reeza Hendricks',                 'country',              'South Africa'),
    ('Reeza Hendricks',                 'batting_hand',         'Right'),
    ('Reeza Hendricks',                 'bowling_style',        'Right-arm Spin'),
    ('Reeza Hendricks',                 'role',                 'Batter'),
    ('Reeza Hendricks',                 'combined_matches',     '140'),
    ('Reeza Hendricks',                 'combined_runs',        '4200'),
    ('Reeza Hendricks',                 'combined_wickets',     '7'),
    ('Reeza Hendricks',                 'debut_year',           '2014'),

    ('Tabraiz Shamsi',                  'active_status',       'Active'),
    ('Tabraiz Shamsi',                  'country',              'South Africa'),
    ('Tabraiz Shamsi',                  'batting_hand',         'Right'),
    ('Tabraiz Shamsi',                  'bowling_style',        'Left-arm Spin'),
    ('Tabraiz Shamsi',                  'role',                 'Bowler'),
    ('Tabraiz Shamsi',                  'combined_matches',     '144'),
    ('Tabraiz Shamsi',                  'combined_runs',        '250'),
    ('Tabraiz Shamsi',                  'combined_wickets',     '228'),
    ('Tabraiz Shamsi',                  'debut_year',           '2016'),

    ('Lungi Ngidi',                     'active_status',       'Active'),
    ('Lungi Ngidi',                     'country',              'South Africa'),
    ('Lungi Ngidi',                     'batting_hand',         'Right'),
    ('Lungi Ngidi',                     'bowling_style',        'Right-arm Pace'),
    ('Lungi Ngidi',                     'role',                 'Bowler'),
    ('Lungi Ngidi',                     'combined_matches',     '155'),
    ('Lungi Ngidi',                     'combined_runs',        '650'),
    ('Lungi Ngidi',                     'combined_wickets',     '285'),
    ('Lungi Ngidi',                     'debut_year',           '2017'),

    ('Dushmantha Chameera',             'active_status',       'Active'),
    ('Dushmantha Chameera',             'country',              'Sri Lanka'),
    ('Dushmantha Chameera',             'batting_hand',         'Right'),
    ('Dushmantha Chameera',             'bowling_style',        'Right-arm Pace'),
    ('Dushmantha Chameera',             'role',                 'Bowling All-rounder'),
    ('Dushmantha Chameera',             'combined_matches',     '160'),
    ('Dushmantha Chameera',             'combined_runs',        '450'),
    ('Dushmantha Chameera',             'combined_wickets',     '260'),
    ('Dushmantha Chameera',             'debut_year',           '2015'),

    ('Mehidy Hasan Miraz',              'active_status',       'Active'),
    ('Mehidy Hasan Miraz',              'country',              'Bangladesh'),
    ('Mehidy Hasan Miraz',              'batting_hand',         'Right'),
    ('Mehidy Hasan Miraz',              'bowling_style',        'Right-arm Spin'),
    ('Mehidy Hasan Miraz',              'role',                 'All-rounder'),
    ('Mehidy Hasan Miraz',              'combined_matches',     '255'),
    ('Mehidy Hasan Miraz',              'combined_runs',        '4500'),
    ('Mehidy Hasan Miraz',              'combined_wickets',     '430'),
    ('Mehidy Hasan Miraz',              'debut_year',           '2016'),

    ('Naveen-ul-Haq',                   'active_status',       'Active'),
    ('Naveen-ul-Haq',                   'country',              'Afghanistan'),
    ('Naveen-ul-Haq',                   'batting_hand',         'Right'),
    ('Naveen-ul-Haq',                   'bowling_style',        'Right-arm Pace'),
    ('Naveen-ul-Haq',                   'role',                 'Bowler'),
    ('Naveen-ul-Haq',                   'combined_matches',     '120'),
    ('Naveen-ul-Haq',                   'combined_runs',        '450'),
    ('Naveen-ul-Haq',                   'combined_wickets',     '160'),
    ('Naveen-ul-Haq',                   'debut_year',           '2016'),

    ('Azmatullah Omarzai',              'active_status',       'Active'),
    ('Azmatullah Omarzai',              'country',              'Afghanistan'),
    ('Azmatullah Omarzai',              'batting_hand',         'Right'),
    ('Azmatullah Omarzai',              'bowling_style',        'Right-arm Pace'),
    ('Azmatullah Omarzai',              'role',                 'All-rounder'),
    ('Azmatullah Omarzai',              'combined_matches',     '106'),
    ('Azmatullah Omarzai',              'combined_runs',        '1700'),
    ('Azmatullah Omarzai',              'combined_wickets',     '116'),
    ('Azmatullah Omarzai',              'debut_year',           '2021'),

    ('Bas de Leede',                    'active_status',       'Active'),
    ('Bas de Leede',                    'country',              'Netherlands'),
    ('Bas de Leede',                    'batting_hand',         'Right'),
    ('Bas de Leede',                    'bowling_style',        'Right-arm Pace'),
    ('Bas de Leede',                    'role',                 'All-rounder'),
    ('Bas de Leede',                    'combined_matches',     '125'),
    ('Bas de Leede',                    'combined_runs',        '2800'),
    ('Bas de Leede',                    'combined_wickets',     '145'),
    ('Bas de Leede',                    'debut_year',           '2018'),

    ('Michael Leask',                   'active_status',       'Active'),
    ('Michael Leask',                   'country',              'Scotland'),
    ('Michael Leask',                   'batting_hand',         'Right'),
    ('Michael Leask',                   'bowling_style',        'Right-arm Spin'),
    ('Michael Leask',                   'role',                 'Batter'),
    ('Michael Leask',                   'combined_matches',     '140'),
    ('Michael Leask',                   'combined_runs',        '2200'),
    ('Michael Leask',                   'combined_wickets',     '60'),
    ('Michael Leask',                   'debut_year',           '2013'),

    ('Muhammad Waseem',                 'active_status',       'Active'),
    ('Muhammad Waseem',                 'country',              'UAE'),
    ('Muhammad Waseem',                 'batting_hand',         'Right'),
    ('Muhammad Waseem',                 'bowling_style',        'Right-arm Pace'),
    ('Muhammad Waseem',                 'role',                 'Batter'),
    ('Muhammad Waseem',                 'combined_matches',     '130'),
    ('Muhammad Waseem',                 'combined_runs',        '3200'),
    ('Muhammad Waseem',                 'combined_wickets',     '7'),
    ('Muhammad Waseem',                 'debut_year',           '2021'),

    ('Aaron Jones',                     'active_status',       'Active'),
    ('Aaron Jones',                     'country',              'USA'),
    ('Aaron Jones',                     'batting_hand',         'Right'),
    ('Aaron Jones',                     'bowling_style',        'Right-arm Spin'),
    ('Aaron Jones',                     'role',                 'Batter'),
    ('Aaron Jones',                     'combined_matches',     '80'),
    ('Aaron Jones',                     'combined_runs',        '2200'),
    ('Aaron Jones',                     'combined_wickets',     '12'),
    ('Aaron Jones',                     'debut_year',           '2019'),

    ('Sandeep Lamichhane',              'active_status',       'Active'),
    ('Sandeep Lamichhane',              'country',              'Nepal'),
    ('Sandeep Lamichhane',              'batting_hand',         'Right'),
    ('Sandeep Lamichhane',              'bowling_style',        'Right-arm Spin'),
    ('Sandeep Lamichhane',              'role',                 'Bowler'),
    ('Sandeep Lamichhane',              'combined_matches',     '165'),
    ('Sandeep Lamichhane',              'combined_runs',        '450'),
    ('Sandeep Lamichhane',              'combined_wickets',     '245'),
    ('Sandeep Lamichhane',              'debut_year',           '2018'),

    ('Wessly Madhevere',                'active_status',       'Active'),
    ('Wessly Madhevere',                'country',              'Zimbabwe'),
    ('Wessly Madhevere',                'batting_hand',         'Right'),
    ('Wessly Madhevere',                'bowling_style',        'Right-arm Spin'),
    ('Wessly Madhevere',                'role',                 'All-rounder'),
    ('Wessly Madhevere',                'combined_matches',     '112'),
    ('Wessly Madhevere',                'combined_runs',        '2600'),
    ('Wessly Madhevere',                'combined_wickets',     '70'),
    ('Wessly Madhevere',                'debut_year',           '2020'),

    ('Curtis Campher',                  'active_status',       'Active'),
    ('Curtis Campher',                  'country',              'Ireland'),
    ('Curtis Campher',                  'batting_hand',         'Right'),
    ('Curtis Campher',                  'bowling_style',        'Right-arm Pace'),
    ('Curtis Campher',                  'role',                 'All-rounder'),
    ('Curtis Campher',                  'combined_matches',     '135'),
    ('Curtis Campher',                  'combined_runs',        '2800'),
    ('Curtis Campher',                  'combined_wickets',     '135'),
    ('Curtis Campher',                  'debut_year',           '2020')
) AS v("PlayerName", "AttrKey", "Value")
JOIN "Players" p ON p."Name" = v."PlayerName"
JOIN "AttributeDefinitions" ad ON ad."Key" = v."AttrKey" AND ad."SportId" = p."SportId"
ON CONFLICT ("PlayerId", "AttributeDefinitionId") DO UPDATE SET
    "Value" = EXCLUDED."Value"
WHERE "PlayerAttributeValues"."IsManuallyEdited" = false;
