-- Men's International Cricket players, batch 3 (30 players, bringing the
-- roster to 90 total: batch 1's 30 + batch 2's 30 + batch 3's 30). Same
-- upsert pattern as prior batches: Players upserts on the unique Name
-- constraint, PlayerAttributeValues upserts on the existing unique
-- (PlayerId, AttributeDefinitionId) constraint, both scoped to the
-- "cricket-men-international" Sport. No overrides in this batch -- every
-- row is IsOverridden = false, DifficultyOverride = NULL.

INSERT INTO "Players" ("SportId", "Name", "IsOverridden", "DifficultyOverride")
SELECT s."Id", v."Name", v."IsOverridden", v."DifficultyOverride"
FROM "Sports" s
CROSS JOIN (VALUES
    ('Yuvraj Singh',             false, NULL),
    ('VVS Laxman',               false, NULL),
    ('Gautam Gambhir',           false, NULL),
    ('Zaheer Khan',              false, NULL),
    ('Harbhajan Singh',          false, NULL),
    ('KL Rahul',                 false, NULL),
    ('Ravindra Jadeja',          false, NULL),
    ('R Ashwin',                 false, NULL),
    ('Mitchell Starc',           false, NULL),
    ('Pat Cummins',              false, NULL),
    ('David Warner',             false, NULL),
    ('Matthew Hayden',           false, NULL),
    ('Justin Langer',            false, NULL),
    ('Brett Lee',                false, NULL),
    ('Kevin Pietersen',          false, NULL),
    ('Andrew Flintoff',          false, NULL),
    ('Jos Buttler',              false, NULL),
    ('Stuart Broad',             false, NULL),
    ('Saeed Anwar',              false, NULL),
    ('Lasith Malinga',           false, NULL),
    ('Angelo Mathews',           false, NULL),
    ('Trent Boult',              false, NULL),
    ('Martin Crowe',             false, NULL),
    ('Faf du Plessis',           false, NULL),
    ('Quinton de Kock',          false, NULL),
    ('Morne Morkel',             false, NULL),
    ('Makhaya Ntini',            false, NULL),
    ('Mushfiqur Rahim',          false, NULL),
    ('Tamim Iqbal',              false, NULL),
    ('Tim Southee',              false, NULL)
) AS v("Name", "IsOverridden", "DifficultyOverride")
WHERE s."Slug" = 'cricket-men-international'
ON CONFLICT ("Name") DO UPDATE SET
    "SportId" = EXCLUDED."SportId",
    "IsOverridden" = EXCLUDED."IsOverridden",
    "DifficultyOverride" = EXCLUDED."DifficultyOverride";

-- One row per (player, attribute) pair. PlayerId/AttributeDefinitionId are
-- resolved by name/key lookup (scoped to each player's own SportId), so
-- this file has no dependency on insertion order or id values, and can
-- never cross-attach to cricket-women-international's AttributeDefinitions.
INSERT INTO "PlayerAttributeValues" ("PlayerId", "AttributeDefinitionId", "Value")
SELECT p."Id", ad."Id", v."Value"
FROM (VALUES
    -- Player,                       AttrKey,               Value
    ('Yuvraj Singh',                 'active_status',       'Retired'),
    ('Yuvraj Singh',                 'country',              'India'),
    ('Yuvraj Singh',                 'batting_hand',         'Left'),
    ('Yuvraj Singh',                 'bowling_style',        'Left-arm Spin'),
    ('Yuvraj Singh',                 'role',                 'Batting All-rounder'),
    ('Yuvraj Singh',                 'combined_matches',     '402'),
    ('Yuvraj Singh',                 'combined_runs',        '11778'),
    ('Yuvraj Singh',                 'combined_wickets',     '148'),
    ('Yuvraj Singh',                 'debut_year',           '2000'),

    ('VVS Laxman',                   'active_status',       'Retired'),
    ('VVS Laxman',                   'country',              'India'),
    ('VVS Laxman',                   'batting_hand',         'Right'),
    ('VVS Laxman',                   'bowling_style',        'Right-arm Spin'),
    ('VVS Laxman',                   'role',                 'Batter'),
    ('VVS Laxman',                   'combined_matches',     '220'),
    ('VVS Laxman',                   'combined_runs',        '11119'),
    ('VVS Laxman',                   'combined_wickets',     '3'),
    ('VVS Laxman',                   'debut_year',           '1996'),

    ('Gautam Gambhir',               'active_status',       'Retired'),
    ('Gautam Gambhir',               'country',              'India'),
    ('Gautam Gambhir',               'batting_hand',         'Left'),
    ('Gautam Gambhir',               'bowling_style',        'Right-arm Spin'),
    ('Gautam Gambhir',               'role',                 'Batter'),
    ('Gautam Gambhir',               'combined_matches',     '242'),
    ('Gautam Gambhir',               'combined_runs',        '10324'),
    ('Gautam Gambhir',               'combined_wickets',     '0'),
    ('Gautam Gambhir',               'debut_year',           '2003'),

    ('Zaheer Khan',                  'active_status',       'Retired'),
    ('Zaheer Khan',                  'country',              'India'),
    ('Zaheer Khan',                  'batting_hand',         'Right'),
    ('Zaheer Khan',                  'bowling_style',        'Left-arm Pace'),
    ('Zaheer Khan',                  'role',                 'Bowler'),
    ('Zaheer Khan',                  'combined_matches',     '309'),
    ('Zaheer Khan',                  'combined_runs',        '2036'),
    ('Zaheer Khan',                  'combined_wickets',     '610'),
    ('Zaheer Khan',                  'debut_year',           '2000'),

    ('Harbhajan Singh',              'active_status',       'Retired'),
    ('Harbhajan Singh',              'country',              'India'),
    ('Harbhajan Singh',              'batting_hand',         'Right'),
    ('Harbhajan Singh',              'bowling_style',        'Right-arm Spin'),
    ('Harbhajan Singh',              'role',                 'Bowler'),
    ('Harbhajan Singh',              'combined_matches',     '367'),
    ('Harbhajan Singh',              'combined_runs',        '2750'),
    ('Harbhajan Singh',              'combined_wickets',     '711'),
    ('Harbhajan Singh',              'debut_year',           '1998'),

    ('KL Rahul',                     'active_status',       'Active'),
    ('KL Rahul',                     'country',              'India'),
    ('KL Rahul',                     'batting_hand',         'Right'),
    ('KL Rahul',                     'bowling_style',        'Hasn''t Bowled'),
    ('KL Rahul',                     'role',                 'Batter'),
    ('KL Rahul',                     'combined_matches',     '215'),
    ('KL Rahul',                     'combined_runs',        '8565'),
    ('KL Rahul',                     'combined_wickets',     '0'),
    ('KL Rahul',                     'debut_year',           '2014'),

    ('Ravindra Jadeja',              'active_status',       'Active'),
    ('Ravindra Jadeja',              'country',              'India'),
    ('Ravindra Jadeja',              'batting_hand',         'Left'),
    ('Ravindra Jadeja',              'bowling_style',        'Left-arm Spin'),
    ('Ravindra Jadeja',              'role',                 'All-rounder'),
    ('Ravindra Jadeja',              'combined_matches',     '373'),
    ('Ravindra Jadeja',              'combined_runs',        '7515'),
    ('Ravindra Jadeja',              'combined_wickets',     '594'),
    ('Ravindra Jadeja',              'debut_year',           '2009'),

    ('R Ashwin',                     'active_status',       'Retired'),
    ('R Ashwin',                     'country',              'India'),
    ('R Ashwin',                     'batting_hand',         'Right'),
    ('R Ashwin',                     'bowling_style',        'Right-arm Spin'),
    ('R Ashwin',                     'role',                 'Bowler'),
    ('R Ashwin',                     'combined_matches',     '287'),
    ('R Ashwin',                     'combined_runs',        '4000'),
    ('R Ashwin',                     'combined_wickets',     '765'),
    ('R Ashwin',                     'debut_year',           '2010'),

    ('Mitchell Starc',                'active_status',       'Active'),
    ('Mitchell Starc',                'country',              'Australia'),
    ('Mitchell Starc',                'batting_hand',         'Left'),
    ('Mitchell Starc',                'bowling_style',        'Left-arm Pace'),
    ('Mitchell Starc',                'role',                 'Bowler'),
    ('Mitchell Starc',                'combined_matches',     '325'),
    ('Mitchell Starc',                'combined_runs',        '2750'),
    ('Mitchell Starc',                'combined_wickets',     '754'),
    ('Mitchell Starc',                'debut_year',           '2010'),

    ('Pat Cummins',                  'active_status',       'Active'),
    ('Pat Cummins',                  'country',              'Australia'),
    ('Pat Cummins',                  'batting_hand',         'Right'),
    ('Pat Cummins',                  'bowling_style',        'Right-arm Pace'),
    ('Pat Cummins',                  'role',                 'Bowler'),
    ('Pat Cummins',                  'combined_matches',     '214'),
    ('Pat Cummins',                  'combined_runs',        '2191'),
    ('Pat Cummins',                  'combined_wickets',     '441'),
    ('Pat Cummins',                  'debut_year',           '2011'),

    ('David Warner',                 'active_status',       'Retired'),
    ('David Warner',                 'country',              'Australia'),
    ('David Warner',                 'batting_hand',         'Left'),
    ('David Warner',                 'bowling_style',        'Right-arm Spin'),
    ('David Warner',                 'role',                 'Batter'),
    ('David Warner',                 'combined_matches',     '383'),
    ('David Warner',                 'combined_runs',        '18995'),
    ('David Warner',                 'combined_wickets',     '8'),
    ('David Warner',                 'debut_year',           '2009'),

    ('Matthew Hayden',               'active_status',       'Retired'),
    ('Matthew Hayden',               'country',              'Australia'),
    ('Matthew Hayden',               'batting_hand',         'Left'),
    ('Matthew Hayden',               'bowling_style',        'Right-arm Pace'),
    ('Matthew Hayden',               'role',                 'Batter'),
    ('Matthew Hayden',               'combined_matches',     '264'),
    ('Matthew Hayden',               'combined_runs',        '14908'),
    ('Matthew Hayden',               'combined_wickets',     '2'),
    ('Matthew Hayden',               'debut_year',           '1993'),

    ('Justin Langer',                'active_status',       'Retired'),
    ('Justin Langer',                'country',              'Australia'),
    ('Justin Langer',                'batting_hand',         'Left'),
    ('Justin Langer',                'bowling_style',        'Right-arm Pace'),
    ('Justin Langer',                'role',                 'Batter'),
    ('Justin Langer',                'combined_matches',     '113'),
    ('Justin Langer',                'combined_runs',        '7846'),
    ('Justin Langer',                'combined_wickets',     '5'),
    ('Justin Langer',                'debut_year',           '1993'),

    ('Brett Lee',                    'active_status',       'Retired'),
    ('Brett Lee',                    'country',              'Australia'),
    ('Brett Lee',                    'batting_hand',         'Right'),
    ('Brett Lee',                    'bowling_style',        'Right-arm Pace'),
    ('Brett Lee',                    'role',                 'Bowler'),
    ('Brett Lee',                    'combined_matches',     '322'),
    ('Brett Lee',                    'combined_runs',        '2200'),
    ('Brett Lee',                    'combined_wickets',     '718'),
    ('Brett Lee',                    'debut_year',           '1999'),

    ('Kevin Pietersen',              'active_status',       'Retired'),
    ('Kevin Pietersen',              'country',              'England'),
    ('Kevin Pietersen',              'batting_hand',         'Right'),
    ('Kevin Pietersen',              'bowling_style',        'Right-arm Spin'),
    ('Kevin Pietersen',              'role',                 'Batter'),
    ('Kevin Pietersen',              'combined_matches',     '277'),
    ('Kevin Pietersen',              'combined_runs',        '13797'),
    ('Kevin Pietersen',              'combined_wickets',     '8'),
    ('Kevin Pietersen',              'debut_year',           '2004'),

    ('Andrew Flintoff',              'active_status',       'Retired'),
    ('Andrew Flintoff',              'country',              'England'),
    ('Andrew Flintoff',              'batting_hand',         'Right'),
    ('Andrew Flintoff',              'bowling_style',        'Right-arm Pace'),
    ('Andrew Flintoff',              'role',                 'All-rounder'),
    ('Andrew Flintoff',              'combined_matches',     '227'),
    ('Andrew Flintoff',              'combined_runs',        '7315'),
    ('Andrew Flintoff',              'combined_wickets',     '400'),
    ('Andrew Flintoff',              'debut_year',           '1998'),

    ('Jos Buttler',                  'active_status',       'Active'),
    ('Jos Buttler',                  'country',              'England'),
    ('Jos Buttler',                  'batting_hand',         'Right'),
    ('Jos Buttler',                  'bowling_style',        'Hasn''t Bowled'),
    ('Jos Buttler',                  'role',                 'Wicketkeeper-Batter'),
    ('Jos Buttler',                  'combined_matches',     '379'),
    ('Jos Buttler',                  'combined_runs',        '11285'),
    ('Jos Buttler',                  'combined_wickets',     '0'),
    ('Jos Buttler',                  'debut_year',           '2011'),

    ('Stuart Broad',                 'active_status',       'Retired'),
    ('Stuart Broad',                 'country',              'England'),
    ('Stuart Broad',                 'batting_hand',         'Left'),
    ('Stuart Broad',                 'bowling_style',        'Right-arm Pace'),
    ('Stuart Broad',                 'role',                 'Bowler'),
    ('Stuart Broad',                 'combined_matches',     '344'),
    ('Stuart Broad',                 'combined_runs',        '4311'),
    ('Stuart Broad',                 'combined_wickets',     '847'),
    ('Stuart Broad',                 'debut_year',           '2006'),

    ('Saeed Anwar',                  'active_status',       'Retired'),
    ('Saeed Anwar',                  'country',              'Pakistan'),
    ('Saeed Anwar',                  'batting_hand',         'Left'),
    ('Saeed Anwar',                  'bowling_style',        'Left-arm Spin'),
    ('Saeed Anwar',                  'role',                 'Batter'),
    ('Saeed Anwar',                  'combined_matches',     '302'),
    ('Saeed Anwar',                  'combined_runs',        '12876'),
    ('Saeed Anwar',                  'combined_wickets',     '6'),
    ('Saeed Anwar',                  'debut_year',           '1989'),

    ('Lasith Malinga',               'active_status',       'Retired'),
    ('Lasith Malinga',               'country',              'Sri Lanka'),
    ('Lasith Malinga',               'batting_hand',         'Right'),
    ('Lasith Malinga',               'bowling_style',        'Right-arm Pace'),
    ('Lasith Malinga',               'role',                 'Bowler'),
    ('Lasith Malinga',               'combined_matches',     '340'),
    ('Lasith Malinga',               'combined_runs',        '978'),
    ('Lasith Malinga',               'combined_wickets',     '546'),
    ('Lasith Malinga',               'debut_year',           '2004'),

    ('Angelo Mathews',               'active_status',       'Active'),
    ('Angelo Mathews',               'country',              'Sri Lanka'),
    ('Angelo Mathews',               'batting_hand',         'Right'),
    ('Angelo Mathews',               'bowling_style',        'Right-arm Pace'),
    ('Angelo Mathews',               'role',                 'All-rounder'),
    ('Angelo Mathews',               'combined_matches',     '434'),
    ('Angelo Mathews',               'combined_runs',        '16400'),
    ('Angelo Mathews',               'combined_wickets',     '178'),
    ('Angelo Mathews',               'debut_year',           '2008'),

    ('Trent Boult',                  'active_status',       'Retired'),
    ('Trent Boult',                  'country',              'New Zealand'),
    ('Trent Boult',                  'batting_hand',         'Right'),
    ('Trent Boult',                  'bowling_style',        'Left-arm Pace'),
    ('Trent Boult',                  'role',                 'Bowler'),
    ('Trent Boult',                  'combined_matches',     '216'),
    ('Trent Boult',                  'combined_runs',        '1000'),
    ('Trent Boult',                  'combined_wickets',     '583'),
    ('Trent Boult',                  'debut_year',           '2011'),

    ('Martin Crowe',                 'active_status',       'Retired'),
    ('Martin Crowe',                 'country',              'New Zealand'),
    ('Martin Crowe',                 'batting_hand',         'Right'),
    ('Martin Crowe',                 'bowling_style',        'Right-arm Pace'),
    ('Martin Crowe',                 'role',                 'Batter'),
    ('Martin Crowe',                 'combined_matches',     '220'),
    ('Martin Crowe',                 'combined_runs',        '10148'),
    ('Martin Crowe',                 'combined_wickets',     '35'),
    ('Martin Crowe',                 'debut_year',           '1982'),

    ('Faf du Plessis',               'active_status',       'Active'),
    ('Faf du Plessis',               'country',              'South Africa'),
    ('Faf du Plessis',               'batting_hand',         'Right'),
    ('Faf du Plessis',               'bowling_style',        'Right-arm Pace'),
    ('Faf du Plessis',               'role',                 'Batter'),
    ('Faf du Plessis',               'combined_matches',     '272'),
    ('Faf du Plessis',               'combined_runs',        '11326'),
    ('Faf du Plessis',               'combined_wickets',     '4'),
    ('Faf du Plessis',               'debut_year',           '2011'),

    ('Quinton de Kock',              'active_status',       'Active'),
    ('Quinton de Kock',              'country',              'South Africa'),
    ('Quinton de Kock',              'batting_hand',         'Left'),
    ('Quinton de Kock',              'bowling_style',        'Hasn''t Bowled'),
    ('Quinton de Kock',              'role',                 'Wicketkeeper-Batter'),
    ('Quinton de Kock',              'combined_matches',     '301'),
    ('Quinton de Kock',              'combined_runs',        '12654'),
    ('Quinton de Kock',              'combined_wickets',     '0'),
    ('Quinton de Kock',              'debut_year',           '2012'),

    ('Morne Morkel',                 'active_status',       'Retired'),
    ('Morne Morkel',                 'country',              'South Africa'),
    ('Morne Morkel',                 'batting_hand',         'Left'),
    ('Morne Morkel',                 'bowling_style',        'Right-arm Pace'),
    ('Morne Morkel',                 'role',                 'Bowler'),
    ('Morne Morkel',                 'combined_matches',     '247'),
    ('Morne Morkel',                 'combined_runs',        '1234'),
    ('Morne Morkel',                 'combined_wickets',     '545'),
    ('Morne Morkel',                 'debut_year',           '2006'),

    ('Makhaya Ntini',                'active_status',       'Retired'),
    ('Makhaya Ntini',                'country',              'South Africa'),
    ('Makhaya Ntini',                'batting_hand',         'Right'),
    ('Makhaya Ntini',                'bowling_style',        'Right-arm Pace'),
    ('Makhaya Ntini',                'role',                 'Bowler'),
    ('Makhaya Ntini',                'combined_matches',     '313'),
    ('Makhaya Ntini',                'combined_runs',        '948'),
    ('Makhaya Ntini',                'combined_wickets',     '676'),
    ('Makhaya Ntini',                'debut_year',           '1998'),

    ('Mushfiqur Rahim',              'active_status',       'Active'),
    ('Mushfiqur Rahim',              'country',              'Bangladesh'),
    ('Mushfiqur Rahim',              'batting_hand',         'Right'),
    ('Mushfiqur Rahim',              'bowling_style',        'Right-arm Spin'),
    ('Mushfiqur Rahim',              'role',                 'Wicketkeeper-Batter'),
    ('Mushfiqur Rahim',              'combined_matches',     '442'),
    ('Mushfiqur Rahim',              'combined_runs',        '15500'),
    ('Mushfiqur Rahim',              'combined_wickets',     '5'),
    ('Mushfiqur Rahim',              'debut_year',           '2005'),

    ('Tamim Iqbal',                  'active_status',       'Retired'),
    ('Tamim Iqbal',                  'country',              'Bangladesh'),
    ('Tamim Iqbal',                  'batting_hand',         'Left'),
    ('Tamim Iqbal',                  'bowling_style',        'Hasn''t Bowled'),
    ('Tamim Iqbal',                  'role',                 'Batter'),
    ('Tamim Iqbal',                  'combined_matches',     '391'),
    ('Tamim Iqbal',                  'combined_runs',        '15148'),
    ('Tamim Iqbal',                  'combined_wickets',     '0'),
    ('Tamim Iqbal',                  'debut_year',           '2007'),

    ('Tim Southee',                  'active_status',       'Retired'),
    ('Tim Southee',                  'country',              'New Zealand'),
    ('Tim Southee',                  'batting_hand',         'Right'),
    ('Tim Southee',                  'bowling_style',        'Right-arm Pace'),
    ('Tim Southee',                  'role',                 'Bowler'),
    ('Tim Southee',                  'combined_matches',     '389'),
    ('Tim Southee',                  'combined_runs',        '4500'),
    ('Tim Southee',                  'combined_wickets',     '756'),
    ('Tim Southee',                  'debut_year',           '2008')
) AS v("PlayerName", "AttrKey", "Value")
JOIN "Players" p ON p."Name" = v."PlayerName"
JOIN "AttributeDefinitions" ad ON ad."Key" = v."AttrKey" AND ad."SportId" = p."SportId"
ON CONFLICT ("PlayerId", "AttributeDefinitionId") DO UPDATE SET
    "Value" = EXCLUDED."Value";
