-- Men's International Cricket players, batch 4 (30 players, bringing the
-- roster to 120 total: batch 1's 30 + batch 2's 30 + batch 3's 30 + batch
-- 4's 30). Same upsert pattern as prior batches: Players upserts on the
-- unique Name constraint, PlayerAttributeValues upserts on the existing
-- unique (PlayerId, AttributeDefinitionId) constraint, both scoped to the
-- "cricket-men-international" Sport. No overrides in this batch -- every
-- row is IsOverridden = false, DifficultyOverride = NULL.

INSERT INTO "Players" ("SportId", "Name", "IsOverridden", "DifficultyOverride")
SELECT s."Id", v."Name", v."IsOverridden", v."DifficultyOverride"
FROM "Sports" s
CROSS JOIN (VALUES
    ('Suryakumar Yadav',         false, NULL),
    ('Mohammed Shami',           false, NULL),
    ('Shubman Gill',             false, NULL),
    ('Hardik Pandya',            false, NULL),
    ('Josh Hazlewood',           false, NULL),
    ('Marnus Labuschagne',       false, NULL),
    ('Shane Watson',             false, NULL),
    ('Michael Bevan',            false, NULL),
    ('Moeen Ali',                false, NULL),
    ('Jonny Bairstow',           false, NULL),
    ('Michael Vaughan',          false, NULL),
    ('Marcus Trescothick',       false, NULL),
    ('Shaheen Afridi',           false, NULL),
    ('Mohammad Rizwan',          false, NULL),
    ('Javed Miandad',            false, NULL),
    ('Andre Russell',            false, NULL),
    ('Kieron Pollard',           false, NULL),
    ('Dwayne Bravo',             false, NULL),
    ('Sunil Narine',             false, NULL),
    ('Dimuth Karunaratne',       false, NULL),
    ('Wanindu Hasaranga',        false, NULL),
    ('Devon Conway',             false, NULL),
    ('Mitchell Santner',         false, NULL),
    ('Kagiso Rabada',            false, NULL),
    ('Vernon Philander',         false, NULL),
    ('Brendan Taylor',           false, NULL),
    ('Heath Streak',             false, NULL),
    ('Mohammad Nabi',            false, NULL),
    ('Shai Hope',                false, NULL),
    ('David Miller',             false, NULL)
) AS v("Name", "IsOverridden", "DifficultyOverride")
WHERE s."Slug" = 'cricket-men-international'
ON CONFLICT ("Name") DO UPDATE SET
    "SportId" = EXCLUDED."SportId",
    "IsOverridden" = EXCLUDED."IsOverridden",
    "DifficultyOverride" = EXCLUDED."DifficultyOverride";

-- One row per (player, attribute) pair. PlayerId/AttributeDefinitionId are
-- resolved by name/key lookup (scoped to each player's own SportId), so
-- this file has no dependency on insertion order or id values, and can
-- never cross-attach to cricket-women-international's AttributeDefinitions.
INSERT INTO "PlayerAttributeValues" ("PlayerId", "AttributeDefinitionId", "Value")
SELECT p."Id", ad."Id", v."Value"
FROM (VALUES
    -- Player,                       AttrKey,               Value
    ('Suryakumar Yadav',             'active_status',       'Active'),
    ('Suryakumar Yadav',             'country',              'India'),
    ('Suryakumar Yadav',             'batting_hand',         'Right'),
    ('Suryakumar Yadav',             'bowling_style',        'Hasn''t Bowled'),
    ('Suryakumar Yadav',             'role',                 'Batter'),
    ('Suryakumar Yadav',             'combined_matches',     '105'),
    ('Suryakumar Yadav',             'combined_runs',        '3000'),
    ('Suryakumar Yadav',             'combined_wickets',     '0'),
    ('Suryakumar Yadav',             'debut_year',           '2021'),

    ('Mohammed Shami',               'active_status',       'Active'),
    ('Mohammed Shami',               'country',              'India'),
    ('Mohammed Shami',               'batting_hand',         'Right'),
    ('Mohammed Shami',               'bowling_style',        'Right-arm Pace'),
    ('Mohammed Shami',               'role',                 'Bowler'),
    ('Mohammed Shami',               'combined_matches',     '197'),
    ('Mohammed Shami',               'combined_runs',        '981'),
    ('Mohammed Shami',               'combined_wickets',     '462'),
    ('Mohammed Shami',               'debut_year',           '2013'),

    ('Shubman Gill',                 'active_status',       'Active'),
    ('Shubman Gill',                 'country',              'India'),
    ('Shubman Gill',                 'batting_hand',         'Right'),
    ('Shubman Gill',                 'bowling_style',        'Right-arm Spin'),
    ('Shubman Gill',                 'role',                 'Batter'),
    ('Shubman Gill',                 'combined_matches',     '126'),
    ('Shubman Gill',                 'combined_runs',        '6738'),
    ('Shubman Gill',                 'combined_wickets',     '0'),
    ('Shubman Gill',                 'debut_year',           '2019'),

    ('Hardik Pandya',                'active_status',       'Active'),
    ('Hardik Pandya',                'country',              'India'),
    ('Hardik Pandya',                'batting_hand',         'Right'),
    ('Hardik Pandya',                'bowling_style',        'Right-arm Pace'),
    ('Hardik Pandya',                'role',                 'All-rounder'),
    ('Hardik Pandya',                'combined_matches',     '215'),
    ('Hardik Pandya',                'combined_runs',        '4536'),
    ('Hardik Pandya',                'combined_wickets',     '213'),
    ('Hardik Pandya',                'debut_year',           '2016'),

    ('Josh Hazlewood',               'active_status',       'Active'),
    ('Josh Hazlewood',               'country',              'Australia'),
    ('Josh Hazlewood',               'batting_hand',         'Left'),
    ('Josh Hazlewood',               'bowling_style',        'Right-arm Pace'),
    ('Josh Hazlewood',               'role',                 'Bowler'),
    ('Josh Hazlewood',               'combined_matches',     '232'),
    ('Josh Hazlewood',               'combined_runs',        '800'),
    ('Josh Hazlewood',               'combined_wickets',     '516'),
    ('Josh Hazlewood',               'debut_year',           '2010'),

    ('Marnus Labuschagne',           'active_status',       'Active'),
    ('Marnus Labuschagne',           'country',              'Australia'),
    ('Marnus Labuschagne',           'batting_hand',         'Right'),
    ('Marnus Labuschagne',           'bowling_style',        'Right-arm Pace'),
    ('Marnus Labuschagne',           'role',                 'Batter'),
    ('Marnus Labuschagne',           'combined_matches',     '91'),
    ('Marnus Labuschagne',           'combined_runs',        '5920'),
    ('Marnus Labuschagne',           'combined_wickets',     '9'),
    ('Marnus Labuschagne',           'debut_year',           '2018'),

    ('Shane Watson',                 'active_status',       'Retired'),
    ('Shane Watson',                 'country',              'Australia'),
    ('Shane Watson',                 'batting_hand',         'Right'),
    ('Shane Watson',                 'bowling_style',        'Right-arm Pace'),
    ('Shane Watson',                 'role',                 'All-rounder'),
    ('Shane Watson',                 'combined_matches',     '307'),
    ('Shane Watson',                 'combined_runs',        '10950'),
    ('Shane Watson',                 'combined_wickets',     '291'),
    ('Shane Watson',                 'debut_year',           '2002'),

    ('Michael Bevan',                'active_status',       'Retired'),
    ('Michael Bevan',                'country',              'Australia'),
    ('Michael Bevan',                'batting_hand',         'Left'),
    ('Michael Bevan',                'bowling_style',        'Left-arm Spin'),
    ('Michael Bevan',                'role',                 'Batter'),
    ('Michael Bevan',                'combined_matches',     '250'),
    ('Michael Bevan',                'combined_runs',        '7697'),
    ('Michael Bevan',                'combined_wickets',     '38'),
    ('Michael Bevan',                'debut_year',           '1994'),

    ('Moeen Ali',                    'active_status',       'Active'),
    ('Moeen Ali',                    'country',              'England'),
    ('Moeen Ali',                    'batting_hand',         'Left'),
    ('Moeen Ali',                    'bowling_style',        'Right-arm Spin'),
    ('Moeen Ali',                    'role',                 'All-rounder'),
    ('Moeen Ali',                    'combined_matches',     '299'),
    ('Moeen Ali',                    'combined_runs',        '6800'),
    ('Moeen Ali',                    'combined_wickets',     '366'),
    ('Moeen Ali',                    'debut_year',           '2014'),

    ('Jonny Bairstow',               'active_status',       'Active'),
    ('Jonny Bairstow',               'country',              'England'),
    ('Jonny Bairstow',               'batting_hand',         'Right'),
    ('Jonny Bairstow',               'bowling_style',        'Right-arm Pace'),
    ('Jonny Bairstow',               'role',                 'Wicketkeeper-Batter'),
    ('Jonny Bairstow',               'combined_matches',     '287'),
    ('Jonny Bairstow',               'combined_runs',        '11581'),
    ('Jonny Bairstow',               'combined_wickets',     '0'),
    ('Jonny Bairstow',               'debut_year',           '2011'),

    ('Michael Vaughan',              'active_status',       'Retired'),
    ('Michael Vaughan',              'country',              'England'),
    ('Michael Vaughan',              'batting_hand',         'Right'),
    ('Michael Vaughan',              'bowling_style',        'Right-arm Spin'),
    ('Michael Vaughan',              'role',                 'Batter'),
    ('Michael Vaughan',              'combined_matches',     '170'),
    ('Michael Vaughan',              'combined_runs',        '7728'),
    ('Michael Vaughan',              'combined_wickets',     '22'),
    ('Michael Vaughan',              'debut_year',           '1999'),

    ('Marcus Trescothick',           'active_status',       'Retired'),
    ('Marcus Trescothick',           'country',              'England'),
    ('Marcus Trescothick',           'batting_hand',         'Left'),
    ('Marcus Trescothick',           'bowling_style',        'Right-arm Pace'),
    ('Marcus Trescothick',           'role',                 'Batter'),
    ('Marcus Trescothick',           'combined_matches',     '202'),
    ('Marcus Trescothick',           'combined_runs',        '10326'),
    ('Marcus Trescothick',           'combined_wickets',     '2'),
    ('Marcus Trescothick',           'debut_year',           '2000'),

    ('Shaheen Afridi',               'active_status',       'Active'),
    ('Shaheen Afridi',               'country',              'Pakistan'),
    ('Shaheen Afridi',               'batting_hand',         'Left'),
    ('Shaheen Afridi',               'bowling_style',        'Left-arm Pace'),
    ('Shaheen Afridi',               'role',                 'Bowler'),
    ('Shaheen Afridi',               'combined_matches',     '211'),
    ('Shaheen Afridi',               'combined_runs',        '1200'),
    ('Shaheen Afridi',               'combined_wickets',     '401'),
    ('Shaheen Afridi',               'debut_year',           '2018'),

    ('Mohammad Rizwan',               'active_status',       'Active'),
    ('Mohammad Rizwan',               'country',              'Pakistan'),
    ('Mohammad Rizwan',               'batting_hand',         'Right'),
    ('Mohammad Rizwan',               'bowling_style',        'Hasn''t Bowled'),
    ('Mohammad Rizwan',               'role',                 'Wicketkeeper-Batter'),
    ('Mohammad Rizwan',               'combined_matches',     '236'),
    ('Mohammad Rizwan',               'combined_runs',        '8331'),
    ('Mohammad Rizwan',               'combined_wickets',     '0'),
    ('Mohammad Rizwan',               'debut_year',           '2015'),

    ('Javed Miandad',                'active_status',       'Retired'),
    ('Javed Miandad',                'country',              'Pakistan'),
    ('Javed Miandad',                'batting_hand',         'Right'),
    ('Javed Miandad',                'bowling_style',        'Right-arm Spin'),
    ('Javed Miandad',                'role',                 'Batter'),
    ('Javed Miandad',                'combined_matches',     '357'),
    ('Javed Miandad',                'combined_runs',        '16213'),
    ('Javed Miandad',                'combined_wickets',     '25'),
    ('Javed Miandad',                'debut_year',           '1975'),

    ('Andre Russell',                'active_status',       'Active'),
    ('Andre Russell',                'country',              'West Indies'),
    ('Andre Russell',                'batting_hand',         'Right'),
    ('Andre Russell',                'bowling_style',        'Right-arm Pace'),
    ('Andre Russell',                'role',                 'All-rounder'),
    ('Andre Russell',                'combined_matches',     '143'),
    ('Andre Russell',                'combined_runs',        '2158'),
    ('Andre Russell',                'combined_wickets',     '132'),
    ('Andre Russell',                'debut_year',           '2010'),

    ('Kieron Pollard',                'active_status',       'Retired'),
    ('Kieron Pollard',                'country',              'West Indies'),
    ('Kieron Pollard',                'batting_hand',         'Right'),
    ('Kieron Pollard',                'bowling_style',        'Right-arm Pace'),
    ('Kieron Pollard',                'role',                 'All-rounder'),
    ('Kieron Pollard',                'combined_matches',     '224'),
    ('Kieron Pollard',                'combined_runs',        '4275'),
    ('Kieron Pollard',                'combined_wickets',     '97'),
    ('Kieron Pollard',                'debut_year',           '2007'),

    ('Dwayne Bravo',                 'active_status',       'Retired'),
    ('Dwayne Bravo',                 'country',              'West Indies'),
    ('Dwayne Bravo',                 'batting_hand',         'Right'),
    ('Dwayne Bravo',                 'bowling_style',        'Right-arm Pace'),
    ('Dwayne Bravo',                 'role',                 'All-rounder'),
    ('Dwayne Bravo',                 'combined_matches',     '295'),
    ('Dwayne Bravo',                 'combined_runs',        '6423'),
    ('Dwayne Bravo',                 'combined_wickets',     '363'),
    ('Dwayne Bravo',                 'debut_year',           '2004'),

    ('Sunil Narine',                 'active_status',       'Active'),
    ('Sunil Narine',                 'country',              'West Indies'),
    ('Sunil Narine',                 'batting_hand',         'Right'),
    ('Sunil Narine',                 'bowling_style',        'Right-arm Spin'),
    ('Sunil Narine',                 'role',                 'Bowler'),
    ('Sunil Narine',                 'combined_matches',     '122'),
    ('Sunil Narine',                 'combined_runs',        '558'),
    ('Sunil Narine',                 'combined_wickets',     '165'),
    ('Sunil Narine',                 'debut_year',           '2011'),

    ('Dimuth Karunaratne',           'active_status',       'Retired'),
    ('Dimuth Karunaratne',           'country',              'Sri Lanka'),
    ('Dimuth Karunaratne',           'batting_hand',         'Left'),
    ('Dimuth Karunaratne',           'bowling_style',        'Right-arm Pace'),
    ('Dimuth Karunaratne',           'role',                 'Batter'),
    ('Dimuth Karunaratne',           'combined_matches',     '157'),
    ('Dimuth Karunaratne',           'combined_runs',        '8316'),
    ('Dimuth Karunaratne',           'combined_wickets',     '4'),
    ('Dimuth Karunaratne',           'debut_year',           '2010'),

    ('Wanindu Hasaranga',            'active_status',       'Active'),
    ('Wanindu Hasaranga',            'country',              'Sri Lanka'),
    ('Wanindu Hasaranga',            'batting_hand',         'Right'),
    ('Wanindu Hasaranga',            'bowling_style',        'Right-arm Spin'),
    ('Wanindu Hasaranga',            'role',                 'Bowling All-rounder'),
    ('Wanindu Hasaranga',            'combined_matches',     '159'),
    ('Wanindu Hasaranga',            'combined_runs',        '2087'),
    ('Wanindu Hasaranga',            'combined_wickets',     '245'),
    ('Wanindu Hasaranga',            'debut_year',           '2017'),

    ('Devon Conway',                 'active_status',       'Active'),
    ('Devon Conway',                 'country',              'New Zealand'),
    ('Devon Conway',                 'batting_hand',         'Left'),
    ('Devon Conway',                 'bowling_style',        'Right-arm Pace'),
    ('Devon Conway',                 'role',                 'Batter'),
    ('Devon Conway',                 'combined_matches',     '127'),
    ('Devon Conway',                 'combined_runs',        '5679'),
    ('Devon Conway',                 'combined_wickets',     '1'),
    ('Devon Conway',                 'debut_year',           '2020'),

    ('Mitchell Santner',              'active_status',       'Active'),
    ('Mitchell Santner',              'country',              'New Zealand'),
    ('Mitchell Santner',              'batting_hand',         'Left'),
    ('Mitchell Santner',              'bowling_style',        'Left-arm Spin'),
    ('Mitchell Santner',              'role',                 'All-rounder'),
    ('Mitchell Santner',              'combined_matches',     '278'),
    ('Mitchell Santner',              'combined_runs',        '3229'),
    ('Mitchell Santner',              'combined_wickets',     '320'),
    ('Mitchell Santner',              'debut_year',           '2015'),

    ('Kagiso Rabada',                'active_status',       'Active'),
    ('Kagiso Rabada',                'country',              'South Africa'),
    ('Kagiso Rabada',                'batting_hand',         'Right'),
    ('Kagiso Rabada',                'bowling_style',        'Right-arm Pace'),
    ('Kagiso Rabada',                'role',                 'Bowler'),
    ('Kagiso Rabada',                'combined_matches',     '241'),
    ('Kagiso Rabada',                'combined_runs',        '1587'),
    ('Kagiso Rabada',                'combined_wickets',     '571'),
    ('Kagiso Rabada',                'debut_year',           '2014'),

    ('Vernon Philander',             'active_status',       'Retired'),
    ('Vernon Philander',             'country',              'South Africa'),
    ('Vernon Philander',             'batting_hand',         'Right'),
    ('Vernon Philander',             'bowling_style',        'Right-arm Pace'),
    ('Vernon Philander',             'role',                 'All-rounder'),
    ('Vernon Philander',             'combined_matches',     '106'),
    ('Vernon Philander',             'combined_runs',        '1250'),
    ('Vernon Philander',             'combined_wickets',     '269'),
    ('Vernon Philander',             'debut_year',           '2011'),

    ('Brendan Taylor',                'active_status',       'Retired'),
    ('Brendan Taylor',                'country',              'Zimbabwe'),
    ('Brendan Taylor',                'batting_hand',         'Right'),
    ('Brendan Taylor',                'bowling_style',        'Hasn''t Bowled'),
    ('Brendan Taylor',                'role',                 'Wicketkeeper-Batter'),
    ('Brendan Taylor',                'combined_matches',     '285'),
    ('Brendan Taylor',                'combined_runs',        '9324'),
    ('Brendan Taylor',                'combined_wickets',     '0'),
    ('Brendan Taylor',                'debut_year',           '2004'),

    ('Heath Streak',                 'active_status',       'Retired'),
    ('Heath Streak',                 'country',              'Zimbabwe'),
    ('Heath Streak',                 'batting_hand',         'Right'),
    ('Heath Streak',                 'bowling_style',        'Right-arm Pace'),
    ('Heath Streak',                 'role',                 'All-rounder'),
    ('Heath Streak',                 'combined_matches',     '254'),
    ('Heath Streak',                 'combined_runs',        '4000'),
    ('Heath Streak',                 'combined_wickets',     '455'),
    ('Heath Streak',                 'debut_year',           '1993'),

    ('Mohammad Nabi',                'active_status',       'Active'),
    ('Mohammad Nabi',                'country',              'Afghanistan'),
    ('Mohammad Nabi',                'batting_hand',         'Right'),
    ('Mohammad Nabi',                'bowling_style',        'Right-arm Spin'),
    ('Mohammad Nabi',                'role',                 'All-rounder'),
    ('Mohammad Nabi',                'combined_matches',     '304'),
    ('Mohammad Nabi',                'combined_runs',        '6000'),
    ('Mohammad Nabi',                'combined_wickets',     '288'),
    ('Mohammad Nabi',                'debut_year',           '2009'),

    ('Shai Hope',                    'active_status',       'Active'),
    ('Shai Hope',                    'country',              'West Indies'),
    ('Shai Hope',                    'batting_hand',         'Right'),
    ('Shai Hope',                    'bowling_style',        'Left-arm Pace'),
    ('Shai Hope',                    'role',                 'Wicketkeeper-Batter'),
    ('Shai Hope',                    'combined_matches',     '235'),
    ('Shai Hope',                    'combined_runs',        '9000'),
    ('Shai Hope',                    'combined_wickets',     '2'),
    ('Shai Hope',                    'debut_year',           '2015'),

    ('David Miller',                 'active_status',       'Active'),
    ('David Miller',                 'country',              'South Africa'),
    ('David Miller',                 'batting_hand',         'Left'),
    ('David Miller',                 'bowling_style',        'Right-arm Spin'),
    ('David Miller',                 'role',                 'Batter'),
    ('David Miller',                 'combined_matches',     '300'),
    ('David Miller',                 'combined_runs',        '7500'),
    ('David Miller',                 'combined_wickets',     '2'),
    ('David Miller',                 'debut_year',           '2010')
) AS v("PlayerName", "AttrKey", "Value")
JOIN "Players" p ON p."Name" = v."PlayerName"
JOIN "AttributeDefinitions" ad ON ad."Key" = v."AttrKey" AND ad."SportId" = p."SportId"
ON CONFLICT ("PlayerId", "AttributeDefinitionId") DO UPDATE SET
    "Value" = EXCLUDED."Value";
