-- Men's International Cricket players, batch 5 (30 players, bringing the
-- roster to 150 total: batch 1's 30 + batch 2's 30 + batch 3's 30 + batch
-- 4's 30 + batch 5's 30). Same upsert pattern as prior batches: Players
-- upserts on the unique Name constraint, PlayerAttributeValues upserts on
-- the existing unique (PlayerId, AttributeDefinitionId) constraint, both
-- scoped to the "cricket-men-international" Sport. No overrides in this
-- batch -- every row is IsOverridden = false, DifficultyOverride = NULL.

INSERT INTO "Players" ("SportId", "Name", "IsOverridden", "DifficultyOverride")
SELECT s."Id", v."Name", v."IsOverridden", v."DifficultyOverride"
FROM "Sports" s
CROSS JOIN (VALUES
    ('Yashasvi Jaiswal',         false, NULL),
    ('Rishabh Pant',             false, NULL),
    ('Travis Head',              false, NULL),
    ('Alex Carey',               false, NULL),
    ('Cameron Green',            false, NULL),
    ('Marcus Stoinis',           false, NULL),
    ('Harry Brook',              false, NULL),
    ('Ben Duckett',              false, NULL),
    ('Sam Curran',               false, NULL),
    ('Adil Rashid',              false, NULL),
    ('Fakhar Zaman',             false, NULL),
    ('Naseem Shah',              false, NULL),
    ('Haris Rauf',               false, NULL),
    ('Pathum Nissanka',          false, NULL),
    ('Dasun Shanaka',            false, NULL),
    ('Nicholas Pooran',          false, NULL),
    ('Shimron Hetmyer',          false, NULL),
    ('Jason Holder',             false, NULL),
    ('Glenn Phillips',           false, NULL),
    ('Finn Allen',               false, NULL),
    ('Lockie Ferguson',          false, NULL),
    ('Aiden Markram',            false, NULL),
    ('Tristan Stubbs',           false, NULL),
    ('Anrich Nortje',            false, NULL),
    ('Litton Das',               false, NULL),
    ('Sikandar Raza',            false, NULL),
    ('Ibrahim Zadran',           false, NULL),
    ('Andrew Balbirnie',         false, NULL),
    ('Brandon McMullen',         false, NULL),
    ('Scott Edwards',            false, NULL)
) AS v("Name", "IsOverridden", "DifficultyOverride")
WHERE s."Slug" = 'cricket-men-international'
ON CONFLICT ("Name") DO UPDATE SET
    "SportId" = EXCLUDED."SportId",
    "IsOverridden" = EXCLUDED."IsOverridden",
    "DifficultyOverride" = EXCLUDED."DifficultyOverride";

-- One row per (player, attribute) pair. PlayerId/AttributeDefinitionId are
-- resolved by name/key lookup (scoped to each player's own SportId), so
-- this file has no dependency on insertion order or id values, and can
-- never cross-attach to cricket-women-international's AttributeDefinitions.
INSERT INTO "PlayerAttributeValues" ("PlayerId", "AttributeDefinitionId", "Value")
SELECT p."Id", ad."Id", v."Value"
FROM (VALUES
    -- Player,                       AttrKey,               Value
    ('Yashasvi Jaiswal',             'active_status',       'Active'),
    ('Yashasvi Jaiswal',             'country',              'India'),
    ('Yashasvi Jaiswal',             'batting_hand',         'Left'),
    ('Yashasvi Jaiswal',             'bowling_style',        'Right-arm Spin'),
    ('Yashasvi Jaiswal',             'role',                 'Batter'),
    ('Yashasvi Jaiswal',             'combined_matches',     '52'),
    ('Yashasvi Jaiswal',             'combined_runs',        '3141'),
    ('Yashasvi Jaiswal',             'combined_wickets',     '1'),
    ('Yashasvi Jaiswal',             'debut_year',           '2023'),

    ('Rishabh Pant',                 'active_status',       'Active'),
    ('Rishabh Pant',                 'country',              'India'),
    ('Rishabh Pant',                 'batting_hand',         'Left'),
    ('Rishabh Pant',                 'bowling_style',        'Right-arm Pace'),
    ('Rishabh Pant',                 'role',                 'Wicketkeeper-Batter'),
    ('Rishabh Pant',                 'combined_matches',     '182'),
    ('Rishabh Pant',                 'combined_runs',        '5150'),
    ('Rishabh Pant',                 'combined_wickets',     '1'),
    ('Rishabh Pant',                 'debut_year',           '2017'),

    ('Travis Head',                  'active_status',       'Active'),
    ('Travis Head',                  'country',              'Australia'),
    ('Travis Head',                  'batting_hand',         'Right'),
    ('Travis Head',                  'bowling_style',        'Right-arm Spin'),
    ('Travis Head',                  'role',                 'Batter'),
    ('Travis Head',                  'combined_matches',     '195'),
    ('Travis Head',                  'combined_runs',        '8900'),
    ('Travis Head',                  'combined_wickets',     '22'),
    ('Travis Head',                  'debut_year',           '2016'),

    ('Alex Carey',                   'active_status',       'Active'),
    ('Alex Carey',                   'country',              'Australia'),
    ('Alex Carey',                   'batting_hand',         'Left'),
    ('Alex Carey',                   'bowling_style',        'Hasn''t Bowled'),
    ('Alex Carey',                   'role',                 'Wicketkeeper-Batter'),
    ('Alex Carey',                   'combined_matches',     '178'),
    ('Alex Carey',                   'combined_runs',        '5278'),
    ('Alex Carey',                   'combined_wickets',     '0'),
    ('Alex Carey',                   'debut_year',           '2018'),

    ('Cameron Green',                'active_status',       'Active'),
    ('Cameron Green',                'country',              'Australia'),
    ('Cameron Green',                'batting_hand',         'Right'),
    ('Cameron Green',                'bowling_style',        'Right-arm Pace'),
    ('Cameron Green',                'role',                 'All-rounder'),
    ('Cameron Green',                'combined_matches',     '88'),
    ('Cameron Green',                'combined_runs',        '3000'),
    ('Cameron Green',                'combined_wickets',     '50'),
    ('Cameron Green',                'debut_year',           '2020'),

    ('Marcus Stoinis',               'active_status',       'Retired'),
    ('Marcus Stoinis',               'country',              'Australia'),
    ('Marcus Stoinis',               'batting_hand',         'Right'),
    ('Marcus Stoinis',               'bowling_style',        'Right-arm Pace'),
    ('Marcus Stoinis',               'role',                 'Batting All-rounder'),
    ('Marcus Stoinis',               'combined_matches',     '165'),
    ('Marcus Stoinis',               'combined_runs',        '3800'),
    ('Marcus Stoinis',               'combined_wickets',     '95'),
    ('Marcus Stoinis',               'debut_year',           '2015'),

    ('Harry Brook',                  'active_status',       'Active'),
    ('Harry Brook',                  'country',              'England'),
    ('Harry Brook',                  'batting_hand',         'Right'),
    ('Harry Brook',                  'bowling_style',        'Right-arm Pace'),
    ('Harry Brook',                  'role',                 'Batter'),
    ('Harry Brook',                  'combined_matches',     '80'),
    ('Harry Brook',                  'combined_runs',        '4650'),
    ('Harry Brook',                  'combined_wickets',     '0'),
    ('Harry Brook',                  'debut_year',           '2022'),

    ('Ben Duckett',                  'active_status',       'Active'),
    ('Ben Duckett',                  'country',              'England'),
    ('Ben Duckett',                  'batting_hand',         'Left'),
    ('Ben Duckett',                  'bowling_style',        'Right-arm Spin'),
    ('Ben Duckett',                  'role',                 'Batter'),
    ('Ben Duckett',                  'combined_matches',     '89'),
    ('Ben Duckett',                  'combined_runs',        '4248'),
    ('Ben Duckett',                  'combined_wickets',     '0'),
    ('Ben Duckett',                  'debut_year',           '2016'),

    ('Sam Curran',                   'active_status',       'Active'),
    ('Sam Curran',                   'country',              'England'),
    ('Sam Curran',                   'batting_hand',         'Left'),
    ('Sam Curran',                   'bowling_style',        'Left-arm Pace'),
    ('Sam Curran',                   'role',                 'All-rounder'),
    ('Sam Curran',                   'combined_matches',     '170'),
    ('Sam Curran',                   'combined_runs',        '2150'),
    ('Sam Curran',                   'combined_wickets',     '240'),
    ('Sam Curran',                   'debut_year',           '2018'),

    ('Adil Rashid',                  'active_status',       'Active'),
    ('Adil Rashid',                  'country',              'England'),
    ('Adil Rashid',                  'batting_hand',         'Right'),
    ('Adil Rashid',                  'bowling_style',        'Right-arm Spin'),
    ('Adil Rashid',                  'role',                 'Bowler'),
    ('Adil Rashid',                  'combined_matches',     '279'),
    ('Adil Rashid',                  'combined_runs',        '1050'),
    ('Adil Rashid',                  'combined_wickets',     '390'),
    ('Adil Rashid',                  'debut_year',           '2009'),

    ('Fakhar Zaman',                 'active_status',       'Active'),
    ('Fakhar Zaman',                 'country',              'Pakistan'),
    ('Fakhar Zaman',                 'batting_hand',         'Left'),
    ('Fakhar Zaman',                 'bowling_style',        'Hasn''t Bowled'),
    ('Fakhar Zaman',                 'role',                 'Batter'),
    ('Fakhar Zaman',                 'combined_matches',     '185'),
    ('Fakhar Zaman',                 'combined_runs',        '5853'),
    ('Fakhar Zaman',                 'combined_wickets',     '0'),
    ('Fakhar Zaman',                 'debut_year',           '2017'),

    ('Naseem Shah',                  'active_status',       'Active'),
    ('Naseem Shah',                  'country',              'Pakistan'),
    ('Naseem Shah',                  'batting_hand',         'Right'),
    ('Naseem Shah',                  'bowling_style',        'Right-arm Pace'),
    ('Naseem Shah',                  'role',                 'Bowler'),
    ('Naseem Shah',                  'combined_matches',     '100'),
    ('Naseem Shah',                  'combined_runs',        '700'),
    ('Naseem Shah',                  'combined_wickets',     '145'),
    ('Naseem Shah',                  'debut_year',           '2020'),

    ('Haris Rauf',                   'active_status',       'Active'),
    ('Haris Rauf',                   'country',              'Pakistan'),
    ('Haris Rauf',                   'batting_hand',         'Right'),
    ('Haris Rauf',                   'bowling_style',        'Right-arm Pace'),
    ('Haris Rauf',                   'role',                 'Bowler'),
    ('Haris Rauf',                   'combined_matches',     '151'),
    ('Haris Rauf',                   'combined_runs',        '250'),
    ('Haris Rauf',                   'combined_wickets',     '222'),
    ('Haris Rauf',                   'debut_year',           '2020'),

    ('Pathum Nissanka',              'active_status',       'Active'),
    ('Pathum Nissanka',              'country',              'Sri Lanka'),
    ('Pathum Nissanka',              'batting_hand',         'Right'),
    ('Pathum Nissanka',              'bowling_style',        'Hasn''t Bowled'),
    ('Pathum Nissanka',              'role',                 'Batter'),
    ('Pathum Nissanka',              'combined_matches',     '165'),
    ('Pathum Nissanka',              'combined_runs',        '6800'),
    ('Pathum Nissanka',              'combined_wickets',     '0'),
    ('Pathum Nissanka',              'debut_year',           '2021'),

    ('Dasun Shanaka',                'active_status',       'Active'),
    ('Dasun Shanaka',                'country',              'Sri Lanka'),
    ('Dasun Shanaka',                'batting_hand',         'Right'),
    ('Dasun Shanaka',                'bowling_style',        'Right-arm Pace'),
    ('Dasun Shanaka',                'role',                 'All-rounder'),
    ('Dasun Shanaka',                'combined_matches',     '220'),
    ('Dasun Shanaka',                'combined_runs',        '4100'),
    ('Dasun Shanaka',                'combined_wickets',     '105'),
    ('Dasun Shanaka',                'debut_year',           '2015'),

    ('Nicholas Pooran',               'active_status',       'Retired'),
    ('Nicholas Pooran',               'country',              'West Indies'),
    ('Nicholas Pooran',               'batting_hand',         'Left'),
    ('Nicholas Pooran',               'bowling_style',        'Right-arm Spin'),
    ('Nicholas Pooran',               'role',                 'Wicketkeeper-Batter'),
    ('Nicholas Pooran',               'combined_matches',     '185'),
    ('Nicholas Pooran',               'combined_runs',        '4300'),
    ('Nicholas Pooran',               'combined_wickets',     '7'),
    ('Nicholas Pooran',               'debut_year',           '2016'),

    ('Shimron Hetmyer',              'active_status',       'Active'),
    ('Shimron Hetmyer',              'country',              'West Indies'),
    ('Shimron Hetmyer',              'batting_hand',         'Left'),
    ('Shimron Hetmyer',              'bowling_style',        'Hasn''t Bowled'),
    ('Shimron Hetmyer',              'role',                 'Batter'),
    ('Shimron Hetmyer',              'combined_matches',     '169'),
    ('Shimron Hetmyer',              'combined_runs',        '4150'),
    ('Shimron Hetmyer',              'combined_wickets',     '0'),
    ('Shimron Hetmyer',              'debut_year',           '2017'),

    ('Jason Holder',                 'active_status',       'Active'),
    ('Jason Holder',                 'country',              'West Indies'),
    ('Jason Holder',                 'batting_hand',         'Right'),
    ('Jason Holder',                 'bowling_style',        'Right-arm Pace'),
    ('Jason Holder',                 'role',                 'Bowling All-rounder'),
    ('Jason Holder',                 'combined_matches',     '293'),
    ('Jason Holder',                 'combined_runs',        '6056'),
    ('Jason Holder',                 'combined_wickets',     '418'),
    ('Jason Holder',                 'debut_year',           '2013'),

    ('Glenn Phillips',                'active_status',       'Active'),
    ('Glenn Phillips',                'country',              'New Zealand'),
    ('Glenn Phillips',                'batting_hand',         'Right'),
    ('Glenn Phillips',                'bowling_style',        'Right-arm Spin'),
    ('Glenn Phillips',                'role',                 'All-rounder'),
    ('Glenn Phillips',                'combined_matches',     '179'),
    ('Glenn Phillips',                'combined_runs',        '5156'),
    ('Glenn Phillips',                'combined_wickets',     '45'),
    ('Glenn Phillips',                'debut_year',           '2017'),

    ('Finn Allen',                   'active_status',       'Active'),
    ('Finn Allen',                   'country',              'New Zealand'),
    ('Finn Allen',                   'batting_hand',         'Right'),
    ('Finn Allen',                   'bowling_style',        'Hasn''t Bowled'),
    ('Finn Allen',                   'role',                 'Batter'),
    ('Finn Allen',                   'combined_matches',     '75'),
    ('Finn Allen',                   'combined_runs',        '1800'),
    ('Finn Allen',                   'combined_wickets',     '0'),
    ('Finn Allen',                   'debut_year',           '2020'),

    ('Lockie Ferguson',              'active_status',       'Active'),
    ('Lockie Ferguson',              'country',              'New Zealand'),
    ('Lockie Ferguson',              'batting_hand',         'Right'),
    ('Lockie Ferguson',              'bowling_style',        'Right-arm Pace'),
    ('Lockie Ferguson',              'role',                 'Bowler'),
    ('Lockie Ferguson',              'combined_matches',     '140'),
    ('Lockie Ferguson',              'combined_runs',        '300'),
    ('Lockie Ferguson',              'combined_wickets',     '220'),
    ('Lockie Ferguson',              'debut_year',           '2016'),

    ('Aiden Markram',                'active_status',       'Active'),
    ('Aiden Markram',                'country',              'South Africa'),
    ('Aiden Markram',                'batting_hand',         'Right'),
    ('Aiden Markram',                'bowling_style',        'Right-arm Spin'),
    ('Aiden Markram',                'role',                 'Batter'),
    ('Aiden Markram',                'combined_matches',     '200'),
    ('Aiden Markram',                'combined_runs',        '8100'),
    ('Aiden Markram',                'combined_wickets',     '18'),
    ('Aiden Markram',                'debut_year',           '2017'),

    ('Tristan Stubbs',                'active_status',       'Active'),
    ('Tristan Stubbs',                'country',              'South Africa'),
    ('Tristan Stubbs',                'batting_hand',         'Right'),
    ('Tristan Stubbs',                'bowling_style',        'Right-arm Spin'),
    ('Tristan Stubbs',                'role',                 'Batter'),
    ('Tristan Stubbs',                'combined_matches',     '105'),
    ('Tristan Stubbs',                'combined_runs',        '3400'),
    ('Tristan Stubbs',                'combined_wickets',     '7'),
    ('Tristan Stubbs',                'debut_year',           '2022'),

    ('Anrich Nortje',                'active_status',       'Active'),
    ('Anrich Nortje',                'country',              'South Africa'),
    ('Anrich Nortje',                'batting_hand',         'Right'),
    ('Anrich Nortje',                'bowling_style',        'Right-arm Pace'),
    ('Anrich Nortje',                'role',                 'Bowler'),
    ('Anrich Nortje',                'combined_matches',     '110'),
    ('Anrich Nortje',                'combined_runs',        '250'),
    ('Anrich Nortje',                'combined_wickets',     '190'),
    ('Anrich Nortje',                'debut_year',           '2019'),

    ('Litton Das',                   'active_status',       'Active'),
    ('Litton Das',                   'country',              'Bangladesh'),
    ('Litton Das',                   'batting_hand',         'Right'),
    ('Litton Das',                   'bowling_style',        'Right-arm Spin'),
    ('Litton Das',                   'role',                 'Wicketkeeper-Batter'),
    ('Litton Das',                   'combined_matches',     '265'),
    ('Litton Das',                   'combined_runs',        '8400'),
    ('Litton Das',                   'combined_wickets',     '4'),
    ('Litton Das',                   'debut_year',           '2015'),

    ('Sikandar Raza',                'active_status',       'Active'),
    ('Sikandar Raza',                'country',              'Zimbabwe'),
    ('Sikandar Raza',                'batting_hand',         'Right'),
    ('Sikandar Raza',                'bowling_style',        'Right-arm Spin'),
    ('Sikandar Raza',                'role',                 'All-rounder'),
    ('Sikandar Raza',                'combined_matches',     '305'),
    ('Sikandar Raza',                'combined_runs',        '8900'),
    ('Sikandar Raza',                'combined_wickets',     '210'),
    ('Sikandar Raza',                'debut_year',           '2013'),

    ('Ibrahim Zadran',               'active_status',       'Active'),
    ('Ibrahim Zadran',               'country',              'Afghanistan'),
    ('Ibrahim Zadran',               'batting_hand',         'Right'),
    ('Ibrahim Zadran',               'bowling_style',        'Right-arm Pace'),
    ('Ibrahim Zadran',               'role',                 'Batter'),
    ('Ibrahim Zadran',               'combined_matches',     '102'),
    ('Ibrahim Zadran',               'combined_runs',        '3771'),
    ('Ibrahim Zadran',               'combined_wickets',     '2'),
    ('Ibrahim Zadran',               'debut_year',           '2019'),

    ('Andrew Balbirnie',             'active_status',       'Active'),
    ('Andrew Balbirnie',             'country',              'Ireland'),
    ('Andrew Balbirnie',             'batting_hand',         'Right'),
    ('Andrew Balbirnie',             'bowling_style',        'Right-arm Spin'),
    ('Andrew Balbirnie',             'role',                 'Batter'),
    ('Andrew Balbirnie',             'combined_matches',     '220'),
    ('Andrew Balbirnie',             'combined_runs',        '7000'),
    ('Andrew Balbirnie',             'combined_wickets',     '4'),
    ('Andrew Balbirnie',             'debut_year',           '2010'),

    ('Brandon McMullen',             'active_status',       'Active'),
    ('Brandon McMullen',             'country',              'Scotland'),
    ('Brandon McMullen',             'batting_hand',         'Right'),
    ('Brandon McMullen',             'bowling_style',        'Right-arm Pace'),
    ('Brandon McMullen',             'role',                 'All-rounder'),
    ('Brandon McMullen',             'combined_matches',     '85'),
    ('Brandon McMullen',             'combined_runs',        '2050'),
    ('Brandon McMullen',             'combined_wickets',     '60'),
    ('Brandon McMullen',             'debut_year',           '2022'),

    ('Scott Edwards',                'active_status',       'Active'),
    ('Scott Edwards',                'country',              'Netherlands'),
    ('Scott Edwards',                'batting_hand',         'Right'),
    ('Scott Edwards',                'bowling_style',        'Hasn''t Bowled'),
    ('Scott Edwards',                'role',                 'Wicketkeeper-Batter'),
    ('Scott Edwards',                'combined_matches',     '160'),
    ('Scott Edwards',                'combined_runs',        '3300'),
    ('Scott Edwards',                'combined_wickets',     '0'),
    ('Scott Edwards',                'debut_year',           '2018')
) AS v("PlayerName", "AttrKey", "Value")
JOIN "Players" p ON p."Name" = v."PlayerName"
JOIN "AttributeDefinitions" ad ON ad."Key" = v."AttrKey" AND ad."SportId" = p."SportId"
ON CONFLICT ("PlayerId", "AttributeDefinitionId") DO UPDATE SET
    "Value" = EXCLUDED."Value";
