-- Men's International Cricket players, batch 8 (30 players, bringing the
-- roster to 240 total: batches 1-7's 210 + batch 8's 30). Same upsert
-- pattern as prior batches: Players upserts on the unique Name constraint,
-- PlayerAttributeValues upserts on the existing unique (PlayerId,
-- AttributeDefinitionId) constraint, both scoped to the
-- "cricket-men-international" Sport. No overrides in this batch -- every
-- row is IsOverridden = false, DifficultyOverride = NULL.

INSERT INTO "Players" ("SportId", "Name", "IsOverridden", "DifficultyOverride")
SELECT s."Id", v."Name", v."IsOverridden", v."DifficultyOverride"
FROM "Sports" s
CROSS JOIN (VALUES
    ('Shivam Dube',               false, NULL),
    ('Abhishek Sharma',           false, NULL),
    ('Prasidh Krishna',           false, NULL),
    ('Rinku Singh',               false, NULL),
    ('Brydon Carse',              false, NULL),
    ('Jamie Smith',               false, NULL),
    ('Matthew Potts',             false, NULL),
    ('Mohammad Wasim Jr',         false, NULL),
    ('Iftikhar Ahmed',            false, NULL),
    ('Shadab Khan',               false, NULL),
    ('Sherfane Rutherford',       false, NULL),
    ('Romario Shepherd',          false, NULL),
    ('Gudakesh Motie',            false, NULL),
    ('Kyle Mayers',               false, NULL),
    ('Mark Chapman',              false, NULL),
    ('Ish Sodhi',                 false, NULL),
    ('Tim Seifert',               false, NULL),
    ('Ryan Rickelton',            false, NULL),
    ('Rassie van der Dussen',     false, NULL),
    ('Wayne Parnell',             false, NULL),
    ('Dhananjaya de Silva',       false, NULL),
    ('Kusal Perera',              false, NULL),
    ('Towhid Hridoy',             false, NULL),
    ('Karim Janat',               false, NULL),
    ('Craig Ervine',              false, NULL),
    ('Ryan Burl',                 false, NULL),
    ('Blessing Muzarabani',       false, NULL),
    ('Mark Adair',                false, NULL),
    ('George Dockrell',           false, NULL),
    ('Harshit Rana',              false, NULL)
) AS v("Name", "IsOverridden", "DifficultyOverride")
WHERE s."Slug" = 'cricket-men-international'
ON CONFLICT ("Name") DO UPDATE SET
    "SportId" = EXCLUDED."SportId",
    "IsOverridden" = CASE WHEN "Players"."IsOverridden" THEN "Players"."IsOverridden" ELSE EXCLUDED."IsOverridden" END,
    "DifficultyOverride" = CASE WHEN "Players"."IsOverridden" THEN "Players"."DifficultyOverride" ELSE EXCLUDED."DifficultyOverride" END;

-- One row per (player, attribute) pair. PlayerId/AttributeDefinitionId are
-- resolved by name/key lookup (scoped to each player's own SportId), so
-- this file has no dependency on insertion order or id values, and can
-- never cross-attach to cricket-women-international's AttributeDefinitions.
INSERT INTO "PlayerAttributeValues" ("PlayerId", "AttributeDefinitionId", "Value")
SELECT p."Id", ad."Id", v."Value"
FROM (VALUES
    -- Player,                          AttrKey,               Value
    ('Shivam Dube',                     'active_status',       'Active'),
    ('Shivam Dube',                     'country',              'India'),
    ('Shivam Dube',                     'batting_hand',         'Left'),
    ('Shivam Dube',                     'bowling_style',        'Right-arm Pace'),
    ('Shivam Dube',                     'role',                 'All-rounder'),
    ('Shivam Dube',                     'combined_matches',     '100'),
    ('Shivam Dube',                     'combined_runs',        '1800'),
    ('Shivam Dube',                     'combined_wickets',     '35'),
    ('Shivam Dube',                     'debut_year',           '2019'),

    ('Abhishek Sharma',                 'active_status',       'Active'),
    ('Abhishek Sharma',                 'country',              'India'),
    ('Abhishek Sharma',                 'batting_hand',         'Left'),
    ('Abhishek Sharma',                 'bowling_style',        'Left-arm Spin'),
    ('Abhishek Sharma',                 'role',                 'Batting All-rounder'),
    ('Abhishek Sharma',                 'combined_matches',     '40'),
    ('Abhishek Sharma',                 'combined_runs',        '1300'),
    ('Abhishek Sharma',                 'combined_wickets',     '10'),
    ('Abhishek Sharma',                 'debut_year',           '2024'),

    ('Prasidh Krishna',                 'active_status',       'Active'),
    ('Prasidh Krishna',                 'country',              'India'),
    ('Prasidh Krishna',                 'batting_hand',         'Right'),
    ('Prasidh Krishna',                 'bowling_style',        'Right-arm Pace'),
    ('Prasidh Krishna',                 'role',                 'Bowler'),
    ('Prasidh Krishna',                 'combined_matches',     '49'),
    ('Prasidh Krishna',                 'combined_runs',        '225'),
    ('Prasidh Krishna',                 'combined_wickets',     '90'),
    ('Prasidh Krishna',                 'debut_year',           '2021'),

    ('Rinku Singh',                     'active_status',       'Active'),
    ('Rinku Singh',                     'country',              'India'),
    ('Rinku Singh',                     'batting_hand',         'Left'),
    ('Rinku Singh',                     'bowling_style',        'Right-arm Spin'),
    ('Rinku Singh',                     'role',                 'Batter'),
    ('Rinku Singh',                     'combined_matches',     '47'),
    ('Rinku Singh',                     'combined_runs',        '1100'),
    ('Rinku Singh',                     'combined_wickets',     '8'),
    ('Rinku Singh',                     'debut_year',           '2023'),

    ('Brydon Carse',                    'active_status',       'Active'),
    ('Brydon Carse',                    'country',              'England'),
    ('Brydon Carse',                    'batting_hand',         'Right'),
    ('Brydon Carse',                    'bowling_style',        'Right-arm Pace'),
    ('Brydon Carse',                    'role',                 'Bowling All-rounder'),
    ('Brydon Carse',                    'combined_matches',     '45'),
    ('Brydon Carse',                    'combined_runs',        '700'),
    ('Brydon Carse',                    'combined_wickets',     '97'),
    ('Brydon Carse',                    'debut_year',           '2021'),

    ('Jamie Smith',                     'active_status',       'Active'),
    ('Jamie Smith',                     'country',              'England'),
    ('Jamie Smith',                     'batting_hand',         'Right'),
    ('Jamie Smith',                     'bowling_style',        'Hasn''t Bowled'),
    ('Jamie Smith',                     'role',                 'Wicketkeeper-Batter'),
    ('Jamie Smith',                     'combined_matches',     '40'),
    ('Jamie Smith',                     'combined_runs',        '2200'),
    ('Jamie Smith',                     'combined_wickets',     '0'),
    ('Jamie Smith',                     'debut_year',           '2023'),

    ('Matthew Potts',                   'active_status',       'Active'),
    ('Matthew Potts',                   'country',              'England'),
    ('Matthew Potts',                   'batting_hand',         'Right'),
    ('Matthew Potts',                   'bowling_style',        'Right-arm Pace'),
    ('Matthew Potts',                   'role',                 'Bowler'),
    ('Matthew Potts',                   'combined_matches',     '26'),
    ('Matthew Potts',                   'combined_runs',        '225'),
    ('Matthew Potts',                   'combined_wickets',     '58'),
    ('Matthew Potts',                   'debut_year',           '2022'),

    ('Mohammad Wasim Jr',               'active_status',       'Active'),
    ('Mohammad Wasim Jr',               'country',              'Pakistan'),
    ('Mohammad Wasim Jr',               'batting_hand',         'Right'),
    ('Mohammad Wasim Jr',               'bowling_style',        'Right-arm Pace'),
    ('Mohammad Wasim Jr',               'role',                 'Bowler'),
    ('Mohammad Wasim Jr',               'combined_matches',     '92'),
    ('Mohammad Wasim Jr',               'combined_runs',        '275'),
    ('Mohammad Wasim Jr',               'combined_wickets',     '120'),
    ('Mohammad Wasim Jr',               'debut_year',           '2021'),

    ('Iftikhar Ahmed',                  'active_status',       'Retired'),
    ('Iftikhar Ahmed',                  'country',              'Pakistan'),
    ('Iftikhar Ahmed',                  'batting_hand',         'Right'),
    ('Iftikhar Ahmed',                  'bowling_style',        'Right-arm Spin'),
    ('Iftikhar Ahmed',                  'role',                 'Batter'),
    ('Iftikhar Ahmed',                  'combined_matches',     '190'),
    ('Iftikhar Ahmed',                  'combined_runs',        '3200'),
    ('Iftikhar Ahmed',                  'combined_wickets',     '55'),
    ('Iftikhar Ahmed',                  'debut_year',           '2015'),

    ('Shadab Khan',                     'active_status',       'Active'),
    ('Shadab Khan',                     'country',              'Pakistan'),
    ('Shadab Khan',                     'batting_hand',         'Right'),
    ('Shadab Khan',                     'bowling_style',        'Right-arm Spin'),
    ('Shadab Khan',                     'role',                 'All-rounder'),
    ('Shadab Khan',                     'combined_matches',     '227'),
    ('Shadab Khan',                     'combined_runs',        '2800'),
    ('Shadab Khan',                     'combined_wickets',     '260'),
    ('Shadab Khan',                     'debut_year',           '2017'),

    ('Sherfane Rutherford',             'active_status',       'Active'),
    ('Sherfane Rutherford',             'country',              'West Indies'),
    ('Sherfane Rutherford',             'batting_hand',         'Left'),
    ('Sherfane Rutherford',             'bowling_style',        'Right-arm Pace'),
    ('Sherfane Rutherford',             'role',                 'Batter'),
    ('Sherfane Rutherford',             'combined_matches',     '100'),
    ('Sherfane Rutherford',             'combined_runs',        '1800'),
    ('Sherfane Rutherford',             'combined_wickets',     '10'),
    ('Sherfane Rutherford',             'debut_year',           '2018'),

    ('Romario Shepherd',                'active_status',       'Active'),
    ('Romario Shepherd',                'country',              'West Indies'),
    ('Romario Shepherd',                'batting_hand',         'Right'),
    ('Romario Shepherd',                'bowling_style',        'Right-arm Pace'),
    ('Romario Shepherd',                'role',                 'Bowling All-rounder'),
    ('Romario Shepherd',                'combined_matches',     '100'),
    ('Romario Shepherd',                'combined_runs',        '1200'),
    ('Romario Shepherd',                'combined_wickets',     '120'),
    ('Romario Shepherd',                'debut_year',           '2019'),

    ('Gudakesh Motie',                  'active_status',       'Active'),
    ('Gudakesh Motie',                  'country',              'West Indies'),
    ('Gudakesh Motie',                  'batting_hand',         'Left'),
    ('Gudakesh Motie',                  'bowling_style',        'Left-arm Spin'),
    ('Gudakesh Motie',                  'role',                 'Bowling All-rounder'),
    ('Gudakesh Motie',                  'combined_matches',     '100'),
    ('Gudakesh Motie',                  'combined_runs',        '450'),
    ('Gudakesh Motie',                  'combined_wickets',     '155'),
    ('Gudakesh Motie',                  'debut_year',           '2021'),

    ('Kyle Mayers',                     'active_status',       'Active'),
    ('Kyle Mayers',                     'country',              'West Indies'),
    ('Kyle Mayers',                     'batting_hand',         'Left'),
    ('Kyle Mayers',                     'bowling_style',        'Right-arm Pace'),
    ('Kyle Mayers',                     'role',                 'Batting All-rounder'),
    ('Kyle Mayers',                     'combined_matches',     '95'),
    ('Kyle Mayers',                     'combined_runs',        '2600'),
    ('Kyle Mayers',                     'combined_wickets',     '35'),
    ('Kyle Mayers',                     'debut_year',           '2020'),

    ('Mark Chapman',                    'active_status',       'Active'),
    ('Mark Chapman',                    'country',              'New Zealand'),
    ('Mark Chapman',                    'batting_hand',         'Left'),
    ('Mark Chapman',                    'bowling_style',        'Left-arm Spin'),
    ('Mark Chapman',                    'role',                 'All-rounder'),
    ('Mark Chapman',                    'combined_matches',     '170'),
    ('Mark Chapman',                    'combined_runs',        '4200'),
    ('Mark Chapman',                    'combined_wickets',     '25'),
    ('Mark Chapman',                    'debut_year',           '2014'),

    ('Ish Sodhi',                       'active_status',       'Active'),
    ('Ish Sodhi',                       'country',              'New Zealand'),
    ('Ish Sodhi',                       'batting_hand',         'Right'),
    ('Ish Sodhi',                       'bowling_style',        'Right-arm Spin'),
    ('Ish Sodhi',                       'role',                 'Bowler'),
    ('Ish Sodhi',                       'combined_matches',     '215'),
    ('Ish Sodhi',                       'combined_runs',        '1800'),
    ('Ish Sodhi',                       'combined_wickets',     '275'),
    ('Ish Sodhi',                       'debut_year',           '2013'),

    ('Tim Seifert',                     'active_status',       'Active'),
    ('Tim Seifert',                     'country',              'New Zealand'),
    ('Tim Seifert',                     'batting_hand',         'Right'),
    ('Tim Seifert',                     'bowling_style',        'Hasn''t Bowled'),
    ('Tim Seifert',                     'role',                 'Wicketkeeper-Batter'),
    ('Tim Seifert',                     'combined_matches',     '135'),
    ('Tim Seifert',                     'combined_runs',        '3200'),
    ('Tim Seifert',                     'combined_wickets',     '0'),
    ('Tim Seifert',                     'debut_year',           '2018'),

    ('Ryan Rickelton',                  'active_status',       'Active'),
    ('Ryan Rickelton',                  'country',              'South Africa'),
    ('Ryan Rickelton',                  'batting_hand',         'Left'),
    ('Ryan Rickelton',                  'bowling_style',        'Left-arm Spin'),
    ('Ryan Rickelton',                  'role',                 'Wicketkeeper-Batter'),
    ('Ryan Rickelton',                  'combined_matches',     '55'),
    ('Ryan Rickelton',                  'combined_runs',        '1800'),
    ('Ryan Rickelton',                  'combined_wickets',     '5'),
    ('Ryan Rickelton',                  'debut_year',           '2022'),

    ('Rassie van der Dussen',           'active_status',       'Retired'),
    ('Rassie van der Dussen',           'country',              'South Africa'),
    ('Rassie van der Dussen',           'batting_hand',         'Right'),
    ('Rassie van der Dussen',           'bowling_style',        'Right-arm Spin'),
    ('Rassie van der Dussen',           'role',                 'Batter'),
    ('Rassie van der Dussen',           'combined_matches',     '146'),
    ('Rassie van der Dussen',           'combined_runs',        '4968'),
    ('Rassie van der Dussen',           'combined_wickets',     '1'),
    ('Rassie van der Dussen',           'debut_year',           '2018'),

    ('Wayne Parnell',                   'active_status',       'Retired'),
    ('Wayne Parnell',                   'country',              'South Africa'),
    ('Wayne Parnell',                   'batting_hand',         'Left'),
    ('Wayne Parnell',                   'bowling_style',        'Right-arm Pace'),
    ('Wayne Parnell',                   'role',                 'All-rounder'),
    ('Wayne Parnell',                   'combined_matches',     '130'),
    ('Wayne Parnell',                   'combined_runs',        '1400'),
    ('Wayne Parnell',                   'combined_wickets',     '170'),
    ('Wayne Parnell',                   'debut_year',           '2009'),

    ('Dhananjaya de Silva',             'active_status',       'Active'),
    ('Dhananjaya de Silva',             'country',              'Sri Lanka'),
    ('Dhananjaya de Silva',             'batting_hand',         'Right'),
    ('Dhananjaya de Silva',             'bowling_style',        'Right-arm Spin'),
    ('Dhananjaya de Silva',             'role',                 'Batting All-rounder'),
    ('Dhananjaya de Silva',             'combined_matches',     '230'),
    ('Dhananjaya de Silva',             'combined_runs',        '7500'),
    ('Dhananjaya de Silva',             'combined_wickets',     '100'),
    ('Dhananjaya de Silva',             'debut_year',           '2015'),

    ('Kusal Perera',                    'active_status',       'Active'),
    ('Kusal Perera',                    'country',              'Sri Lanka'),
    ('Kusal Perera',                    'batting_hand',         'Left'),
    ('Kusal Perera',                    'bowling_style',        'Right-arm Pace'),
    ('Kusal Perera',                    'role',                 'Wicketkeeper-Batter'),
    ('Kusal Perera',                    'combined_matches',     '233'),
    ('Kusal Perera',                    'combined_runs',        '6749'),
    ('Kusal Perera',                    'combined_wickets',     '6'),
    ('Kusal Perera',                    'debut_year',           '2013'),

    ('Towhid Hridoy',                   'active_status',       'Active'),
    ('Towhid Hridoy',                   'country',              'Bangladesh'),
    ('Towhid Hridoy',                   'batting_hand',         'Right'),
    ('Towhid Hridoy',                   'bowling_style',        'Right-arm Spin'),
    ('Towhid Hridoy',                   'role',                 'Batter'),
    ('Towhid Hridoy',                   'combined_matches',     '105'),
    ('Towhid Hridoy',                   'combined_runs',        '2800'),
    ('Towhid Hridoy',                   'combined_wickets',     '5'),
    ('Towhid Hridoy',                   'debut_year',           '2023'),

    ('Karim Janat',                     'active_status',       'Active'),
    ('Karim Janat',                     'country',              'Afghanistan'),
    ('Karim Janat',                     'batting_hand',         'Right'),
    ('Karim Janat',                     'bowling_style',        'Right-arm Pace'),
    ('Karim Janat',                     'role',                 'Batting All-rounder'),
    ('Karim Janat',                     'combined_matches',     '92'),
    ('Karim Janat',                     'combined_runs',        '1400'),
    ('Karim Janat',                     'combined_wickets',     '81'),
    ('Karim Janat',                     'debut_year',           '2016'),

    ('Craig Ervine',                    'active_status',       'Active'),
    ('Craig Ervine',                    'country',              'Zimbabwe'),
    ('Craig Ervine',                    'batting_hand',         'Left'),
    ('Craig Ervine',                    'bowling_style',        'Right-arm Spin'),
    ('Craig Ervine',                    'role',                 'Batter'),
    ('Craig Ervine',                    'combined_matches',     '220'),
    ('Craig Ervine',                    'combined_runs',        '6500'),
    ('Craig Ervine',                    'combined_wickets',     '20'),
    ('Craig Ervine',                    'debut_year',           '2010'),

    ('Ryan Burl',                       'active_status',       'Active'),
    ('Ryan Burl',                       'country',              'Zimbabwe'),
    ('Ryan Burl',                       'batting_hand',         'Left'),
    ('Ryan Burl',                       'bowling_style',        'Right-arm Spin'),
    ('Ryan Burl',                       'role',                 'All-rounder'),
    ('Ryan Burl',                       'combined_matches',     '125'),
    ('Ryan Burl',                       'combined_runs',        '1800'),
    ('Ryan Burl',                       'combined_wickets',     '117'),
    ('Ryan Burl',                       'debut_year',           '2017'),

    ('Blessing Muzarabani',             'active_status',       'Active'),
    ('Blessing Muzarabani',             'country',              'Zimbabwe'),
    ('Blessing Muzarabani',             'batting_hand',         'Right'),
    ('Blessing Muzarabani',             'bowling_style',        'Right-arm Pace'),
    ('Blessing Muzarabani',             'role',                 'Bowler'),
    ('Blessing Muzarabani',             'combined_matches',     '155'),
    ('Blessing Muzarabani',             'combined_runs',        '450'),
    ('Blessing Muzarabani',             'combined_wickets',     '240'),
    ('Blessing Muzarabani',             'debut_year',           '2017'),

    ('Mark Adair',                      'active_status',       'Active'),
    ('Mark Adair',                      'country',              'Ireland'),
    ('Mark Adair',                      'batting_hand',         'Right'),
    ('Mark Adair',                      'bowling_style',        'Right-arm Pace'),
    ('Mark Adair',                      'role',                 'Bowling All-rounder'),
    ('Mark Adair',                      'combined_matches',     '135'),
    ('Mark Adair',                      'combined_runs',        '1800'),
    ('Mark Adair',                      'combined_wickets',     '150'),
    ('Mark Adair',                      'debut_year',           '2018'),

    ('George Dockrell',                 'active_status',       'Active'),
    ('George Dockrell',                 'country',              'Ireland'),
    ('George Dockrell',                 'batting_hand',         'Right'),
    ('George Dockrell',                 'bowling_style',        'Left-arm Spin'),
    ('George Dockrell',                 'role',                 'All-rounder'),
    ('George Dockrell',                 'combined_matches',     '281'),
    ('George Dockrell',                 'combined_runs',        '3200'),
    ('George Dockrell',                 'combined_wickets',     '180'),
    ('George Dockrell',                 'debut_year',           '2010'),

    ('Harshit Rana',                    'active_status',       'Active'),
    ('Harshit Rana',                    'country',              'India'),
    ('Harshit Rana',                    'batting_hand',         'Right'),
    ('Harshit Rana',                    'bowling_style',        'Right-arm Pace'),
    ('Harshit Rana',                    'role',                 'Bowling All-rounder'),
    ('Harshit Rana',                    'combined_matches',     '27'),
    ('Harshit Rana',                    'combined_runs',        '200'),
    ('Harshit Rana',                    'combined_wickets',     '40'),
    ('Harshit Rana',                    'debut_year',           '2024')
) AS v("PlayerName", "AttrKey", "Value")
JOIN "Players" p ON p."Name" = v."PlayerName"
JOIN "AttributeDefinitions" ad ON ad."Key" = v."AttrKey" AND ad."SportId" = p."SportId"
ON CONFLICT ("PlayerId", "AttributeDefinitionId") DO UPDATE SET
    "Value" = EXCLUDED."Value"
WHERE "PlayerAttributeValues"."IsManuallyEdited" = false;
